### ISSUE TITLE
JRE HeaderDoc warnings

### ISSUE THREAD

**Issue by adil-hussain-84** [google/j2objc#1025]
I'm seeing a number of warnings in my Xcode project about bad HeaderDoc in the J2ObjC headers.

For example:
- j2objc-2.3.1/include/java/lang/reflect/AnnotatedElement.h:92:38: Expected quoted string after equals sign
- j2objc-2.3.1/include/java/lang/reflect/AnnotatedElement.h:92:38: HTML start tag prematurely ended, expected attribute name or '>'
- j2objc-2.3.1/include/java/util/HashMap.h:1333:3: '@return' command used in a comment that is attached to a method returning void

**Comment by antonio-cortes-perez** [comment]
I do not think this is specific to the release 2.3.1. We tried to balance the cost-benefit of translating Javadoc to HeaderDoc.

Since you can always refer to the original Javadocs, you could rebuild the distribution without the comments by removing the flag “--doc-comments” in:

https://github.com/google/j2objc/blob/master/jre_emul/Makefile#L40

**Comment by adil-hussain-84** [comment]
Okay. Thank you for the response @antonio-cortes-perez.

**Comment by tomball** [comment]
FWIW, those errors are in OpenJDK, which is pulled to Android's libcore library, which we then pull. So we can stay up-to-date with Android, we try to minimize the changes we make to just those that are necessary for that code to work on iOS. 

If anyone wants to contribute to OpenJDK (nice bragging rights), consider fixing these warnings and submitting a pull request there.
