### ISSUE TITLE
Enhancement request: allow @Weak annotation to generate __unsafe_unretained or __weak

### ISSUE THREAD

**Issue by yegork78** [google/j2objc#1028]
The request is for a new command line argument for j2objc to optionally generate `__weak` attribute, instead of `__unsafe_unretained`, for `@Weak` annotation.

**Comment by danieldickison** [comment]
Why not use Java's `WeakReference`? If it's possible that a variable could be accessed after it's no longer strongly referenced, it seems likely that you would need similar functionality on the Java side as well.

**Comment by sparseware** [comment]
I would go a step further in saying that @Weak* so go back to their previous behavior as the name implies and if unsafe/un-retained is to be supported it should have it's own annotation. However, I am not aware of any mechanism to check if a pointer is valid,  so the only safe use of unsafe/un-retained instance variable is to check if it is null. Any attempt to use weak in an environment that does not support it should be a compile (or transpile) time error left to the developer to deal with.

**Comment by sparseware** [comment]
@danieldickison I think most people who use the @Weak annotation to prevent memory leaks that can happen in Objective-C but not in Java. As you know Java's GC is much more sophisticated than ARC and the @Weak annotations helps programmers deal with the difference without refactoring their code. Having and unsafe/un-retained instance variable in ARC means you can never safely use the variable without having some other means of verifying its validity.

**Comment by tomball** [comment]
If you want a field that may vanish and be validated at runtime, follow Daniel's suggestion to use WeakReference. The @Weak annotation should only be used to break retention cycles, and does not have the same semantics as __weak (we need a new annotation name, like DontRetain). An example where this is very appropriate is LinkedList.Node, where its prev field is @Weak, while its next field isn't. This ensures that when a LinkedList is deleted, its nodes all are. Normally these fields are private (they're an aspect of the hidden implementation), and it's worth taking a hard look at any that aren't.

With this big restriction, it doesn't matter whether generated code uses __weak or unsafe/unretained, since **the only code that should reference those fields is generated**.

As I've had to do in the past, I must again deeply apologize for naming the project "J2ObjC", since it's purpose has always been to compile Java to iOS, not translate it into another language. "ObjC" shouldn't have been part of the name, because (like @Weak fields) that implementation should have been hidden from its public API. This is why engineers need to tolerate their marketing people, as most actually know what they're doing. :-)

**Comment by sparseware** [comment]
What you are saying is correct. I think there is a misunderstanding of why we want it. Your stated reason for using **@weak** is the only reason anyone would use it for (to break retention cycles). No variable marked with **@weak** will ever be set to null in a Java environment. That only happens in ObjC.

If I have my own implementation of **LinkedList** (or something similar) in Java, I would have to rewrite it to make it work with J2ObjC. Aside form the rewrite work; it would also become much slower. I have simply modified the translator instead.  If I were forced to use a non-ARC environment, I would probable modify the translator the generate macro calls, to replace direct access to the variable with a function call that manages the memory for me. 

A differently named annotation would be fine. I think most folks who want this back just want a way to break retention cycles within their own code.
