### ISSUE TITLE
Add Reflection Data to SSLException?

### ISSUE THREAD

**Issue by omerp** [google/j2objc#1032]
Following up on a crash I've seen - it seems like IosHttpURLConnection uses SSLException via reflection (https://bit.ly/2SHtoPW), however - SSLException does not seem to have the @ReflectionSupport annotation attached to it (https://bit.ly/2S7JnkV). Would adding it help mitigating the crash?

Error seen:
ComGoogleJ2objcReflectionStrippedError at IOSClass_GetMetadataOrFail: ComGoogleJ2objcReflectionStrippedError: JavaxNetSslSSLException: Reflection is unavailable. Fix this by avoiding reflection or building without --strip-reflection.

**Comment by tomball** [comment]
Yes, that's right. The runtime doesn't require reflection to load a class dynamically (it just has to be linked into the app), but querying that class for a constructor requires Java reflection. Since you found the bug, do you want to submit a pull request with the @ReflectionSupport(FULL) annotation added to get the credit. If not, we can get to it later this week.

**Comment by omerp** [comment]
I can send a PR, but I won't be able to test it (beyond unit tests) for a while.
If you don't get to it, I'll try followup in ~2 weeks when I'm back :)

**Comment by antonio-cortes-perez** [comment]
I added the annotation to SSLException. The fix will be visible after our next repo sync.

**Comment by antonio-cortes-perez** [comment]
Fixed in latest source code.
