### ISSUE TITLE
different versions of j2objc-annotations 1.1 in gradle

### ISSUE THREAD

**Issue by pvyhnal-generalbytes** [google/j2objc#1033]
com.google.j2objc:j2objc-annotations:1.1 has different checksums when downloaded from jcenter and maven central
```
2994a7eb78f2710bd3d3bfb639b2c94e219cedac0d4d084d516e78c16dddecf6 jcenter
40ceb7157feb263949e0f503fe5f71689333a621021aa20ce0d0acee3badaa0f maven central
```
which is causing problems in our build when we download dependencies from different repositories in different build environments 

v. 1.1 is used by latest version of guava

**Comment by tomball** [comment]
The j2objc team had nothing to do with the jcenter repository submission, so some random developer built their own version and pushed it. It's therefore very unlikely we have the access rights to make changes. I wrote an email to Bintray (they manage jcenter.bintray.com) asking that they either remove or mirror the Maven Central distribution.

We also don't support the [j2objc Gradle plugin](https://github.com/j2objc-contrib/j2objc-gradle) (it was contributed by external developers).

We therefore recommend that you only use Maven Central. Documentation on specifying a repository can be found [here](https://maven.apache.org/pom.html#Repository).

**Comment by pvyhnal-generalbytes** [comment]
Thanks, could you please update us when Bintray reply?

**Comment by tomball** [comment]
Sure, but I can't promise they will. Feel free to also send them a support request (https://bintray.com/, click on "Contact Us" at the page bottom), and perhaps they will give the issue higher priority.

FYI, I updated Maven Central with j2objc-annotations version 2.0 and 2.2 releases. The current j2objc release is 2.3.1, but the annotations haven't changed since 2.2.

**Comment by sixpi** [comment]
The maven central copy of j2objc-annotations version 1.1 seems to match the copy in bintray now - was this an intentional change?

**Comment by tomball** [comment]
As I suggested before, you need to ask bintray support (https://bintray.com/, click on "Contact Us" at the page bottom), as we have nothing to do with that project.

**Comment by sixpi** [comment]
I understand, but the current copy from maven central now does not match
our old copy from maven central. Does google control the copy in maven
central?

**Comment by tomball** [comment]
We have never updated an existing jar (I had assumed that wasn't possible). Whenever we've found bugs in a release, we've always made a new release with an incremented version number. The important bit to know is that we only submit to Sonatype.org, and since they manage Maven Central, that's the binary that should be used if there is ever a discrepancy. Maybe Maven Central used to use a different or buggy checksum calculation tool, or maybe when Maven Central was updated something changed, but those are just guesses.

If this continues to be a concern for your team, consider publishing your own version from your org to Maven Central or jcenter. That way you have full control over it.

**Comment by sixpi** [comment]
I see, I think whoever maintains the jcenter copy must have recently realized their copy was incorrect, and updated their jar to match yours from maven central. That seems like the most likely explanation to me.

**Comment by sixpi** [comment]
I think you could close this issue, since the copy from jcenter and Maven central match up now.

**Comment by tomball** [comment]
Thanks for following up on this.
