### ISSUE TITLE
Generating protocols and class from Java interface

### ISSUE THREAD

**Issue by losharik** [google/j2objc#1050]
Hello. Noticed the problem when generating the protocol and class from the interface:

```
public interface ImageDataStorage
{
    String CROSS = "CROSS";
    String ARROW_LEFT = "ARROW_LEFT";

    ImageData get(String imageId);
}
```

At the output we get the protocol and class of the same name, in the case of objective c this is not a problem, but Swift will not see the protocol.

**Comment by tomball** [comment]
Are you building with j2objc's --swift-friendly flag? One of the things that flag does is generate accessor methods for those constants:
```
@interface ImageDataStorage : NSObject
@property (readonly, copy, class) NSString *CROSS NS_SWIFT_NAME(CROSS);
@property (readonly, copy, class) NSString *ARROW_LEFT NS_SWIFT_NAME(ARROW_LEFT);

+ (NSString *)CROSS;
+ (NSString *)ARROW_LEFT;
@end
```
The Swift importer needs accessor methods to include these constants. They aren't generated by default since they just take up space in Objective C where the C functions can be used instead.

**Comment by losharik** [comment]
Yes, I use swift friendly flag, the question is how do I get to the protocol from swift.

```
@protocol MBImageData;

@protocol MBImageDataStorage < JavaObject >

- (id<MBImageData>)getWithNSString:(NSString *)imageId;

@end

@interface MBImageDataStorage : NSObject
@property (readonly, copy, class) NSString *CROSS NS_SWIFT_NAME(CROSS);
@property (readonly, copy, class) NSString *ARROW_LEFT NS_SWIFT_NAME(ARROW_LEFT);

+ (NSString *)CROSS;

+ (NSString *)ARROW_LEFT;

@end
```

**Comment by tomball** [comment]
I reproduced the problem, and it's unfortunately a bug with the Swift importer. Objective C allows a class and a protocol to share a name (NSObject being a famous example). You differentiate between superclass and protocol in Objective C with <name>. Swift knows that if there is more than one superclass listed in a class definition, only the first is a class and the others have to be protocols. So it should be perfectly legal to import an Objective C class and protocol with the same name, since both languages clearly differentiate them.

The Swift importer doesn't appear to be that smart, though: even though the importer knows the class and protocol, it only appears to import the class. So when you use the protocol when declaring a class after its superclass, the compiler reports an error that you are trying to use multiple-inheritance. 

j2objc generates a class with a protocol from an interface when that interface declares constants, since an Objective C protocol can't declare them. In your example, if you remove the constants (or move them to a class), then the Swift importer imports the protocol correctly. It's unfortunate that only Java interfaces that define methods can be imported into Swift, at least until the importer is improved.

**Comment by losharik** [comment]
Can I try to add "Protocol" to the names of the protocol, then Swift should import it? Could you tell me where to find the generation of headers in the source?

**Comment by antonio-cortes-perez** [comment]
It looks like the Swift importer is already appending "Protocol". In Xcode, select the generated header file (e.g. ImageDataStorage.h), then in the Counterparts view, instead of the corresponding m file, select the output of the Swift importer (e.g. "ImageDataStorage.h (Swift 5 interface)". Here is a snippet of what I am seeing:

public protocol ImageDataStorageProtocol : JavaObject {
...
}
open class ImageDataStorage : NSObject {
...
}
