### ISSUE TITLE
@tball about circle_finder

### ISSUE THREAD

**Issue by radxe** [google/j2objc#1051]
Hello, @tomball ,
     My question is whether the circle_finder can find all possible circle references, can it find circle refence in container like hashmap, arraylist?  We just verify each found circle references, then pick which circle is true circle reference？  
     Maybe the found circle references were just a part of all possible circle references？ We need the found the reminder circle references from the source code?
     Can circle finder automaticly  set the @weakOuter for us? then we just don't care the circle reference problems？

Thank you for your great j2objc product!

**Comment by tomball** [comment]
The cycle_finder uses static analysis to locate cycles, and static analysis is limited in what it can find (that's why compilers can't find all bugs). So no, cycle_finder won't find all cycles. It also reports "false positives," where cycles are reported where they don't exist. Its main use is to report the easier cycles, and when used as a unit test, to catch some cycles when they are later created.

The way to find cycles is with Xcode's Leaks profiler. Since it examines the actual program execution instead of just its source code, the Leaks profiler will report real leaks and not report false positives. Each leak will have a stack trace to locate the offending class.

@WeakOuter is not a general-purpose cycle fixer: it's specifically used with non-static inner classes where an inner class object may live longer than the outer class. The easiest way to avoid issues with non-static inner classes is to make them static, as [Effective Java](http://thefinestartist.com/effective-java/22) recommends. We cannot make that change in j2objc's version of the Java Runtime since it's a public API, but you can make that change in your product.
