### ISSUE TITLE
Xcode Project Integration

### ISSUE THREAD

**Issue by PorterHoskins** [google/j2objc#1054]
I follow these instructions and get the following error:

<img width="847" alt="Screen Shot 2019-06-14 at 2 06 50 PM" src="https://user-images.githubusercontent.com/5604819/59535348-f60c5300-8ead-11e9-9194-8eeb031cf8a9.png">

clang: error: no such file or directory: '/Users/myuser/Library/Developer/Xcode/DerivedData/MyProject-arvkcxaffcevuzcteqhtjiefmitg/Build/Products/Debug-iphoneos/libjre_emul.a'

It appears my project is searching for the library in Derived Data but the build for libjre_emul.a is not using derived data. I tried adding Library search paths to the `dist` and `build_result` folders but it didn't work. Any ideas?

I am trying to build a dynamic framework using the library.

**Comment by tomball** [comment]
Does the JreEmulation project build successfully by itself? To verify this, build its JreJUnitTests target with a simulator device, and when the app loads, select the "All JRE Tests" line.

That said, it's probably been a very long time (in iOS years) since anyone has tried adding the JreEmulation project to another project (it's mostly used to run the JRE unit tests). An alternative is to build everything at the command line (cd $J2OBJC_HOME && make -j8 dist), then specify dist/include as a header search path in your project, and dist/lib as a library search path.

**Comment by PorterHoskins** [comment]
Yeah that works. Thanks

**Comment by alizainprasla** [comment]
I am getting same error when i build the project

`clang: error: no such file or directory: '/Users/currentuser/Library/Developer/Xcode/DerivedData/objctest-bajvsjeqpcnmkydoahfbwekzusfw/Build/Products/Debug-iphoneos/libjre_emul.a'`

I followed your last comment and tried to build **JreJUnitTests** with simulator device. it didn't build the app and throw error.

```
m: /usr/local/bin/j2objc/jre_emul/build_result/tests/arc/.translate_list_jre_emul_tests_arc: Permission denied
make: *** [/usr/local/bin/j2objc/jre_emul/build_result/tests/arc/.translate_mark_jre_emul_tests_arc] Error 1
Command ExternalBuildToolExecution failed with a nonzero exit code
```

am i not providing any permission?

**Comment by tomball** [comment]
First check that you have a recent Xcode installed (Xcode->About Xcode). 10.2 is the latest release, but anything from 9.0 on should be fine.

Next, don't ever install a source directory in /usr/local/bin -- all bin directories are for executables, not projects (my guess is that the ExternalBuildToolExecution failed because of this). To keep things clean, create a new directory in your home directory (don't use a name with spaces, as some projects break), then clone j2objc and any other source project in that directory. On my system, that directory is "~/src" (~ means the home directory), so "/Users/tball/src/j2objc" is where my local copy of the j2objc repository is kept. 

Next, make sure the j2objc project builds outside of Xcode by running "make -j8 dist" in the top-level j2objc project directory. All that ExternalBuildToolExecution command does is invoke this command, so trying to build a broken build within Xcode just makes it more confusing.

Finally, learning Xcode and iOS development using j2objc will be an exercise in frustration, since j2objc is an advanced build tool for very large (Gmail-sized) apps. If you have a small Android project you're hoping to use j2objc to avoid learning iOS development, save yourself the headaches and just rewrite it from scratch. It will be a little slow at first, but once you're comfortable in this environment, you'll be much more productive.
