### ISSUE TITLE
make: Nothing to be done for `SUFFIXES'. Not build in osx 

### ISSUE THREAD

**Issue by kaizer1** [google/j2objc#1100]
Hi, I decided to build a small example using this utility, downloaded it and tried to create an example in the folder with the command: make   - And I got this error: 

 make: Nothing to be done for `SUFFIXES'.  

  How to win it, knows what. It seems to me that the solution is very simple, but I can find

**Comment by tomball** [comment]
Thanks for bringing up this subject. SUFFIXES was a rule we started copying into the project's first make files, since that's what the docs we used at the time said to do. However, [the current doc for SUFFIX Rules](https://www.gnu.org/software/make/manual/html_node/Suffix-Rules.html) states that these rules are now obsolete, unnecessary, and only supported for backwards compatibility with old makefiles. So I went through all our makefiles and removed all SUFFIXES and .SUFFIXES lines, and sure enough, the build worked exactly the same. I'll commit a change later this week that removes all SUFFIXES lines.

To fix this, delete the SUFFIXES line from your makefile. Also, check that you are using the correct make by running "make -version", which on my system looks like this:
```
$ make -version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```
If your version is different and your system is a Mac, install the latest Xcode (it's free) which should include make in its command-line tools. If you're running this on a different system, install and use GNU Make. You'll need a Mac to compile the files j2objc generates, but the j2objc compiler works on any system with a Java 8 or 11 JDK installed.

**Comment by kaizer1** [comment]
Thank you very much for your reply. My system looks exactly the same

  SergeiLoskutnikovs-Mac-mini:~ sergeiloskutnikov$ make -version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

   And I have downloaded and installed the latest version of Xcode ( also Mac OSX)
However, I received this error, but now I will try to assemble without SUFFIXES

**Comment by kaizer1** [comment]
But still not going to... 
Building j2objc annotations
/Users/sergeiloskutnikov/Downloads/j2objc-master/install: line 1: Build: command not found
/Users/sergeiloskutnikov/Downloads/j2objc-master/install: line 2: ==================: command not found
/Users/sergeiloskutnikov/Downloads/j2objc-master/install: line 4: This: command not found
/Users/sergeiloskutnikov/Downloads/j2objc-master/install: line 6: syntax error near unexpected token `('
/Users/sergeiloskutnikov/Downloads/j2objc-master/install: line 6: ` * Xcode 7.1.1 or higher (https://developer.apple.com/xcode/)'
make[1]: *** [../dist/lib/j2objc_annotations.jar] Error 2
make: *** [annotations_dist] Error 2

 What is strange, according to the idea of a popular library, but thanks again for your answer. I will try and work so that everything works

**Comment by tomball** [comment]
There's no need to build the j2objc project to experiment with it; just download [the latest release](https://github.com/google/j2objc/releases/latest) and unzip it. This creates a j2objc-<version> subdirectory, which has the commands and libraries.
