### ISSUE TITLE
Classpath wildcards

### ISSUE THREAD

**Issue by blazek** [google/j2objc#1141]
It would be nice if j2objc -classpath parameter supported wildcards in the same way like javac, as documented here:  
https://docs.oracle.com/javase/8/docs/technotes/tools/windows/classpath.html#A1100762
Expanded lists of all jars are becoming too long.

It could be also considered for -sourcepath.

Discussion: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/j2objc-discuss/Qq7vHN0VaUM/t8wWa7NjAAAJ

**Comment by antonio-cortes-perez** [comment]
Thanks for submitting the issue, I'll take a look.

**Comment by tomball** [comment]
FYI, j2objc supports '@' files, which are files containing a list of
arguments. This helps in two ways: first, it allows teams to avoid command
lines that are longer than the shell allows, as you mentioned. The second
is that it makes all arguments intentional, and not dependent upon whatever
jars happen to match a wildcard. These @ files are frequently included in a
project, where they both support the build and serve as documentation for
what its dependencies are.

I agree with this issue that j2objc should work like javac, but would never
recommend using wildcards in a build's classpath as it can introduce
perplexing errors when different developers have different sets of matching
jars.

**Comment by antonio-cortes-perez** [comment]
Fixed in latest source.

**Comment by blazek** [comment]
> FYI, j2objc supports '@' files, which are files containing a list of arguments.

Thank you, I was not aware of @files support, it works well for me.
