### ISSUE TITLE
No such file: —no-package-directories

### ISSUE THREAD

**Issue by songyuyang0918** [google/j2objc#1158]
JDK1.8 is installed through the "brew cask install AdoptOpenJDK/openjdk/adoptopenjdk8" terminal instruction, and no such file: - no package directories error occurs when compiling the project again.

I changed the "sourcepath" to: "${PROJECT_DIR}/src"

My profile:
<img width="644" alt="屏幕快照 2019-11-21 下午6 23 35" src="https://user-images.githubusercontent.com/15685672/69329435-0e1da500-0c8c-11ea-9195-9508a00b0e61.png">

My project structure:
<img width="317" alt="屏幕快照 2019-11-21 下午6 24 13" src="https://user-images.githubusercontent.com/15685672/69329478-2ab9dd00-0c8c-11ea-8461-544dca76589d.png">
The folder SRC contains java code.

I want to know if there's something wrong with my understanding. I'm at a loss about this mistake

**Comment by tomball** [comment]
In [Xcode Build Rules/Adding a J2ObjC Build Rule](https://developers.google.com/j2objc/guides/xcode-build-rules#adding_a_j2objc_build_rule), it says, "(remember to substitute $source-root)", which you apparently didn't do. Since "$source-root" is not defined by Xcode (which is why we chose that name), the shell substituted an empty string, causing the command to have "... -sourcepath --no-package-directories ...". Replacing "$source_root" with "${PROJECT_DIR}/src" as you did fixed the problem, because that was what the doc said to do.

Can you suggest a clearer description for our documentation? Perhaps we should change the name to "PROJECT_SOURCE_PATH" without the $, so that if the developer doesn't replace it then the error will be "No such file: PROJECT_SOURCE_PATH". I'm not sure that will help, though, as lots of new developers have never worked with a shell and so this error may also be confusing.
