### ISSUE TITLE
What is the reason for not providing common engineering libraries for Android and iOS projects?

### ISSUE THREAD

**Issue by superLiuYiPeng** [google/j2objc#1221]
I think j2objc is a sharing module of data logic and business logic used in Android and IOS applications, but j2objc only has few libraries built in, such as guava and JUnit. Why not provide common libraries, such as okhttp, SQLite3, and other shared libraries of network and database, and there are no examples

**Comment by tomball** [comment]
J2ObjC is a Java compiler and runtime for iOS, not a general mobile platform or a "sharing module". Google is used by its biggest iOS apps, like Gmail and Docs, and isn't very useful for apps that are not designed to be cross-platform and have a substantial amount of client code that's shared. These apps also use [J2CL](https://github.com/google/j2cl) to compile that shared code for their web clients.

You'll want to find a different platform that better meets your needs, like [Flutter](https://flutter.dev/) or [Xamarin](https://dotnet.microsoft.com/apps/xamarin).

Closed because issues are normally used for bug reports.

**Comment by superLiuYiPeng** [comment]
think for you
