### ISSUE TITLE
Guava framework + file not found

### ISSUE THREAD

**Issue by mobilemindtec** [google/j2objc#1227]
Hi,

I am having several problems publishing my application. Running it in debug mode the compilation works perfectly, but when I run the archive xcode option, problems start. I've been trying several solutions for several weeks, but I always stop at a new problem. The new problem is:

```
Lexical or Preprocessor Issue Group
/Volumes/Data/sources/j2objc/pay4gym/share/ios/AppShare/Classes/AgendaController.m:33:10: 'com/google/common/collect/ImmutableMap.h' file not found
``` 

Project configuration:

```
Other linker flags: $(inherited) -l"jre_emul" -l"iconv" -l"guava" -l"javax_inject" -l"jsr305" -l"iconv" -ObjC

Framework Search Paths: $PODS_CONFIGURATION_BUILD_DIR/** ${J2OBJC_HOME}/frameworks

Library Search Paths: ${J2OBJC_HOME}/lib

User Header Search Path: $J2OBJC_HOME/include
```

Would anyone know the solution?

Thanks!

**Comment by tomball** [comment]
Guava headers are not directly referenced from `${J2OBJC_HOME}/include/` because there are actually [two versions of Guava](https://github.com/google/guava): `guava-jre` (for Java apps and servers) and `guava-android` (for Android apps). J2ObjC distributes both.

So the short answer is to explicitly add the Guava framework to your project (right-click on your project's Frameworks section, select Add Files to ..., then add the `Guava.framework` directory from your J2OBJC_HOME's frameworks directory (or `GuavaAndroid.framework`). Since the headers and library are in each framework, things should then "just work":

```
$ find ~/j2objc-2.5/frameworks -name ImmutableMap.h
/Users/tball/j2objc-2.5/frameworks/Guava.framework/Versions/A/Headers/com/google/common/collect/ImmutableMap.h
/Users/tball/j2objc-2.5/frameworks/GuavaAndroid.framework/Versions/A/Headers/com/google/common/collect/ImmutableMap.h
```
However, if you don't want your project to depend upon Guava as a framework, then an additional header search path is needed:
```
$ ls -ld ~/j2objc-2.5/include/guava*
drwxr-xr-x@ 4 tball  primarygroup  128 Jul 15  2019 /Users/tball/j2objc-2.5/include/guava
drwxr-xr-x@ 4 tball  primarygroup  128 Jul 15  2019 /Users/tball/j2objc-2.5/include/guava_android
```
So either add (not replace) `${J2OBJC_HOME}/include/guava` for the JRE version of Guava, or `${J2OBJC_HOME}/include/guava_android` for the Android version.

There are also library names now: continue specifying `-lguava` for the JRE library, or use `-lguavaandroid` for the Android version.

**Comment by mobilemindtec** [comment]
Hi,

Thanks for the answer, solve the problem!
