### ISSUE TITLE
how to add j2objc to flutter plugin as dependency?

### ISSUE THREAD

**Issue by jiangyubao** [google/j2objc#1253]
Hi, every body. I am a Java Programmer, and now I need to move some java code to my flutter project.

There is no tools to translate java code to dart code, so I use flutter's plugin to satisfy this need.
The java code can easy translate to Android code, no need to change anything.
Then I use j2objc command line tool to translate java code to objc code, and every is OK.
But I don't know how add these objc code as dependency to flutter plugin. I try the flowing code:
`  s.ios.vendored_frameworks = 'frameworks/JRE.xcframework'
  s.vendored_frameworks = 'JRE.xcframework'`

but it's not OK.

Do you know how? And anybody can show me an flutter plugin example?

**Comment by tomball** [comment]
You need to ask a Flutter support group how iOS frameworks are added to a Flutter project.

One possible issue is that Flutter may not yet support XCFramework frameworks, since that format was introduced in Xcode 11. If Flutter does not, then try the old-style frameworks distributed in [j2objc-2.5](https://github.com/google/j2objc/releases/tag/2.5).

**Comment by jiangyubao** [comment]
thank you



发自我的iPhone


------------------ Original ------------------
