### ISSUE TITLE
Events not recorded by WatchService

### ISSUE THREAD

**Issue by albertomisail** [google/j2objc#1440]
This is the reason why MacOSXPathTest.test_register$WatchService$WatchEvent_Kind is in an infinite while loop

**Comment by tomball** [comment]
It looks like Java doesn't have a useful watch service on MacOS yet. [Although this question](https://stackoverflow.com/questions/9588737/is-java-7-watchservice-slow-for-anyone-else) has "Java 7" in its title, the comments state that it's still not working correctly as of Java 13.

**Comment by albertomisail** [comment]
Indeed BsdFileSystem (superclass of MacOSXFileSystem) has the following ```@Override
    public WatchService newWatchService()
        throws IOException
    {
        // use polling implementation until we implement a BSD/kqueue one
        return new PollingWatchService();
    }```

**Comment by tomball** [comment]
According to the [FileSystem javadoc](https://docs.oracle.com/javase/8/docs/api/java/nio/file/FileSystem.html), FileSystem.newWatchService() should throw an UnsupportedOperationException if the filesystem doesn't support a watch service. Since it's not working for us and barely working for MacOS Java developers, we should probably remove the implementation support for it. Your thoughts?

**Comment by albertomisail** [comment]
SGTM

**Comment by tomball** [comment]
Closing issue since this works on iOS.
