### ISSUE TITLE
package org.json no longer automatically included into the classpath

### ISSUE THREAD

**Issue by JustinGanzer** [google/j2objc#1508]
With the release of version 2.7, android's "org.json" package is no longer picked up automatically by j2objc as a -classpath for the java compiler. The package is now inside it's own json.jar file (still inside the lib folder however) and previously was part of the jre_emul.jar. My guess is that this is due to updates to Xcode or Java as compiling the sources of 2.6 and older now also creates a separate json.jar and libjson.a file instead.

It was my understanding that everything from within the "lib" folder was passed to j2objc automatically? If not or this is indeed the intended behaviour please disregard the issue but perhaps we could add the "-l json" flag to the documentation at https://developers.google.com/j2objc/guides/required-link-flags.

**Comment by tomball** [comment]
Thanks for notifying us that this page needs updating. Moving the `org.json` fixed the issue where developers want to use a different implementation of the `org.json` API (there are [several](https://www.json.org/json-en.html)) instead of Android's version.

In j2objc's lib directory, only the `jre_core` library is linked in by default by the j2objcc script, and all other libraries in `lib` are optional. The documented required libraries are needed by `jre_core`. This is also intentional, since most developers prefer linking their apps with the (default) `-ObjC` flag, which adds all Objective-C classes in all static libraries to the app, whether they're used or not. Adding unused static libraries to an app's build with that flag just increases its download and memory size without adding any benefit.

**Comment by tomball** [comment]
Added JSON library https://developers.google.com/j2objc/guides/required-link-flags list.

**Comment by kluverua** [comment]
Perhaps you can help me, I also have a problem with "org.json"
I have updated j2objc library to version 2.7 (Downloaded and unpacked archives **j2objc-2.7-frameworks.zip** and **j2objc-2.7.zip**)

After update, the project stopped building, an error appeared:
`error: ... / FilterableQuery.java:3: package org.json does not exist`

As I understand it, I need to add the "json" option in build options.
(Because this library was excluded by default now)

In XCODE, in the project properties **Other Linker Flags**, I added the **-ljson** flag

now it look like this:
```
OTHER_LDFLAGS = (
"$ (inherited)",
"-ObjC",
"-liconv",
"-ljre_emul",
"-ljson",
);
```

But it did not help.
The error `package org.json does not exist` remains

What else needed to be done?

**Comment by tomball** [comment]
You are right to add the "-ljson" flag so your app *links* again, but since
this is a Java error, j2objc-2.7/lib/json.jar needs to be added to
j2objc's -classpath argument.

The quick trick to setting -sourcepath and -classpath arguments is to first
try compiling your Java sources using javac, as the same paths are used by
j2objc, and then switch to j2objc:

$ j2objc JsonTest.java
JsonTest.java:1: error: package org.json does not exist
import org.json.*;
^
...
3 errors$ javac JsonTest.java
JsonTest.java:1: error: package org.json does not exist
import org.json.*;
^
...
3 errors
$ javac -classpath ~/j2objc-2.7/lib/json.jar JsonTest.java
$ j2objc -classpath ~/j2objc-2.7/lib/json.jar JsonTest.java

Why does this help? Java developers know how to fix compiler errors, and so
quickly apply those skills when javac has errors. With j2objc, they assume
it's something different that they don't already know. However, j2objc uses
javac as it's front-end, which is why it shares so many core flags with
javac -- it just passes them on to javac unaltered (that's why the errors
are identical).

**Comment by tomball** [comment]
You are right to add the `-ljson` flag so your app **links** again, but since
this is a Java error, `j2objc-2.7/lib/json.jar` needs to be added to
j2objc's `-classpath` argument.

The quick trick to setting `-sourcepath` and `-classpath` arguments is to first
try compiling your Java sources using javac, as the same paths are used by
j2objc, and then switch to j2objc:
```
$ j2objc JsonTest.java
JsonTest.java:1: error: package org.json does not exist
import org.json.*;
^
...
3 errors$ javac JsonTest.java
JsonTest.java:1: error: package org.json does not exist
import org.json.*;
^
...
3 errors
$ javac -classpath ~/j2objc-2.7/lib/json.jar JsonTest.java
$ j2objc -classpath ~/j2objc-2.7/lib/json.jar JsonTest.java
```
Why does this help? Java developers know how to fix compiler errors, and so
quickly apply those skills when javac has errors. With j2objc, they assume
it's something different that they don't already know. However, j2objc uses
javac as it's front-end, which is why it shares so many core flags with
javac -- it just passes them on to javac unaltered (that's why the errors
are identical).

**Comment by xurei** [comment]
@tomball I spent two hours searching for this information. I believe there should be a statement in the doc about this.

**Comment by tomball** [comment]
Sounds good, where would you put it? Few, if any, developers read everything on our site, so it needs to go somewhere they're likely to look.

**Comment by mzufry** [comment]
Hi @tomball,
I am trying to update j2objc from 2.6 to 2.8. The same error occurred in build,
package org.json does not exist

In XCODE, in the Build Settings Other Linker Flags, I added the -ljson flag also, but the error remains.

I tried many hours to set j2objc's -classpath argument. but I couldn't. Can you help me on that?
