### ISSUE TITLE
system:macOS Big Sur. Xcode:12.2

### ISSUE THREAD

**Issue by zhaohuang2016** [google/j2objc#1513]
error: ../../j2objc-2.3.1/j2objc: line 88: /Library/Internet: No such file or directory

**Comment by vvaleed** [comment]
Hi 
I was facing the same problem. I got it resolved by setting the $JAVA_HOME variable

JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home
export JAVA_HOME;

For some reason the JAVA_HOME is not being set. I had to put this in build rules before j2objc starts

**Comment by tomball** [comment]
The j2objc script does not set `JAVA_HOME`. It uses the `/usr/libexec/java_home`command-line tool (installed on all Macs), and otherwise uses whatever the developer has defined in `JAVA_HOME`. Here is a discussion on [how to set `JAVA_HOME` on a Mac](https://stackoverflow.com/questions/22842743/how-to-set-java-home-environment-variable-on-mac-os-x-10-9).

I think the issue here is that some developers are using a different Java distribution from what Oracle or OpenJDK provides, and that distribution doesn't install itself in a way that `/usr/libexec/java_home`can find. Many Java tools require a valid `JAVA_HOME` environment variable, and if the system can't find an installed distribution, it is the responsibility of the developer to set it like @vvaleed did.

**Comment by zhaohuang2016** [comment]
thank you very much

**Comment by stevekellogg** [comment]
This is a stupid question (I'm assuming), but a NEWER version of Java won't work, correct?  I had installed "jdk-15.0.1.jdk" and setting JAVA_HOME didn't seem to help.

TIA

Steve

**Comment by tomball** [comment]
We currently support up through Java 11, as Google hasn't deployed Java 15
yet internally. If you can't wait, a Java 15 update should be
straightforward, by following these commits:

   - Scripts and make support:
   https://github.com/google/j2objc/commit/8e35b4c9ee0baab679b1d65ea4db1ee1f6be0113
   - Translator support:
   https://github.com/google/j2objc/commit/daf28c8dd8e7a33a1978e2c49a540fc02b18d1f5
   ,
   https://github.com/google/j2objc/commit/9a5ff0691888a905b911357c04e8d28be2006a5e
