### ISSUE TITLE
Adding aarch64 support for macOS Big Sur

### ISSUE THREAD

**Issue by dsanghan** [google/j2objc#1516]
Does J2Objc need to add the new arm64 architecture for macOS to its makefiles?

Currently the common makefile only contains: 
`macosx iphone64 iphone64e watchv7k watch64 watchsimulator simulator64 maccatalyst`

**Comment by tomball** [comment]
Yes, we’ll eventually do it, but can’t until Big Sur is released internally
for our Google-managed systems (since security is so critical, we don’t
know when the reviews will be complete).

If you need it sooner, it’s easier to add new architectures now that we
support XCFrameworks. Open that makefile on the GitHub site, then click the
Blame button to see which commit last modified that arch list. Open that
commit to see the list of files changed, and how. Make similar updates for
this new arch, verify it works for you, then submit a pull request. That
way, you get the update that you need when you need it, and become a
publicly listed contributor!

**Comment by dsanghan** [comment]
@tomball Added https://github.com/google/j2objc/pull/1517
