### ISSUE TITLE
zsh: exec format error: j2objc

### ISSUE THREAD

**Issue by nafis042** [google/j2objc#1534]
When I try to run the command j2objc Hello.java I'm getting the following error: 
`zsh: exec format error: j2objc`

here is my java --version output:
`openjdk 11.0.9.1 2020-11-04`
`OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)`
`OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)`

what am I misssing here?

**Comment by tomball** [comment]
This works for me using zsh with OpenJDK 11. Since the "exec" in this error message is short for "executable", check the following:

1. Is the j2objc script executable? Run `ls -l ~/j2objc-2.7/j2objc` (or whatever the path is to your copy of the j2objc script) and you should see something like `-rwxr-xr-x`, with the x's showing it is executable. If there aren't x's, then delete your j2objc distribution and unzip [the latest version](https://github.com/google/j2objc/releases/latest).
2. Is Java configured on your system correctly? Run `which java` to see what binary zsh executes, then run `echo $JAVA_HOME` and verify it points to the same JDK path from where java executes.
3. If you don't have `JAVA_HOME` set in your environment, run `/usr/libexec/java_home -v 1.8`. That command searches for the latest version of Java 1.8 installed on your Mac, and is what the j2objc script calls if JAVA_HOME isn't set. Verify the path returned by java_home can run with the `-version` flag.

**Comment by IbrahimAfaq1** [comment]
I am Downloading TLauncher for Minecraft in Kali Linux but I am having that error:
zsh: exec format error: ./TLauncher-2.895.jar
Can someone please help me with this error.

**Comment by tomball** [comment]
"TLauncher-2.895.jar" has nothing to do with j2objc, so we can't help you. Since it's a Java jar file, you might want to search for an answer on StackOverflow.com.

**Comment by IbrahimAfaq1** [comment]
OK thanks
