### ISSUE TITLE
Rename Java variable names that conflict with ObjC reserved words

### ISSUE THREAD

**Issue by taylesworth** [google/j2objc#1549]
We're translating an existing Java project that unfortunately has many uses of `typeof` as a Java variable name. It's easy enough for us to rename these but not as easy to prevent regressions in new code, since the pattern has been so widely used before.

Would it be reasonable to add a check for reserved words [here](https://github.com/appian/j2objc/blob/master/translator/src/main/java/com/google/devtools/j2objc/translate/VariableRenamer.java#L121) and append an "_" if a variable name is found in an array of reserved words?

Want to check before going down this path to see if it's something you have considered in the past and whether there are any gotchas I should be aware of.

**Comment by tomball** [comment]
We already do a reserved words check as you describe, so all that's necessary is to add `typeof` to [j2objc's reserved words list](https://github.com/google/j2objc/blob/master/translator/src/main/resources/com/google/devtools/j2objc/reserved_names.txt) and rebuild the translator. Since the [clang language extensions doc](https://clang.llvm.org/docs/UsersManual.html#differences-between-various-standard-modes) describes this and other standard mode-specific keywords, I'll add a new standard-mode section with all the current ones.

In the meantime, that clang doc suggests that you can avoid this by changing your Xcode project's C Language Dialect to any non-GNU standard, such as C11. If you need a GNU standard, another option is to add the keyword to reserved_names.txt and rebuild the translator.

**Comment by tomball** [comment]
It turns out only `typeof` is missing, so a fix should be pushed out later today.

**Comment by taylesworth** [comment]
That's fantastic. Thank you so much!
