### ISSUE TITLE
Rewording suggestion for the "Required Link Settings" documentation page

### ISSUE THREAD

**Issue by adil-hussain-84** [google/j2objc#1563]
The description associated to the `libjre_concurrent.a` library in the [Required Link Settings](https://developers.google.com/j2objc/guides/required-link-flags) documentation page seems to imply that this library contains _all_ of the classes in the `java.util.concurrent`, `java.util.concurrent.atomic` and `java.util.concurrent.locks` packages. This is not the case. Some of the classes belonging to the `java.util.concurrent` package are in the `libjre_core.a` library. I think this description should be reworded slightly so it's clear that this library contains a subset of the classes in the aforementioned packages. Perhaps the wording should be like it is in the description associated to the `libjre_io.a` and `libjre_util.a` libraries.

**Comment by tomball** [comment]
Right, jre_core has a lot of classes from other libraries because they are part of its dependency closure. The JRE wasn't designed to be split into pieces (which is why the Java 9+ java.base module is so big). I'll update the descriptions, but for practical it shouldn't matter since the way to use subsets is to start with jre_core, then add whatever subsets resolve missing JRE symbols when the app is linked. The subset names are really just clues to where those missing symbols might be resolved.

I'll also add links to to the library sources lists in [jre_sources.mk](https://github.com/google/j2objc/blob/master/jre_emul/jre_sources.mk), which should help reduce confusion.

FYI, building without the `-ObjC` linker flag avoids the need for subsets, as only those classes that resolve dependencies will be included. That requires that classes only loaded by reflection to be specifically referenced, though ([example](https://github.com/google/j2objc/blob/master/jre_emul/Classes/com/google/j2objc/security/IosSecurityProvider.java#L125)).

**Comment by adil-hussain-84** [comment]
Thanks for the information about the `-ObjC` linker flag. That's good to know. I just went back to the [-ObjC Link Flag](https://developers.google.com/j2objc/guides/required-link-flags#the_-objc_link_flag) section in the [Required Link Settings](https://developers.google.com/j2objc/guides/required-link-flags) page and it is mentioned there. I just didn't pick up on it.

**Comment by tomball** [comment]
Fixed, thanks for the feedback. Updated section is at https://developers.devsite.corp.google.com/j2objc/guides/required-link-flags#jre_libraries
