### ISSUE TITLE
Build from source fails with 'binaries with multiple platforms are not supported' error

### ISSUE THREAD

**Issue by benlacey** [google/j2objc#1634]
I'm taking over responsibility for an app that uses J2ObjC, and have been looking at getting the tests working on our M1 Mac build agent, as well as updating from the current 2.2 version it uses - following the suggestion here (https://groups.google.com/g/j2objc-discuss/c/dchLTimVqxY/m/rql6UatcBgAJ) I'm attempting to build from source, but the build fails with the following error when building on my Intel Mac:

>xcodebuild -create-xcframework -output ../dist/frameworks/JRE.xcframework -library /Users/benlacey/git/external/j2objc/jre_emul/build_result/appletvos/libjre_emul.a -library /Users/benlacey/git/external/j2objc/jre_emul/build_result/iphone/libjre_emul.a -library /Users/benlacey/git/external/j2objc/jre_emul/build_result/maccatalyst/libjre_emul.a -library /Users/benlacey/git/external/j2objc/jre_emul/build_result/macosx/libjre_emul.a -library /Users/benlacey/git/external/j2objc/jre_emul/build_result/simulator/libjre_emul.a -library /Users/benlacey/git/external/j2objc/jre_emul/build_result/watchos/libjre_emul.a
>error: binaries with multiple platforms are not supported '/Users/benlacey/git/external/j2objc/jre_emul/build_result/appletvos/libjre_emul.a'
>make[1]: *** [../dist/frameworks/JRE.xcframework] Error 70
>make: *** [frameworks] Error 2

Building using `./scripts/build_distribution.sh 2.8 /usr/local` and `make all_dist` both end up at the same error.

Inspecting the file it complains about shows it contains two archs - I'm not familiar enough to know if this is expected, or if it's a failure somewhere in my installed toolchain.

>BW101491:j2objc benlacey$ lipo -i /Users/benlacey/git/external/j2objc/jre_emul/build_result/appletvos/libjre_emul.a
>Architectures in the fat file: /Users/benlacey/git/external/j2objc/jre_emul/build_result/appletvos/libjre_emul.a are: x86_64 arm64 

I've tried on two separate (both Intel) machines and get the same issue.  I've also tried the current HEAD (9ddf8ab9b) and one from the recent past (9d7a85aec) from around the time of the Groups post linked above, with the same results.

Any thoughts on whether there's something wrong with my setup or suggestions for how to fix?

Environment details:

>Xcode 12.4 (12D4e)
>/usr/libexec/java_home -v 1.8 => /usr/local/Cellar/openjdk@8/1.8.0+282/libexec/openjdk.jdk/Contents/Home
>/usr/local/bin/protoc --version => libprotoc 3.15.6

**Comment by tomball** [comment]
First, does your build use Frameworks or static libraries? If it only uses static libraries, then run `make dist` instead of `make frameworks`.

Next, does your app need to work with AppleTV (most don't). If not, explicitly set [J2OBJC_ARCHS](https://github.com/google/j2objc/blob/master/make/common.mk#L87) to only include the archs your app will actually use (this has the extra advantage of reducing your build time). The same goes for Watch OS and Mac Catalyst -- if your app won't run on a watch or as an iOS app on Mac, then skip building for those platforms.

Since you're new to Apple architectures, here's what we support:
```
# Original list:
  # iOS
  iphone64 iphone64e simulator64
  # macOS
  macosx macosx64
  # watchOS
  watchv7k watch64 watchsimulator 
  # AppleTV
  appletvos appletvsimulator
  # Mac Catalyst (iOS on Mac)
  maccatalyst

For example, here's how to build with just iOS:
```
$ export iphone64 iphone64e simulator64
$ make -j8 frameworks
```

**Comment by benlacey** [comment]
Thanks Tom, that's given me some avenues to go down.

We're using frameworks and only need to run on iOS devices and simulator, so I'm currently looking to add arm64 simulator support in a similar way to https://github.com/google/j2objc/commit/91eeab36a41a8f77152f98a3d85377d2aec3cb12 added `macos64` support - although it might take a while to get results!

**Comment by tomball** [comment]
For the (j2objc-2.8 release](https://github.com/google/j2objc/releases/tag/2.8) we fixed xcframework builds by only using single-arch static libraries in each slice. This should fix this issue, but if you still have issues, feel free to reopen with the specific failures.

**Comment by himamis** [comment]
@tomball Is this fix committed to the repository? Where can I find this part of using only single-arch static libraries?

**Comment by tomball** [comment]
Yes, in [3a70244](https://github.com/google/j2objc/commit/3a702441917ab787460f6aeff14bfa5a99f49dde). It's not obvious, but the `$(BUILD_DIR)/[aimsw]*/lib$(STATIC_LIBRARY_NAME).a` are per-platform fat libraries (the ones copied to a distribution's `lib` directory), while the `$(BUILD_DIR)/objs-*/lib$(STATIC_LIBRARY_NAME).a` library are single-architecture slices. When I had Xcode build an xcframework all of the libraries were single-slice, so this change seemed correct (it's hard to tell since xcframework documentation is pretty weak).

**Comment by himamis** [comment]
Thanks, yes you're right the, command is called with separate slices.
