### ISSUE TITLE
Cannot find symbol

### ISSUE THREAD

**Issue by amir-ardalanuk** [google/j2objc#1658]
Hi 
Thank you for helping me to pass this issue
I'm trying to convert an encryption lib to the swift library 
at first, get an error from cannot find symbol but the file exist in the directory but when I moved the file into another directory and import it the issue gone, this problem is happening for most of the file 
What is my project problem to get this issue and how can fix it? 
<img width="798" alt="Screen Shot 2021-04-26 at 14 32 23" src="https://user-images.githubusercontent.com/12419118/116079748-6f317f80-a6ad-11eb-8d2c-6c7e6e4382c7.png">
![Screen Shot 2021-04-26 at 15 13 19](https://user-images.githubusercontent.com/12419118/116079752-722c7000-a6ad-11eb-8bc0-c9dade7c39ed.png)
![Screen Shot 2021-04-26 at 15 14 20](https://user-images.githubusercontent.com/12419118/116079756-72c50680-a6ad-11eb-83e2-37ce0847c8d5.png)
![Screen Shot 2021-04-26 at 16 38 59](https://user-images.githubusercontent.com/12419118/116080172-f848b680-a6ad-11eb-8d5f-ac8e9ed26940.png)

**Comment by tomball** [comment]
The underlying problem is that Xcode doesn't support/won't respect relative source paths, which Java requires. For example, org.bouncycastle.util.Store should be in a file with a relative path of "org/bouncycastle/util/Store.java", and even though that's how it shows in your screenshot, Xcode really sees it as just "Store.java". So we added a `--no-package-directories` hack to generate sources without relative paths. It works for very simple Java libraries, but since Java really expects packages to be supported, this support is fragile and frequently not sufficient for large libraries. Unfortunately, Xcode closed its plug-in API years ago, so there's no way an independent project like ours can fix it.

So what to do? Since I doubt you're a BouncyCastle contributor (few developers are), building a BouncyCastle framework outside of Xcode and just referencing it in your project is both easier than wrestling with Xcode, and faster building since the framework is only built once with each version update. 

I suggest downloading and building the [j2objc repository](https://developers.google.com/j2objc/guides/building-j2objc), then copying its `j2objc/jsr305` project (since it's the simplest) to a j2objc/bouncycastle directory and then editing the project. Make may be an archaic build tool for this century, but our project has macros in the `j2objc/make` directory that do the heavy lifting. In its `environment.mk` file, change the definitions for the BouncyCastle source and class jars, then in `Makefile` replace the JAVA_SOURCES definition, then run `make framework`.

**Comment by amir-ardalanuk** [comment]
Thank you for replying
I could not build it outside of the Xcode And I hade to prepare it as soon as possible 
Finally I build and get my .h and .m file from j2objc
and everything works till I added to the another framwrok to use my Implimented file 
 I've gotten some errors such as 
 `"_new_OrgBouncycastleCryptoGeneratorsEd448KeyPairGenerator_init", referenced from:
      static bouncyCastle.Ed448Impl.generatePrivateKey() throws -> Swift.String in libbouncyCastle.a(Ed448Impl.o)
  "_new_OrgBouncycastleCryptoParamsEd448KeyGenerationParameters_initWithJavaSecuritySecureRandom_", referenced from:
      static bouncyCastle.Ed448Impl.generatePrivateKey() throws -> Swift.String in libbouncyCastle.a(Ed448Impl.o)
ld: symbol(s) not found for architecture arm64`

**Comment by tomball** [comment]
If your comment "I hade to prepare it as soon as possible" means you are under a lot of time pressure and are rushing to finish this, STOP. It is a really, really, REALLY bad idea to rush new crypto code into an app, as mistakes in crypto often become security weaknesses that can be exploited by bad actors.

I just built BouncyCastle's core (where Ed448KeyPairGenerator.java and Ed448KeyGenerationParameters.java live), using the following steps in a command-line window:
```
$ git clone https://github.com/bcgit/bc-java.git
$ cd bc-java/
$ j2objc -d objc_build -sourcepath core/src/main/java `find core/src/main/java -name '*.java'`
$ cd objc_build
$ j2objcc -c -I. -Wno-integer-overflow `find org -name '*.m'` -arch arm64 \
-isysroot /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk
```
To find a missing symbol, search for it without the beginning underscore. So, looking for your missing symbols finds:
```
$ grep -r new_OrgBouncycastleCryptoGeneratorsEd448KeyPairGenerator_init objc_build
objc_build/org/bouncycastle/crypto/generators/Ed448KeyPairGenerator.m:OrgBouncycastleCryptoGeneratorsEd448KeyPairGenerator *new_OrgBouncycastleCryptoGeneratorsEd448KeyPairGenerator_init() {
objc_build/org/bouncycastle/crypto/generators/Ed448KeyPairGenerator.h:FOUNDATION_EXPORT OrgBouncycastleCryptoGeneratorsEd448KeyPairGenerator *new_OrgBouncycastleCryptoGeneratorsEd448KeyPairGenerator_init(void) NS_RETURNS_RETAINED;
```
```
$ grep -r new_OrgBouncycastleCryptoParamsEd448KeyGenerationParameters_initWithJavaSecuritySecureRandom objc_build
objc_build/org/bouncycastle/crypto/params/Ed448KeyGenerationParameters.h:FOUNDATION_EXPORT OrgBouncycastleCryptoParamsEd448KeyGenerationParameters *new_OrgBouncycastleCryptoParamsEd448KeyGenerationParameters_initWithJavaSecuritySecureRandom_(JavaSecuritySecureRandom *random) NS_RETURNS_RETAINED;
objc_build/org/bouncycastle/crypto/params/Ed448KeyGenerationParameters.m:OrgBouncycastleCryptoParamsEd448KeyGenerationParameters *new_OrgBouncycastleCryptoParamsEd448KeyGenerationParameters_initWithJavaSecuritySecureRandom_(JavaSecuritySecureRandom *random) {
```
So that tells us that Ed448KeyPairGenerator.m and Ed448KeyGenerationParameters.m need to be included in your project, along with their .h headers.

However, once you add those files, new dependencies are likely to be needed. So it's best to include all the generated sources, as we know all the library's dependencies were found since the `j2objcc` command succeeded.
