### ISSUE TITLE
*** Terminating app due to uncaught exception 'SecurityException', reason: 'SecurityException: No provider found for AES/ECB/NoPadding'

### ISSUE THREAD

**Issue by ManjunathShiv** [google/j2objc#1659]
When I am trying to integrate Java to ObjC converted code. I am getting a security Exception. Can you please let me know on how to deal with security related exception.

**Comment by tomball** [comment]
"No provider found" means a platform doesn't support the requested security or crypto algorithm. J2ObjC has a very limited security provider implementation, especially not crypto due to export restrictions. You have two options:

1. Use a native Objective C library. Apple provides the Security Framework, and there open-source libraries like RNCryptor ([here's a tutorial](https://code.tutsplus.com/tutorials/securing-and-encrypting-data-on-ios--mobile-21263)). [AESCrypt-ObjC](https://github.com/Gurpartap/AESCrypt-ObjC) is also supposed to be simple to use.

2. Use the [Bouncy Castle Java library](https://www.bouncycastle.org/). It transpiles without problem and doesn't have any dependent libraries.
