### ISSUE TITLE
J2ObjC MAC Algorithm support

### ISSUE THREAD

**Issue by Vedranivic** [google/j2objc#1694]
Hi, I have a question regarding j2objc's (jre_emul) support for translating java.security providers, services and algorithms, more specifically the support of the **MAC** (Message Authentication Code) algorithm (HMac256 to be precise). In the [documentation](https://developers.google.cn/j2objc/javadoc/jre/reference/javax/crypto/Mac?hl=vi), as well as the generated _Mac.h_ header file, it is stated that during the instancing of the MAC algorithm, all the available providers (retrieved by _Security.getProviders()_) are iterated to find the one that supports the MAC algorithm.
When using Objective-C classes translated by j2objc, the listed providers are only **J2ObjCSecurity** and **CertPathProvider**, and neither has support for the mentioned MAC services (algorithms). I can see in the wrapper code [implementation](https://github.com/google/j2objc/blob/master/jre_emul/Classes/com/google/j2objc/security/IosSecurityProvider.java) of the J2ObjCSecurity provider that, unlike MessageDigest, Signatures, KeyFactory etc. the MAC services are not even listed and no MAC algorithms are added. 

Does the 2.8 j2objc release not have included wrapper implementation support for MAC algorithms? And if so, is it possible to add it somehow manually - to the existing release binaries or by adding additional corresponding java implementation classes to the source code and then building the binaries manually? Thanks :D

**Comment by tomball** [comment]
There isn't support for MAC algorithms, j2objc's IosSecurityProvider lists everything that is included. 

Since java.security and its sub-packages is supported, you can follow the normal Java way of adding an independent security provider (which is what IosSecurityProvider does). For the provider, you can use [Bouncy Castle](https://www.bouncycastle.org/java.html) which j2objc translates without issue (it's just really big).

An easier approach is to add support for this algorithm to IosSecurityProvider and implement it using the new crypto APIs in iOS. Here's a [StackOverflow answer](https://stackoverflow.com/questions/476455/is-there-a-library-for-iphone-to-work-with-hmac-sha-1-encoding#answer-635004) that shows an implementation. If you [contribute a pull request](https://developers.google.com/j2objc/guides/how-to-contribute) adding this to the j2objc project, you'll be a hero to future developers. 👍

**Comment by Vedranivic** [comment]
Thank you for the suggestions and explanation. I will try that and keep you posted. 👍

**Comment by tomball** [comment]
[This GitHub Gist](https://gist.github.com/tomball/26cf057bd808add837a82bb790c05e3a) demonstrates accessing CommonCrypto's CCHmac function from Java.
