### ISSUE TITLE
Framework build not work with archs "iphone64 simulator64 iphone simulator"

### ISSUE THREAD

**Issue by sarsonj** [google/j2objc#1713]
The similar bug #1567 was already there, but it looks like it appears again - at least with latest stable xCode (version 12.5). Tested with fresh git pull.

Result is still same: 

`export J2OBJC_ARCHS="iphone64 simulator64 iphone simulator"`
`make -j8 all_dist`

result:
```
building JRE framework
xcodebuild -create-xcframework -output ../dist/frameworks/JRE.xcframework -library /Users/sarsonj/work/git/j2objc/jre_emul/build_result/objs-iphone64/libjre_emul.a -library /Users/sarsonj/work/git/j2objc/jre_emul/build_result/objs-iphone/libjre_emul.a -library /Users/sarsonj/work/git/j2objc/jre_emul/build_result/objs-iphone64/libjre_emul.a
Both ios-armv7 and ios-arm64 represent two equivalent library definitions.
make[1]: *** [../dist/frameworks/JRE.xcframework] Error 70
make: *** [frameworks] Error 2
```

I tried to update framework.mk to ad `iphone` into `FMWK_FAT_LIBS` (according to comment in makefile, there should be there anyway?), but then `gen_xcframework.sh` failed with empty parameters, so that this simple fix didn't helps.

**Comment by L6Echo** [comment]
The issue seems to be how the "fat libs" paths are constructed in framwork.mk:100

```
 94: # As of Xcode 12, xcframeworks need single slice libraries, except for iOS, simulator and Mac platforms
 95: # which require fat libraries.
 96: FMWK_ARCH_LIBS = $(filter-out simulator% macos% maccatalyst%,$(J2OBJC_ARCHS))
 97: FMWK_FAT_LIBS = $(filter simulator% macos% maccatalyst%,$(J2OBJC_ARCHS))
 98: framework_libraries = \
 99:  $(foreach arch,$(FMWK_ARCH_LIBS),$(wildcard $(BUILD_DIR)/objs-$(arch)*/lib$(1).a)) \
100:  $(foreach arch,$(FMWK_FAT_LIBS),$(wildcard $(BUILD_DIR)/$(arch)/lib$(1).a))
```

**General issue on constructing fat libraries:**

The intention of Line 100 is to select the fat library for the device instead of each architecture slice. E.g. for `simulator64` it should select `$(BUILD_DIR)/simulator/libjre_emul.a` instead of `$(BUILD_DIR)/objs-simulator64/libjre_emul.a`.

But with the current code it works only when archs `simulator` and `simulator64` are in `J2OBJC_ARCHS`. 
Because it looks for `$(BUILD_DIR)/simulator/libjre_emul.a` and `$(BUILD_DIR)/simulator64/libjre_emul.a` but skips `$(BUILD_DIR)/simulator64/libjre_emul.a` because it does not exist.

When only arch 'simulator64` is in `J2OBJC_ARCHS` it only looks for `$(BUILD_DIR)/simulator64/libjre_emul.a` but skips it because it does not exist and so any `simulator` lib is added to the xcframework.

**Special case iPhone:**
Currently the the `iphone` architectures works only if a single `iphone` architecture is added to `J2OBJC_ARCHS`. This is because it is added, against the comment in line 94, as single slice instead the fat library. When multiple `iphone` architectures are in `J2OBJC_ARCHS` it will try to add all slices as own lib and xcode complains with `represent two equivalent library definitions`

When the `iphone%` is added in line 97 and 96, then it tries to find `$(BUILD_DIR)/iphone/libjre_emul.a`, `$(BUILD_DIR)/iphone64/libjre_emul.a`, `$(BUILD_DIR)/iphone64e/libjre_emul.a` ...
But none of these folder exists. The folder would have to be `$(BUILD_DIR)/libjre_emul.a` because for the fat iphone library no own subdirectory is used. This causes your observed failure: 
>  but then gen_xcframework.sh failed with empty parameters, so that this simple fix didn't helps.


**Workaround**
There is also a workaround which should obviously reduce the issue `represent two equivalent library definitions` for architecture `iphone64e` and `watchv7k`.

gen_xcframework.sh
```
37:  # Skip libraries that have equivalent library definitions.
38:  if [[ $1 != *"iphone64e"* ]] && [[ $1 != *"watchv7k"* ]]; then
39:    CMD=${CMD}" -library "$1
40:  fi
```

But it only causes, that currently `iphone64e` and `watchv7k` are not added to the xcframework.

**Sugested solution**

1. The fat libraries for `iphone` should be added to a iphone subdirectory like for all other devices
2. The construction of the fat lib paths should be refactored, that it will point to the "device" folder. (e.g. architecture `simulator64` -> `$(BUILD_DIR)/simulator/libjre_emul.a`) and only once for each "device"
3. Workaround should be removed in favor of 1 and 2.
4. Watch should be added to the devices, which requires a fat library



Unfortunately  my skills in makefiles are too bad to provided a PR quickly in a good quality.

**Comment by L6Echo** [comment]
@sarsonj I created PR which addressed this issue. It was merged on the last weekend.
@tomball This issue might be closed

**Comment by tomball** [comment]
Yes, it appears so since I was able to successfully build as @sarsonj described. Thanks for your help!
