### ISSUE TITLE
Missing Arm64 Architecture for iOS Simulator

### ISSUE THREAD

**Issue by L6Echo** [google/j2objc#1737]
For iOS Simulator the Arm64 Architecture is missing. This is required to run iOS Apps in Simulator on Macs with M1 chips.

**Comment by tomball** [comment]
This should have been fixed in [821ff4e](https://github.com/google/j2objc/commit/821ff4ebe99ed79011b31aae73158b3f8b47b072). Since this pull request was merged after the last release, you'll need to [build from source](https://developers.google.com/j2objc/guides/building-j2objc). "Real" developers should normally be doing that anyway, since the releases are really just for people who want to experiment with this project before seriously using it.

**Comment by L6Echo** [comment]
> "Real" developers should normally be doing that anyway, since the releases are really just for people who want to experiment with this project before seriously using it.

Thanks for the clarification. This was not clear to us. I can't find any comments, that these releases are only intended to be used for experimental testing. Also the "Getting Started" section says that this one way to go without limiting it to experimental tests.

> First, either:
> Download the current distribution from the Releases section and unzip it, or
> Get the source and build it.

**Comment by tomball** [comment]
Right, it wasn't intended that way when we started (and wrote those docs).
What happened is that the big app teams kept wanting the latest (often the
moment it was committed), and gradually the only feedback on releases came
from new (to the project) developers.

BTW, I didn't mean my comment as a criticism in any way. Some teams have a
"use only released libraries" policy, which makes sense when they come from
teams with lots of QA and release engineers. Many people assume that j2objc
is an officially supported Google project, but it's just a small,
unofficial part of the Gmail team. Consequently, we early on adopted
test-driven development so that we could ensure high-quality with every
commit. So whenever a release is made, within days the repository HEAD has
a better version.
