### ISSUE TITLE
IOSArray leak memory when beeing copied

### ISSUE THREAD

**Issue by braandl** [google/j2objc#1772]
I simply want to copy an array of doubles and then replace the original with the new ones.
I know this snipped 

```java
    int pointlength = this.doubles.length;
    double[] newDouble = new double[pointlength];
    System.arraycopy(this.doubles, 0, newDouble, 0, pointlength);
    this.doubles = newDouble;
```

to get a copy of the original array is no problem at all.

Transpiled with j2objc this results in

```objective-c
    ....
    JreStrongAssignAndConsume(&self->doubles_, [IOSDoubleArray newArrayWithLength:pointlength]);
    JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(inputDoubles, 0, self->doubles_, 0, pointlength);
```

which leaks the memory of `self->doubles_->buffer` with every copy.

The only workaround I found is altering the produced code using `OCNI` towards

```objective-c
  IOSDoubleArray * newDouble = [IOSDoubleArray newArrayWithLength:pointlength]
  JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(self->doubles_, 0, newDouble, 0, self->doubles_->size_);
  [self->doubles_ release];
  self->doubles_ = newDouble;
```

I hope my example is giving an idea of the problem.
Maybe there is aready a better solution to this? I'd think that the transpiled result should not lead to a memory leak.

**Comment by tomball** [comment]
This isn't a leak, but instead a case of delayed release, where the old array is autoreleased and so it won't be freed until the autoreleasepool it's executing within drains. Here's your code transpiled:

```
- (void)test {
  jint pointlength = ((IOSDoubleArray *) nil_chk(self->doubles_))->size_;
  IOSDoubleArray *newDouble = [IOSDoubleArray arrayWithLength:pointlength];
  JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(self->doubles_, 0, newDouble, 0, pointlength);
  JreStrongAssign(&self->doubles_, newDouble);
}
```

The JreStrongAssign function looks like this:
```
id JreStrongAssign(__strong id *pIvar, id value) {
  return JreAutoreleasedAssign(pIvar, [value retain]);
}

__attribute__((always_inline)) inline id JreAutoreleasedAssign(
    id *pIvar, NS_RELEASES_ARGUMENT id value) {
  [*pIvar autorelease];
  return *pIvar = value;
}
```
which boils down to:
```
id JreStrongAssign(__strong id *pIvar, id value) {
  [value retain];
  [*pIvar autorelease];
  return *pIvar = value;
}
```
If you are seeing a problem with a loop that executes this code many times (such as for vector math), then you may need to  add an [AutoreleasePool annotation](https://developers.google.com/j2objc/javadoc/annotations/reference/com/google/j2objc/annotations/AutoreleasePool) so that memory is released during loop execution. The AutoreleasePool documentation has an example demonstrating how to add the annotation to a for loop variable.

I'll close this now, but if you have a more complete test that demonstrates this issue, please reopen it and attach the test code.

**Comment by braandl** [comment]
Sorry to comment on this again, but the topic is not leaving me alone.
You were very right, that System.arraycopy does not leak memory, but it does also not free it "in time".
Adding an AutoreleasePool annotation totally helps, but I was wandering if there is any reason, not to add it to the System.arraycopy directly. At least in my code, i have this annotation now on very array-copy instruction and every time you write new code, you have to be aware of this, or you will run out of memory. Also I did not see any negative sideeffects by adding the autorelease pool.

In my case, copying thousands of short array items for opengl rendering, it fills up the memory quite quickly, while it is easily avoided with the autorelease pool.

**Comment by tomball** [comment]
Often the best way to fix a performance issue is to use a different algorithm. I prompted [Gemini](https://gemini.google.com/app) about this subject (I asked about Java GC overhead instead of anything j2objc or iOS-specific to ensure a solution that also works on Android):

**Prompt**: When copying thousands of short Java array items for opengl rendering, memory fills up quite quickly, causing frequent GC delays. What Java runtime or data structure alternatives are there to reduce this allocation overhead?

### Gemini:
To reduce memory allocation overhead and avoid GC delays when handling large amounts of data for OpenGL, you should use **direct** `java.nio` **buffers** instead of standard Java arrays.

The core issue with using thousands of small arrays (`float[]`, `int[]`, etc.) is that each array is an object on the Java heap. This creates a lot of work for the Garbage Collector (GC), leading to the performance stutters you're seeing.

Direct buffers solve this by allocating memory outside the Java heap, in a way that can be accessed directly by native code like the OpenGL driver.

### The Solution: ByteBuffer and Direct Buffers

The best alternative is `java.nio.ByteBuffer` allocated as a **direct buffer**. This gives you a single, contiguous block of native memory that is not managed by the GC. You can then create "views" of this buffer for specific data types like floats or integers.

### Key Benefits:

- **Reduced GC Pressure**: Since the data lives outside the Java heap, the GC doesn't need to track and clean it up, virtually eliminating GC-related pauses from your vertex data.
- **Improved Performance**: The JVM can pass the memory address of a direct buffer directly to the native OpenGL function. This avoids the costly step of copying data from a Java array on the heap into a temporary native buffer.

### How to Use Direct Buffers

Here's a typical workflow for creating and populating a direct buffer for vertex data.

1. **Allocate a Direct** `ByteBuffer`: Calculate the total size you need in bytes. For example, for 1000 vertices with 3 float components (X, Y, Z) each: `1000 vertices * 3 floats/vertex * 4 bytes/float`.
2. **Set Native Byte Order**: It's crucial to match the byte order of the underlying hardware for performance.
3. **Create a Typed View**: Use `.asFloatBuffer()` or `.asIntBuffer()` to get a view that lets you work with specific data types.
4. **Put Your Data**: Transfer the data from your Java array into the buffer.
5. **Flip the Buffer**: Prepare the buffer for reading by the native code. The `flip()` method sets the `limit` to the current `position` and resets the `position` to 0.

### Code Example
This example shows how to convert a Java `float[]` into a direct `FloatBuffer` ready for an OpenGL call like `glBufferData`.

```
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.FloatBuffer;

public class BufferExample {

    public static FloatBuffer createDirectFloatBuffer(float[] data) {
        // 1. Allocate a direct ByteBuffer
        // The size is the number of floats multiplied by the size of a float (4 bytes).
        ByteBuffer byteBuffer = ByteBuffer.allocateDirect(data.length * Float.BYTES);

        // 2. Set the byte order to the native order of the hardware
        byteBuffer.order(ByteOrder.nativeOrder());

        // 3. Create a FloatBuffer "view" on top of the ByteBuffer
        FloatBuffer floatBuffer = byteBuffer.asFloatBuffer();

        // 4. Copy the data from the Java array into the buffer
        floatBuffer.put(data);

        // 5. Flip the buffer to prepare it for reading (e.g., by OpenGL)
        // This sets the limit to the current position and position to 0.
        floatBuffer.flip();

        return floatBuffer;
    }

    public static void main(String[] args) {
        // Your vertex data, which might come from many small arrays
        float[] vertexData = new float[] {
            // Vertex 1: Position (X, Y, Z)
            -0.5f, -0.5f, 0.0f,
            // Vertex 2: Position (X, Y, Z)
             0.5f, -0.5f, 0.0f,
            // Vertex 3: Position (X, Y, Z)
             0.0f,  0.5f, 0.0f
        };

        FloatBuffer gpuBuffer = createDirectFloatBuffer(vertexData);

        // Now, gpuBuffer is ready to be passed to an OpenGL function, for example:
        // glBufferData(GL_ARRAY_BUFFER, gpuBuffer, GL_STATIC_DRAW);
        
        System.out.println("Direct FloatBuffer created with capacity: " + gpuBuffer.capacity());
    }
}
```

### Data Organization Tip: Interleaved Data
Instead of managing separate buffers for positions, colors, and texture coordinates, consider interleaving them into a single, large direct buffer. This is often more efficient for the GPU.

For example, your buffer layout for a vertex could be: `[X, Y, Z, R, G, B, U, V]`. You would then use `glVertexAttribPointer` with the appropriate `stride` and `offset` parameters to tell OpenGL how to find each attribute within this single block of memory. This approach simplifies your code by reducing the number of buffers you need to create, manage, and bind.
