### ISSUE TITLE
error: package java.io.ObjectInputFilter does not exist

### ISSUE THREAD

**Issue by ferencIOS** [google/j2objc#1775]
Hi everyone!

I'm trying to build the whole BouncyCastle project.
Now, I am stuck on this error:
```
...src/com/sun/naming/internal/ObjectFactoriesFilter.java:32: error: package java.io.ObjectInputFilter does not exist
import java.io.ObjectInputFilter.FilterInfo;
```

`ObjectInputFilter` is a type not a package
`FilterInfo` is an internal type

How did I get to this point?
First of all started using this script:
```
#!/bin/bash

set -exu

J2OBJC=path/to/j2objc

SOURCE_DIR=path/to/src
OUTPUT_DIR=path/to/ouput
PREFIXES_PROPERTIES=path/to/prefixes.properties

rm -rf ${OUTPUT_DIR} && mkdir -p ${OUTPUT_DIR}

${J2OBJC} -Xlint:none -g -v -d "${OUTPUT_DIR}" \
-sourcepath "${SOURCE_DIR}" \
--prefixes "${PREFIXES_PROPERTIES}" \
--swift-friendly \
--no-segmented-headers \
--no-package-directories \
$(find "${SOURCE_DIR}" -name '*.java')
```

First run:
`error: package javax.naming does not exist`

So I went to check in the documentation if this package was contained in the j2objc-2.8 version and it wasn't.
How could I solve? I thought about importing the missing java source code into the `SOURCE_DIR` one piece at a time.

Here the folders structure:
```
src 
     ---- org
                ---- bouncycastle (...)
     ---- com
                ---- sun
                            ---- jndi (...)
                            ---- naming (...)
     ---- javax
                ---- naming (...)
                ---- security (...)
     ---- jdk
                ---- internal
                                  ---- misc (...)
```

Thanks in advance!

**Comment by tomball** [comment]
The `javax.naming` package is not included because [it's not part of Android](https://developer.android.com/reference/packages), probably because they don't consider it useful on mobile devices (it's mostly used by server-side code). J2ObjC's JRE emulation is a fork of Android's libcore library (it's own JRE), and that also doesn't contain `java.io.ObjectInputFilter`. Finally, no libraries should depend upon `sun.*` or `com.sun.*` API, as they are clearly documented as being internal-use-only.

Regarding BouncyCastle, I strongly recommend that you start with just the `core/` and `jce/` source directories, and see if that meets your project's needs. Unlike Android apps which usually are built with Proguard (or something similar), iOS apps by default are built with all Objective-C classes linked into the app, whether they are used or not. BouncyCastle is a big set of packages, so adding any that aren't needed just bloats your app.

One easy way to keep the bloat of a large library down is to use `j2objc --build-closure`, putting the library's source roots on the `--sourcepath` instead of translating them all. The `--build-closure` flag works like javac does, only translating those sourcepath sources that resolve dependencies from the explicitly listed source files. Since it also resolving dependencies that the pulled-in sourcepath sources have, it builds a "closure" with the minimum sources needed to fully build. It won't find classes loaded by reflection (Class.getClass("name")), though, so those need to be explicitly listed. With that suggestion, your script invocation might look like:
```
export BOUNCYCASTLE_ROOT=<wherever your top-level BC directory  is>
${J2OBJC} -Xlint:none -g -v -d "${OUTPUT_DIR}" \
-sourcepath "${APP_SOURCE_DIR}:$(BOUNCYCASTLE_ROOT)/core:$(BOUNCYCASTLE_ROOT)/jce)" \
--build-closure \
--prefixes "${PREFIXES_PROPERTIES}" \
--swift-friendly \
--no-segmented-headers \
--no-package-directories \
$(find "${APP_SOURCE_DIR}" -name '*.java')
```
