### ISSUE TITLE
Supporting other types of Nullable/Not Nullable annotations

### ISSUE THREAD

**Issue by frangipanes** [google/j2objc#1820]
J2ObjC currently supports jsr305 `@Nullable` and `@Nonnull` annotations. These are useful, but as mentioned in https://github.com/google/guava/issues/2960, it would be ideal to move away from using jsr305 as it is a dormant project.

Is there any chance of supporting other sources of nullable annotations, for example, those from JetBrains, or Guava?

We use our shared Java code both with Objective-C iOS applications and applications written in Kotlin, and the annotations make the Kotlin->Java interface much nicer.

**Comment by tomball** [comment]
Good news, work is in progress. The Guava team is working with the JetBrains team on richer nullability annotating, both to improve error detection and to improve Kotlin importing. They're helping define and are adopting [JSpecify](https://jspecify.dev/) annotations, and [JSpecify's issues list](https://github.com/jspecify/jspecify/issues) details their work and ongoing discussions. Both the JSpecify and Guava teams are making frequent commits as this task is being addressed.

J2ObjC's support for these annotations is limited due to [what Objective-C supports](https://developer.apple.com/documentation/swift/objective-c_and_c_code_customization/designating_nullability_in_objective-c_apis?language=objc), but we're updating the translator as Guava's nullability updates require. All Google apps that use j2objc also use Guava, so translator support will be ongoing as Guava is updated.

I just checked in the jspecify jars to the build. I'm closing this issue not because the work here is finished, but because (IMO) this issue doesn't need to be separately tracked from what's in JSpecify's and Guava's issue lists.

**Comment by frangipanes** [comment]
Thanks Tom! Does this mean we can use the Nullable / NullMarked annotations inside our code (once we grab the latest J2ObjC changes)?
