### ISSUE TITLE
Unable to build without the inclusion of `-Wno-unused-but-set-variable`

### ISSUE THREAD

**Issue by aepryus** [google/j2objc#1872]
machine: Mac mini (M1, 2020)
OS: macOS Monterey v12.3.1
Xcode: v13.3.1

I am currently unable to build without the inclusion of the `-Wno-unused-but-set-variable` warning exclusion.  By adding it to the `CC_WARNINGS` variable in `make/common.mk` it is possible to build.

```
CC_WARNINGS = -Wall -Werror -Wshorten-64-to-32 -Wimplicit-function-declaration \
  -Wmissing-field-initializers -Wduplicate-method-match -Wno-unused-variable \
  -Wno-unused-but-set-variable -Wno-nullability-completeness
```

**Comment by tomball** [comment]
Xcode often adds new warnings to the default set with each release, and in 12.3, that included `-Wunused-but-set-variable`. So your update to CC_WARNINGS is the first workaround, until we come up with a better solution.

One idea we're considering is to not generate the assignment if it's named `unused`. Tests often have lines like `int result = foo.methodUnderTest();` and don't check the result since that's not important for that test case. If lines like that were written as `int unused = foo.methodUnderTest();`, the test writer's intention is more obvious. If j2objc were updated to generate just `[foo methodUnderTest]` because the variable's name is "unused", then this warning can be enabled again. What do you think?

**Comment by aepryus** [comment]
Offhand, I see no issue with that idea (assuming those tests are the sole generators of this warning).

**Comment by tomball** [comment]
Those tests aren't the only places, just a common area where unused
variables aren't necessarily bugs. Changing the variable's name to "unused"
acts like an annotation, documenting that the warning should be suppressed.

**Comment by tomball** [comment]
Fixed in current source.
