### ISSUE TITLE
j2objc to make a component library

### ISSUE THREAD

**Issue by xabodog** [google/j2objc#1874]
I want to make j2objc as our own pod management component library, I need to import j2objc related framework for this component, and then I do pod install in the host project after installing and compiling Cycle dependencyinmodule "Foundation":Foundation -> CoreFoundation -> Foundation
Then I thought.
1. how to solve this problem
2. can you provide a support cocoapod direct installation j2objc library

Translated with www.DeepL.com/Translator (free version)

**Comment by tomball** [comment]
We have no experience with pods or pod management. Since the j2objc frameworks are (or should be) normal Objective-C static-library XCFrameworks, I suggest asking on StackOverflow without mentioning "j2objc" (since it has nothing to do with your issue). If you find that our frameworks aren't correct, please file a new issue with the specific problem with them.
