### ISSUE TITLE
Architecture issues when running `make new dist`

### ISSUE THREAD

**Issue by abbyThompson** [google/j2objc#1902]
Hello there! I have run into some issues running `make new dist` with the latest version of j2obc (ed9bfa31ba993e1314e7a79d33e0794c7af5b7cd) that are preventing the distribution from being made.

When run on an Intel Mac, I see the following:
```
Both 'watchos-arm64_32' and 'watchos-armv7k' represent two equivalent library definitions.
make[1]: *** [../dist/frameworks/JRE.xcframework] Error 70
make: *** [jre_emul_dist] Error 2
```
This happens when building the JRE framework.

When run on a M1 Mac, I see the following:
```
clang: error: invalid version number in '--target=x86_64-apple-ios13-macabi'
make[1]: *** [/Users/abby.thompson/repo/j2objc/jre_emul/build_result/objs-maccatalyst/JreEmulation.h.pch] Error 1
make: *** [jre_emul_dist] Error 2
```
This happens while building `libjre_emul.a`.

Would you be able to provide some guidance on this? These errors also prevent me from running `make frameworks` successfully on either machine as well. Thank you!

**Comment by tomball** [comment]
Do you need support for watchos? I tried convincing other j2objc users that j2objc isn't appropriate for watch apps (Java's JRE is too big), but was shouted down (virtually) by folks who believe that all SDKs Apple includes must be supported everywhere. Same goes for appletvos, but by then they had worn me down. 😞

If you don't, `make/common.mk` defines the list of architectures to build in its `J2OBJC_ARCHS` variable, which can be set as an environment variable which you can set in your shell's config files. To build without watchos and appletvos slices, build with `J2OBJC_ARCHS="macosx iphone64 iphone64e simulator simulator64 maccatalyst macosx64 maccatalyst64"`. No need for macOS support, remove each arch starting with "mac". With each arch you drop, your build gets faster, so there's no benefit and only cost to include archs your app won't use.

I can't help with the M1 Mac issue, since I don't have access to an M1. However, if your app isn't targeted for MacCatalyst, then building without those archs should avoid the issue.

If you have any other problems with this, please reopen this issue and include your Xcode version number so I can reproduce them.
