### ISSUE TITLE
The import java.nio.file cannot be resolved

### ISSUE THREAD

**Issue by fantomas9091** [google/j2objc#1934]
**import java.nio.file.Files;**

In android studio, the import is Ok. But when I use j2objc to translate I get an error:
_The import java.nio.file cannot be resolved_

**Comment by tomball** [comment]
The [java.nio.file package](https://developers.google.com/j2objc/javadoc/jre/reference/java/nio/file/package-summary) has been supported since [version 2.7](https://github.com/google/j2objc/releases/tag/2.7). You'll need to download and install either that release or better yet, [the latest release](https://github.com/google/j2objc/releases/latest).
