### ISSUE TITLE
JRE.xcframework and libjre_emul.a don't contains JSON classes

### ISSUE THREAD

**Issue by sarsonj** [google/j2objc#1965]
Seems to me Makefile bug, because JSON classes are part of the header files in generated JRE.xcframework. But implementation is not part of .a libs.

Pull request that fixes this  #1964.

**Comment by tomball** [comment]
We separated JSON classes from the JRE for two reasons:

- There are multiple JSON libraries with similar APIs, and the Android version prevented the use of other versions; and
- `org.json` isn't part of the JRE.

The actual issue here appears to be that Make isn't generating a separate JSON framework, which will be easy to add since the libraries are already separately generated.

**Comment by sarsonj** [comment]
@tomball fine, but there were (and still are) JSON header files in generated JRE.framework. That was the reason it confused me. Because:

`PUBLIC_TRANSLATED_HEADERS = $(JAVA_PUBLIC_SOURCES:.java=.h) $(JSON_PUBLIC_SOURCES:.java=.h)`

in Makefile in jre_emul.

**Comment by tomball** [comment]
I fixed that last night (thanks for noticing, though), but amending the commit (we use Mercurial internally) didn't update the pull request as expected. I just forced an update, and now the fix is part of https://github.com/google/j2objc/pull/1966/files.

**Comment by tomball** [comment]
The jre_emul build now creates a JRE.framework without any JSON headers or libraries, and a JSON.framework that only contains them.
