### ISSUE TITLE
Is Java 17 supported?

### ISSUE THREAD

**Issue by adil-hussain-84** [google/j2objc#2095]
This project's [README file](https://github.com/google/j2objc/blob/master/README.md) specifies "JDK 1.8 or JDK 11" in the [Requirements](https://github.com/google/j2objc/blob/master/README.md#requirements).

[Lines 191 to 205](https://github.com/google/j2objc/blob/master/make/common.mk#L191-L205) of the [make/common.mk](https://github.com/google/j2objc/blob/master/make/common.mk) file suggest that Java versions 12 to 19 are supported.

Can I build and use J2ObjC with Java 17? I ask because the latest Android tooling (specifically, the Android Gradle Plugin) require Java 17 or later. (For reference, see the [Android Gradle Plugin 8.0.0 release notes](https://developer.android.com/build/releases/gradle-plugin#8-0-0).)

**Comment by tomball** [comment]
That's tough to answer with a yes or no, as there are really three questions with this one:

1. Does j2objc support all Java 17 language features?
2. Does j2objc support new Java 17 JRE API?
3. Does j2objc run on Java 17?

1) AFAIK, j2objc supports the latest language features, like text blocks and switch expression statements. Much of that support is free, because j2objc uses javac as its front-end; for example, javac converts text blocks into regular strings, so j2objc didn't need to be updated to support that feature.

2) No, J2ObjC's JRE is a fork of Android's libcore library (its JRE), so if it's not available in Android, it's not available on iOS. That's intentional, as the purpose of J2ObjC is to support shared Java across an app's clients, not to be a complete Java platform (that's why we don't/can't call it "Java").

3) No, because the javac team (see 1)) keeps changing access to its packages. So it works on Java 11, but it is currently broken on Java 17 until someone fixes the necessary flags (contributions welcome!).

The Android Gradle Plugin should be able to run command-line tools like j2objc in a separate shell (and likely already does). So try installing both Java 17 and Java 11 on your system, with the j2objc action defined by the flags in the [j2objc.sh](https://github.com/google/j2objc/blob/master/scripts/j2objc.sh) script. That script is also where the flags aren't correct for Java 17, so if you can fix them, great!

**Comment by adil-hussain-84** [comment]
Thanks for the answer 👍 We'll try it out in the coming weeks and see how we get on with it.

**Comment by adil-hussain-84** [comment]
I just re-read my question and @tomball's answer and I see that I was unclear about what I was asking exactly.

What I meant to ask was: Can I build J2ObjC with my `JAVA_HOME` environment variable set to JDK 17? I just tried it and the answer right now is: no. The build fails for me with the following error:

```shell
...
building cycle_finder jar
building jre_emul archs: iphone64 simulator64 simulator
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
translating jre_emul sources
install -m 0644 build_result/cycle_finder.jar ../dist/lib/cycle_finder.jar
error: internal error translating "/Users/adil/Work/j2objc/jre_emul/openjdk/src/macosx/classes/sun/nio/fs/MacOSXNativeDispatcher.java"
java.lang.IllegalAccessError: class com.google.devtools.j2objc.javac.TreeConverter$1 (in unnamed module @0x1a708820) cannot access class com.sun.tools.javac.parser.Tokens$Comment$CommentStyle (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.parser to unnamed module @0x1a708820
	at com.google.devtools.j2objc.javac.TreeConverter$1.<clinit>(TreeConverter.java:1477)
	at com.google.devtools.j2objc.javac.TreeConverter.convertInner(TreeConverter.java:280)
	at com.google.devtools.j2objc.javac.TreeConverter.convert(TreeConverter.java:261)
	at com.google.devtools.j2objc.javac.TreeConverter.convertCompilationUnit(TreeConverter.java:232)
	at com.google.devtools.j2objc.javac.JavacParser.parseFiles(JavacParser.java:212)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processBatch(FileProcessor.java:137)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processInputs(FileProcessor.java:67)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processInputs(TranslationProcessor.java:84)
	at com.google.devtools.j2objc.J2ObjC.run(J2ObjC.java:127)
	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:176)

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.google.devtools.j2objc.ast.CompilationUnit.getSourceFilePath()" because "<local9>" is null
	at com.google.devtools.j2objc.javac.JavacParser.parseFiles(JavacParser.java:214)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processBatch(FileProcessor.java:137)
	at com.google.devtools.j2objc.pipeline.FileProcessor.processInputs(FileProcessor.java:67)
	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processInputs(TranslationProcessor.java:84)
	at com.google.devtools.j2objc.J2ObjC.run(J2ObjC.java:127)
	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:176)
make[1]: *** [/Users/adil/Work/j2objc/jre_emul/build_result/Classes/.translate_mark_jre_emul] Error 1
make: *** [jre_emul_dist] Error 2
```

This is not a blocker for me. Taking @tomball's answer into consideration, I have both JDK 11 and 17 installed on my machine. I have my `JAVA_HOME` environment variable set to JDK 17 except in a small number of isolated processes where I change it to JDK 11. For example, when building J2ObjC and when running the `j2objc` command.

**Comment by parveen-bhatia** [comment]
> That's tough to answer with a yes or no, as there are really three questions with this one:
> 
> 1. Does j2objc support all Java 17 language features?
> 2. Does j2objc support new Java 17 JRE API?
> 3. Does j2objc run on Java 17?
> 

@tomball is Java 17 fully supported now ?

**Comment by tomball** [comment]
> That's tough to answer with a yes or no, as there are really three questions with this one:
>
> Does j2objc support all Java 17 language features?

Still working on switch expressions. The basics are improving with each commit, but the language spec got a lot more complicated in Java 21 with pattern and guard support.

> Does j2objc support new Java 17 JRE API?

Only as requested by customers, and then only APIs that are implemented on Android and don't require massive changes. Examples of new APIs that won't be supported include lightweight threads, pseudo-random number generators, foreign memory access API, and context-specific deserialization filters. Generally, j2objc's purpose is to support code-sharing of Java on iOS that also runs on Android or is transpiled via J2CL on web platforms.

> Does j2objc run on Java 17?

Yes, j2objc is currently in use inside Google on Java 22, and I've been testing new language features on Java 14, 17, and 21.
