### ISSUE TITLE
Error in upgrading J2ObjC from version 2.8 to 3.0: create_JavaLangDeprecated() too few arguments

### ISSUE THREAD

**Issue by raymondChan23** [google/j2objc#2329]
Hi everyone,

I'm currently working on updating J2ObjC in my project from version 2.8 to 3.0. 
I successfully built J2ObjC from the tag 3.0.0 (commit: cff004b845f94255bcb1863ac7cf822778357550). 
However, I encountered an error in the generated .h and .m files from my .java classes.

where the following line is causing a problem:

return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
The error message states: "Too few arguments to function call, expected 2, have 0." 

Upon comparing this line with the corresponding line in the previous 2.8 version, I noticed the difference:
return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaLangDeprecated(false, @"") } count:1 type:JavaLangAnnotationAnnotation_class_()];

In the 2.8 version, the create_JavaLangDeprecated() method had two arguments: false and @"".

My question is, what steps should I take to resolve this error and avoid the "too few arguments" issue when using J2ObjC 3.0?

Thank you in advance for your help and suggestions!

**Comment by tomball** [comment]
Right, in Java 9's JRE two attributes were added to `java.lang.Deprecated`. Annotations only have a single constructor which takes the annotation's attributes as arguments. So when two attributes are added, the constructor changes. Annotations don't have constructors in Java source, so there's no way to add a backwards-compatible constructor; instead, javac generates a call to the new constructor with the default attribute values as arguments.

So, did you the full 3.0.0 j2objc project, or at least the translator and jre_emul sub-projects? The translator uses the jre_emul.jar as its bootclasspath, but the build won't generate the matching JRE header files if only the translator is built. Basically, all j2objc components and transpiled Java files need to use the same j2objc version. Since it looks like you transpiled your source with the 3.0.0 j2objc translator (since the generated code snippet uses the new constructor), I think all you need to do is rebuild the jre_emul sub-project. Or better yet, in the top-level j2objc directory, run `make clean && make -j8 dist`, so that all j2objc components are using the same version.

If for some reason you can't rebuild everything now (though you'll need to eventually), you can translate your project sources with the j2objc `--string-reflection` flag. This skips generating the reflection metadata and runtime annotation support methods, which is where the compiler is failing.

**Comment by tomball** [comment]
Please reopen with details if this doesn't resolve this issue.
