### ISSUE TITLE
Transpiler generated header like JavaUtilMap cannot be bridged to swift

### ISSUE THREAD

**Issue by parveen-bhatia** [google/j2objc#2332]
We are using `JavaUtilMap.h` (transpiled by j2objc) in the bridging header file so that to expose it to Swift. It was working fine before, but with latest master swift is not able to find it's method definitions and throwing errors like `value of type 'JavaUtilMap' has no member 'keySet'`

After analysis, we found that it stated happening because `JavaUtilMap.h` now contains both protocol and interface declarations, which xcode compiler couldn't understand and hence couldn't generate interfaces for swift to recognize it.

```java
...
@protocol JavaUtilMap < JavaObject >
....
@interface JavaUtilMap : NSObject
...
```

**Comment by tomball** [comment]
The issue is that Java 8 added default methods to interfaces (partly to support lambdas), and so j2objc now supports them (can't compile the JRE without them). This means that there's a concrete method conceptually in a @protocol, which Objective-C doesn't support. What it can handle is an @interface and @protocol with the same name, so we had to add the @interface to hold the default method.

So we can't get rid of the @interfaces, but we control how headers are written. I can't find documentation for the Swift importer, but do you know of any formatting tricks or macros we can use with it? Perhaps hide the @interface section from the Swift importer with some sort of "swift ignore" macro?

**Comment by parveen-bhatia** [comment]
There are some swift macros like `NS_SWIFT_UNAVAILABLE("Don't expose")` or `NS_SWIFT_NAME(JavaUtilMapStaticInterface)` but using that doesn't work as expected as then Swift thinks JavaUtilMap is not defined or defined with name JavaUtilMapStaticInterface. I was able to proceed further by applying a patch to remove `@interface JavaUtilMap : NSObject`. Other option is we can pass user defined flags say `EXPOSE_J2OBJC_TO_SWIFT` which then header files can use. Example:

```objectivec
#ifndef EXPOSE_J2OBJC_TO_SWIFT
@end
@interface JavaUtilMap : NSObject
#endif
```

**Comment by tomball** [comment]
We're investigating with our Swift team a separate solution which may fix this correctly: adding a flag that generates separate header files for each inner class, so they can be included with `#import` instead of `#include`. This should eliminate the need for [Segmented Headers](https://developers.google.com/j2objc/guides/segmented-headers), but it hasn't been prototyped yet to verify that's true. To see an example, attached is a "desegmented" version of the [Segmented Headers example](https://developers.google.com/j2objc/guides/segmented-headers#example). 

This isn't a quick fix because most build systems require that compilation of a source file generated known outputs; for example, our Make support "knows" that "Foo.java" generates "Foo.h" and "Foo.m". The "desegmenting" approach requires that the build tool be able to accept an unknown set of outputs; often there's special support for Java (which generates unknown outputs), but not (easily) all languages. So if this approach proves successful, we'll add a j2objc flag so projects can use it as needed.

We're also working on moving our build from Make to [Bazel](https://bazel.build/), as most other Google projects are doing. We already use it internally, so moving our public build to it should mean fewer build breakages. It's also faster than Make, and has no trouble supporting unknown compiler outputs.

[desegmented_headers_example.zip](https://github.com/google/j2objc/files/15381065/desegmented_headers_example.zip)

**Comment by cfdrake-bc** [comment]
Hello! Just wanted to check if there were any updates on this issue? My team is attempting to upgrade our apps from j2objc 2.8 to the latest (running `HEAD` appears to be the recommendation?) and I'm running into this issue, amongst others when I try to compile. I'm seeing the issue mentioned in the original comment as well as things I presume are related, i.e.:

```
Value of type 'JavaUtilList' has no member 'isEmpty'
Value of type 'JavaUtilList' has no member 'getWith'
Value of type 'JavaUtilList' has no member 'indexOf'
Cannot assign value of type '(any JavaUtilListProtocol)?' to type 'JavaUtilList?'
```

I do see a new [commit](https://github.com/google/j2objc/commit/add4718cf098c3565f49576a5f642173cac0c884) that mentions segmented headers as well as the documentation update, but I'm unsure of whether I need to pass in the `-Xseparate-headers` flag to get this to work, and where to do that. Any help would be appreciated, thanks!

**Comment by tomball** [comment]
Although j2objc can now generate separate header files with the `-Xseparate-headers` flag, we found it difficult to roll out internally because every native file that referenced inner transpiled types (such as Guava's ImmutableList.Builder) would need the additional header included. 

The underlying problem we did find, though, is that our [Swift module map files](https://clang.llvm.org/docs/Modules.html#header-declaration) were using `header "j2objc.transpiled.Type.h"` and should have instead used `textual header "j2objc.transpiled.Type.h"`. When`swiftc` precompiles a module map, "header" files are imported, while "textual header" files are included. Fixing our Swift app's map files resolved this problem internally.

We therefore recommend that you check that all j2objc-generated headers are read with `#include` (never `#import`) in Objective C sources and Swift bridging headers, or by using an equivalent module map that lists them using "textual header". I found that the HelloSwift example's bridging header incorrectly uses `#import`, and will update it this week.

**Comment by taylesworth** [comment]
This is old but just for your information, I recently tried to get rid of the patch @parveen-bhatia described in our codebase by following your recommendation to ensure that all of our j2objc headers are `#include` rather than `#import`. Unfortunately, that did not fix this problem so I needed to add the patch back.

**Comment by tomball** [comment]
Right, the #include requirement addresses only half of the issues importing java.util.Map to Swift, and the Swift importer hasn't been improved to handle complex types like that. The reason #include is necessary is because Map has inner classes that extend public types in a super class; to support #import, Objective-C would need to support using @class for the super type, which it doesn't. That's why [segmented headers](https://developers.google.com/j2objc/guides/segmented-headers) are necessary.

The other incompatibility is that in Java 8, default methods were added to interfaces, requiring that j2objc generate both an @interface and an @protocol with the same name. It's not a new hack, as NSObject is both a class and protocol. But the Swift importer can't handle that workaround.
