### ISSUE TITLE
Mismatch on info / debug log levels between logging/Level.java and ASL_LEVEL

### ISSUE THREAD

**Issue by brunobowden** [google/j2objc#465]
Note the mapping:

log.info(...) => \<Notice>
log.fine(...) => \<Info>

I would think that it's more obvious if log.info(...) => <Info> and log.fine(...) => <Debug>, which is how I expect most people intend to use it.

Here are the log outputs:

    Jan  2 23:58:45 iPhone-6-Plus main[1915] <Error>: severe
    Jan  2 23:58:45 iPhone-6-Plus main[1915] <Warning>: warning
    Jan  2 23:58:45 iPhone-6-Plus main[1915] <Notice>: info
    Jan  2 23:58:45 iPhone-6-Plus main[1915] <Info>: fine

From testing:

    log.severe("severe");
    log.warning("warning");
    log.info("info");
    log.fine("fine");

**Comment by brunobowden** [comment]
The mapping should have been listed as:

log.info(...) => \<Notice>
log.fine(...) => \<Info>

**Comment by tomball** [comment]
Apple and Sun/Oracle have very different definitions for these levels ([ASL priorities](https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/LoggingErrorsAndWarnings.html)). ASL defines Notice as "things of moderate interest to the user or administrator," which IMO defines Level.INFO. ASL's Info level is defined as "the lowest priority you would normally log," which matches the FINE/FINER/FINEST levels. 

I think the names are less important than the type of log message and how it is expected to be filtered. It could be argued that naive Java developers consider INFO the lowest level; because they never bother to learn how to configure logging in their apps, anything finer than INFO doesn't show up in their logs and so isn't used in their code. My preference, however, is to support developers who know Java logging well, emitting the expected log messages when they set a given level.

**Comment by brunobowden** [comment]
Fair enough, good point that the ASL levels are different, e.g.

Debug (level 7)

The lowest priority, and normally not logged except for messages from the
kernel.
It would be helpful to add a comment to the wiki explaining this + also the
notes about how to get improved startup performance. I would offer to do
this but it's still a pain sending you wiki edits in GitHub.
