### ISSUE TITLE
AsyncTask support

### ISSUE THREAD

**Issue by OMFOm** [google/j2objc#483]
Does j2objc include support for Android thread operations? I'm using the AsyncTask class but I'm getting the error The import android.os.AsyncTask cannot be resolved.

If it's not supported what should I use as an alternative solution?

**Comment by tomball** [comment]
I'm afraid the first sentence in the javadoc for AsyncTask is: "AsyncTask
enables proper and easy use of the UI thread. " J2ObjC doesn't support UI
code by design. AsyncTask is tightly integrated with the Android OS, with
references to Looper, Message, Parcel, etc.

However, if all you want to do is run background tasks,  you can post
FutureTask jobs to a java.util.concurrent.ThreadPoolExecutor. The
ThreadPoolExecutor gives you the async support, while the FutureTask
provides the ability to cancel the task and get execution status. Android
supports that API, so the code will be portable.
