### ISSUE TITLE
Allow access to native properties

### ISSUE THREAD

**Issue by pennersr** [google/j2objc#487]
I would like to access native properties, such as the `colorRef` in the example below, from native client code. So, basically I want to allow for native code to execute this:

    CGColorRef color = [paint getCGColor];

In order to do this, I need to inject a method into the generated `Paint.h`:

    -(CGColorRef) getCGColor;

I don't think this is currently possible. So, I am forced to return a `long`, and cast that long to a `CGColorRef`, as in:

    CGColorRef color = (CGColorRef) [paint getCGColor];

Example:

    public class Paint {
    
        /*-[ {
          CGColorRef colorRef;
        }
        ]-*/;
    
    
        public native long getCGColor()
        /*-[
            return (jlong) colorRef;
        ]-*/;
    }

Is there a better workaround for this. Or, would injecting additional info into the header be a sensible feature?

**Comment by tomball** [comment]
For Objective-C instances, Object works because java.lang.Object is mapped
to NSObject. For other pointers like CGColorRef, though, long is the best
solution since there's notion of a raw pointer in Java. You'll see examples
of that in the native code for some of our JRE classes, such as
java.util.regex.Pattern
<https://github.com/google/j2objc/blob/master/jre_emul/android/libcore/luni/src/main/java/java/util/regex/Pattern.java#L288>
.
