### ISSUE TITLE
Java 1.8 support?

### ISSUE THREAD

**Issue by dabeersk** [google/j2objc#500]
It looks like j2objc does not support Java 1.8 features. Specifically lambda expressions. Is this something you are working on?

**Comment by tomball** [comment]
We plan on supporting the Java 8 language features toward the end of Q3 this year. There's no reason to hurry this work, since neither Android or GWT supports Java 8 yet (it's hard to write platform-independent code when two of the three target platforms don't support a feature).

New Java 1.8 API, though, depends on Android support, since j2objc's JRE emulation is based on Android source. This includes the new java.util.function and java.util.stream packages.

**Comment by pfista** [comment]
+1 :)

**Comment by tomball** [comment]
Anyone who wants to be notified when this is rolled out should click on this issue's Subscribe button; there's no need to add a comment.

**Comment by tomball** [comment]
Java 8 lambda expressions and method references are now supported: use a "-source 8"  flag when transpiling.

**Comment by formvoltron** [comment]
Very good!  Can't wait to try it out.
