### ISSUE TITLE
Ignore specific java annotations?

### ISSUE THREAD

**Issue by MiguelGL** [google/j2objc#503]
I have sets of Java classes using JAXB annotations, `javax.xml.bind.annotation.Xml*` stuff mostly and some `com.google.gwt.core.client.js.Js*` ones as well. 

Generating the iOS classes works fine if I include both JAXB api and GWT User jarfiles when running j2objc. But when trying to compile them, references `#include "com/google/gwt/core/client/js/JsExport.h"` and the like cannot be resolved. 

Since these annotations do not really make any sense nor provide any functionality once Objective-C-ized, I was wondering: is there any way to tell the j2objc code generator to just "ignore" them? I mean, just as if they had never been added to my Java classes in the first time. 

This obviously does not only apply to GWT and JAXB annotations. I am thinking JPA and many others as well, which do make sense when running within a specific context. One could of course go and j2objc-ize all these annotations, but having the chance to simply ignore them would even be more convenient IMHO. 

Thanks!

**Comment by tomball** [comment]
Here's a general rule: prefer putting classes you don't already have an iOS library for (like JUnit) on the sourcepath, not the classpath. This moves any compile or link errors to the beginning of transpilation, and as an engineer you know that the sooner a problem is detected, the easier it is to fix or change the design to avoid it.

The good news is that this only affects annotations with runtime retention, so lots of annotations aren't referenced in generated files. It's always safe to include source annotation jars on the classpath, since they never "leak" into translated code.

Now the bad news: we can't ignore runtime annotations because many libraries wouldn't work without them. If all the runtime annotations were just marker annotations (no properties), we could store the classname instead of the type constant, and dynamically load them when the annotations are reflectively referenced. However, properties are a problem, because some of the constants they store would be very difficult to encode for later creation via reflection. I'm often amazed at how annotations can be abused by wily Java developers, so by storing what the compiler outputs seems the best course.

However, there's an easy workaround for most runtime annotations: just transpile and include them into your app. In most cases, you can include the source file with your project since annotations are generally much more portable than the libraries they're from. For example, [JSExport.java](https://github.com/gwtproject/gwt/blob/master/user/src/com/google/gwt/core/client/js/JsExport.java) has nothing GWT-specific about it other than its package name.

For any annotations you don't have source for, remember they are just a form of interface, so their public API defines them. Even better, javadoc includes the annotation's metadata at the top of the class description, so you don't have to figure that out.

More good news (if you care): j2objc now supports annotation processing. All that's necessary is to put the jars with the annotation processors on the classpath (not the sourcepath, since they need to execute).

**Comment by MiguelGL** [comment]
Thanks so much for such a detailed and quick answer. I'm honoured by yourself responding -- I got highly motivated and jumped into j2objc after [your recent GWT.create talk] (https://www.youtube.com/watch?v=NwhfyQG3myc). 

So I followed your advice and placed dependencies source jars into my `-sourcepath` (vs. compiled jars in `-classpath`). I also selectively added the annotations source files from GWT and JAXB I depended on. 

Now my j2objc generated code compiles and links perfectly. Thanks again for your help!

On the annotation processing support: That's great news indeed (I may be one of those annotation junkies you mention ;) I am heavily using [Project Lombok] (http://projectlombok.org/) to annotate my data models and pointing j2objc to the [de-lomboked] (http://projectlombok.org/features/delombok.html) sources. I will certainly next try to make it part of my j2objc case. As per your comment, I assume placing lombok's jar into the `-classpath` should do, am I right? I am aware though that what lombok does is somehow different/complimentary to plain annotation processing - I'll try to find out.

**Comment by tomball** [comment]
j2objc calls the Eclipse batch compiler in its annotation mode to handle
the annotation processing, then adds any .java files found in the output
directory to the list that needs translation. It's therefore best if the
output directory is separate from the source directories, but that's true
for most projects since it makes cleaning out the build artifacts easier. I
have no experience with Lombok, but if its jar defines discoverable
processors
<http://stackoverflow.com/questions/11685498/what-is-the-default-annotation-processors-discovery-process>
then just putting on the classpath should work. If it requires setting
javac's -processor flag to work, then we'll need to add that to j2objc
(contributions
are always welcome
<https://github.com/google/j2objc/blob/master/CONTRIBUTING.md> ;-).

BTW, since you like Lombok, you might also like the set of Auto projects
<https://github.com/google/auto> from a couple of friends of mine at
Google. If Lombok's annotation processors aren't discoverable, AutoService
<https://github.com/google/auto/tree/master/service> has a generator they
can use. :-)

**Comment by vals-productions** [comment]
I came up with the following way of excluding some code from being considered by j2objc translator. Just thought this might be useful. It gives almost preprocessor like flexibility to manipulate the code.

I've been using bash script for my j2obj code conversions. In this case ```sed``` comes handy.

The following is sample script to convert one java class file:

```
00 #/bin/sh
01 sed -i '' -e 's#/\*exclb\*/#/\*exclb#g' File.java
02 sed -i '' -e 's#/\*excle\*/#excle\*/#g' File.java
03 j2objc [... j2objc command line parameters ...] File.java
04 sed -i '' -e 's#/\*exclb#/\*exclb\*/#g' File.java
05 sed -i '' -e 's#excle\*/#/\*excle\*/#g' File.java
```

File before and after j2objc code translation:

```java
package ...;
public class File {
/*exclb*/
	// The code between exclb and excle comment is going to be excluded
	@SomeAnnotation
	private boolean undesiredMethod() {
		return false;
	}
/*excle*/
	public void desiredMethod() {
	}
}
```

File ready for j2objc code translation:

```java
package ...;
public class File {
/*exclb
	// The code between exclb and excle comment is going to be excluded
	@SomeAnnotation
	private boolean undesiredMethod() {
		return false;
	}
excle*/
	public void desiredMethod() {
	}
}
```
Lines 01 and 02 of the script will transform independent block comments into
opening and closing block comments. The code between them will be ignored as a comment. Lines 04 and 05 will return them back into original state.
