### ISSUE TITLE
Using Package Prefixes With Xcode Build Rule

### ISSUE THREAD

**Issue by mvoong** [google/j2objc#505]
We're currently exploring integrating J2ObjC into Xcode as a Build Rule for a simpler workflow, as used by the https://github.com/tomball/j2objc-sample-reversi sample project. We have multiple Java classes with the same class name, in separate packages, so we removed the --no-package-directories flag from the j2objc call, resulting in the following build rule:

![screen shot 2015-03-16 at 14 30 33](https://cloud.githubusercontent.com/assets/571634/6668278/9ff4e95e-cbe9-11e4-89d4-6ca233d753fc.png)

Xcode throws an error when trying to compile the resulting .m and .h files because it doesn't know the full path of the generated files:

![screen shot 2015-03-16 at 14 35 44](https://cloud.githubusercontent.com/assets/571634/6668289/bf2abf60-cbe9-11e4-9145-b9333ab84f4d.png)

I can think of the following solutions, none of which are ideal:

1. Hardcode the directory in the Output Files path in the build rule
2. Don't use package prefixes, and don't use the same class name twice

Does anyone have any other ideas?

**Comment by tomball** [comment]
Create separate static library build targets for the conflicting names, then add them as dependencies to your app. Another idea is to use more unique names for the classes, if they're in your code.

For future reference, discussions are held on http://groups.google.com/group/j2objc-discuss.

**Comment by tomball** [comment]
Last idea (what the jre_emul library build does): translate and compile the Java sources using a makefile, then add it as an [external build project](https://github.com/google/j2objc/wiki/External-Build-Projects) to your Xcode project. This problem is due to an Xcode limitation (can't support output sub-directories), so building that part of your project outside of Xcode mean fewer limits.

**Comment by mvoong** [comment]
Thanks, Tom!
