### ISSUE TITLE
JDK 1.7 RuntimeException missing constructor

### ISSUE THREAD

**Issue by egu002** [google/j2objc#507]
1.7 introduced a new protected constructor for RuntimeException (http://docs.oracle.com/javase/7/docs/api/java/lang/RuntimeException.html , bottom of the page). Translating a class (https://github.com/jdereg/json-io/blob/master/src/main/java/com/cedarsoftware/util/io/JsonIoException.java) that extends RuntimeException gives the error:
 JsonIoException.java:101: The constructor RuntimeException(String, Throwable, boolean, boolean) is undefined
javac -version reports 1.7.0_65, and I'm using j2objc-0.9.6.1. I'm guessing it's because RuntimeException in jre_emul hasn't been updated?

**Comment by tomball** [comment]
Good catch -- not only is this an issue in RuntimeException's superclasses, too, but it hasn't been updated in [Android, either](http://developer.android.com/reference/java/lang/RuntimeException.html).

**Comment by mvoong** [comment]
We're seeing this issue too. What would be involved in updating jre_emul?

**Comment by nbransby** [comment]
Both seeing the same because both trying to translate the same library.. https://github.com/jdereg/json-io :) 

Interestingly the projects appears to work on android, @tomball does your response suggests it shouldn't?

**Comment by tomball** [comment]
The fix is in j2objc's source, just not in a distribution bundle yet. It's
easy to clone the source and build the bundle with the latest, though: Building
J2ObjC <https://github.com/google/j2objc/wiki/Building-J2ObjC>.

My comment on Android was based on looking at their latest source
<https://android.googlesource.com/platform/libcore/+/master/luni/src/main/java/java/lang/Throwable.javahttps://android.googlesource.com/platform/libcore/+/master/luni/src/main/java/java/lang/Throwable.java>.
My guess is that these constructors are resolved because the source
referencing them is built with a recent JDK, not the Android runtime.
That's likely to die with a NoSuchMethodError when that code executes,
though.

**Comment by mvoong** [comment]
Excellent! It worked, thanks.

**Comment by tomball** [comment]
Released in 0.9.7.
