### ISSUE TITLE
Annotation Processing fails for Dagger2

### ISSUE THREAD

**Issue by lilianes** [google/j2objc#510]
Annotation Processing fails for Dagger2
[12:40:50] Michael Gorski: I read the discussion in the j2objc form (https://groups.google.com/forum/#!topic/j2objc-discuss/iwPEMeBa8RA) from @confile. 

It turns out that I have the same problem when building my sources using ``dagger-compiler-2.0-20150318.194524-17-jar-with-dependencies.jar``

It seems that j2objc does not execute the annotation processor correctly. I also tested the sample project from @confile here: https://github.com/confile/j2objc-dagger

with the same results: 

package com.example;

^

Internal compiler error: java.lang.NoSuchMethodError: com.google.common.collect.Multimaps.filterKeys(Lcom/google/common/collect/SetMultimap;Lcom/google/common/base/Predicate;)Lcom/google/common/collect/SetMultimap; at com.google.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:225)

Also it work form me with pure ``javac``.

**Comment by steffimueller** [comment]
+1

**Comment by tomball** [comment]
Have you built from the latest source
<https://github.com/google/j2objc/wiki/Building-J2ObjC>? Annotation support
isn't in any built release yet.

**Comment by lilianes** [comment]
@tomball yes I build from source. Google autofactory works well with j2objc, but when using dagger-compiler-2.0-20150318.194524-17-jar-with-dependencies.jar no source files are generated.

**Comment by confile** [comment]
@tomball When I create the annotation source files with java ATP and use j2objc with dagger-2.0-SNAPSHOT.jar everything works fine. Since  

```
dagger-compiler-2.0-20150318.194524-17-jar-with-dependencies.jar
```
works well wich ``javac`` it must be a ``j2objc`` problem.

**Comment by tomball** [comment]
This has nothing to do with transpilation or annotation processing, just a basic Java versioning issue:

Internal compiler error: java.lang.NoSuchMethodError: com.google.common.collect.Multimaps.filterKeys(Lcom/google/common/collect/SetMultimap;Lcom/google/common/base/Predicate;)Lcom/google/common/collect/SetMultimap; at com.google.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:225)

The j2objc translator uses Guava classes internally, so the classpath in its jar's manifest.mf file refers to the Guava jar included with the j2objc distribution. The problem is that you're using a library, Dagger 2, that needs a newer version of Guava (it's included in the "jar-with-dependencies" jar you're using). The Java runtime places jars defined in the executable jar's manifest at the beginning of the classpath, followed by any other jars.

You can verify this by editing javac-script.sh and changing the classpath to first include the Guava jar used by j2objc:

-classpath ../j2objc-0.9.6.1/lib/guava-14.0.1.jar:lib/javax.inject-1.jar:lib/dagger-compiler-2.0-20150330.203231-18-jar-with-dependencies.jar

The same error is reported using javac.

We need to investigate using a build tool like [jarjar](https://code.google.com/p/jarjar/) to make the translator's Guava dependencies internal.

In the meantime, you can work around this by replacing the j2objc script with one that invokes java with the translator's classpath explicitly listed (don't use the -jar option), either using the latest Guava version or using dagger-compiler-2.0-20150330.203231-18-jar-with-dependencies.jar instead.

**Comment by tomball** [comment]
The problem is that j2objc uses guava, while Dagger 2 now requires a newer
version. I'm in the process of upgrading our guava library to 18.0 (the
latest). To get past this before this is complete, use javac to generate
the Java sources from your annotations. It's easiest to run javac to output
to a new temporary directory, as all the .java files in that directory were
created by annotation processing.

**Comment by confile** [comment]
@tomball Thanks for your effort. Your suggestion is great. That is exactly what I am doing right now. Thank you.
