### ISSUE TITLE
EXC_BAD_ACCESS in simple code

### ISSUE THREAD

**Issue by zubchenok** [google/j2objc#514]
public class Test 
    {
        public void runTest() {
            field = new Foo();
            Foo f = field.bar();
        }

        private Foo field;

        private class Foo {
            public Foo bar() {
                field = null;
                return this;
            }
        }
    }

Calling runTest in translated code causes the EXC_BAD_ACCESS on the latest 64bit iPhones. And it only happens when build Optimization Levels set 'Faster' and higher: -O2, -O3, -Os or -Ofast. So usually in Release configuration. 
BTW, translated code works well when Optimization Levels set 'None' or 'Fast': -O0 or -O1.

This class causes EXC_BAD_ACCESS even if translated with j2objc 0.9.6.1 and j2objc compiled from the latests sources (cloned on 7th of April 2015).

XCode 6.2 (6C131e)

**Comment by zubchenok** [comment]
When I simplified translated code and did some refactoring I came to this pure objc code, which fails with EXC_BAD_ACCESS when is compiled with optimization level > -O1.

**Comment by zubchenok** [comment]
Published it to StackOverflow 
http://stackoverflow.com/questions/29495339/exc-bad-access-in-simple-code-in-release
and Apple Bug Reporter with Problem ID 20449878

**Comment by tomball** [comment]
It sounds like a bug in the ARM64 compiler support, since it only affects iPhone 6 which is 64bit. Keith's the expert as he wrote the J2OBJC_FIELD_SETTER macro, which AFAIK it carefully follows Apple's reference counting guidelines. The fact this only happens on a major new architecture (64bit ARM) and only when optimized makes me suspect clang's the culprit.

As a workaround, have you tried building with ARC? Xcode allows per-file compilation flags, so try adding -fobjc-arc to the file that's crashing. If that doesn't work, the method can be deoptimized by moving one of the two statements to a separate method.

**Comment by tomball** [comment]
This appears to work with clang, version 7.3.
