### ISSUE TITLE
@Weak reference to parent can often lead to early release of parent

### ISSUE THREAD

**Issue by neocxi** [google/j2objc#521]
For example, the HashMap.java in jre_emul exposes an inner class object through method keySet(). In many use cases of HashMap, there might be no direct reference to the HashMap object but there are references to its keySet or values. As of now, those inner classes have @WeakOuter annotation that makes the aforementioned cases crash. https://github.com/google/j2objc/blob/master/jre_emul/android/libcore/luni/src/main/java/java/util/HashMap.java#L918

We have a patch to fix this by converting strong reference fields into thread-safe WeakReference objects to make sure the HashMap will not be destroyed when its views are live, while preventing strong reference cycles. There are a couple more instances like this in jre_emul. If you think this approach is fine, then we can submit a pull request. Otherwise we can discuss what a proper fix will be.

Thanks!

**Comment by kstanger** [comment]
I'd be interested to see your patch, but I'm a bit hesitant to start using
WeakReference within core java.util collections. Our WeakReference
implementation uses some Objective-C magic (eg. changing the object's
class) that might have unintended consequences.

I have an alternate proposal for this "collection alternate view" reference
cycle problem that I've been sitting on for a while but haven't found the
time to implement or test. This is how it works:
- The weak field is declared as the object's "owner". In this case we can
modify the annotation for example @WeakOuter(owner = true). If the "owner"
is not an outer reference, the field must be declared final (so it can't be
reassigned)
- When the object's retain count becomes 2 (something other than it's owner
is holding it), it retains it's owner.
- When the object's retain count drops back to 1 (only its owner is holding
it) it releases it's owner.

**Comment by kstanger** [comment]
Of course, my proposed solution would require generating non-arc code.

**Comment by advayDev1** [comment]
Any update on this?  Would it be preferable until a better solution is in place, to remove @WeakOuter here?

While the current state is better for memory consumption, it is incorrect.

**Comment by advayDev1** [comment]
Also, there is an alternative design for these collection classes that sidesteps the problem altogether, correct?
Namely, currently a HashMap object does double duty - it posses the data/behavior re: a HashMap and also caches view objects (which point back to the HashMap).  You could split the implementation such that 1) you have HashMapImpl which carries the data/behavior, 2) HashMap proxies to an instance of that, 3) HashMap view classes get a reference to HashMapImpl, not HashMap.

**Comment by kstanger** [comment]
A particularly harsh case of this bug is in Guava's AggregateFuture, where there is a paired relationship between the [AggregateFuture](https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/AggregateFuture.java#L42) and it's [RunningState](https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/AggregateFuture.java#L91). Unlike with the java.util collections it is not easy for a user to change their code to ensure the parent outlives the child.

**Comment by kstanger** [comment]
This issue is fixed in J2ObjC 1.1. HashMap and other java.util collections are fixed in [this commit](https://github.com/google/j2objc/commit/39c7247e677e6aceae6706d01bf3260f5d602a08). More generally this problem can be solved using the new [RetainedWith annotation](https://github.com/google/j2objc/blob/master/annotations/src/main/java/com/google/j2objc/annotations/RetainedWith.java) however I recommend avoiding it's use in user code if possible.
