### ISSUE TITLE
Guava 18?

### ISSUE THREAD

**Issue by robertrangel** [google/j2objc#526]
I see J2Objc was upgraded to Guava 18 but then reverted back to 14. Why didn't you stick with 18?

**Comment by tomball** [comment]
It's called a "rollback", where when a commit breaks something, a second
commit undoes it until the problem can be fixed. The underlying problem is
that the j2objc translator uses Guava, so whatever version it was built
with prevented use of other versions. We just changed the build to use
jarjar <https://code.google.com/p/jarjar/>, so the package names of the
classes j2objc uses can be renamed, which avoids conflicts. Now that that's
in place, we should be able to upgrade Guava without breaking other
projects.

**Comment by tomball** [comment]
Guava is now at version 18.
