### ISSUE TITLE
Undefined symbols for architecture i386 when using enums in Swift

### ISSUE THREAD

**Issue by ex3ndr** [google/j2objc#535]
I have very simple enum
```
/*
 * Copyright (C) 2015 Actor LLC. <https://actor.im>
 */

package im.actor.model;

/**
 * Application type
 */
public enum AppCategory {
    GENERIC, ANDROID, IOS, WEB
}
```

in Swift code i am trying to create it by command
```
AMAppCategoryEnum_get_IOS
```
an linking is failure with linking error:

```Undefined symbols for architecture i386:
  "_AMAppCategoryEnum_get_IOS", referenced from:
      __TF8ActorAppg3MSGCS_14CocoaMessenger in CocoaMessenger.o
  "_AMDeviceCategoryEnum_get_MOBILE", referenced from:
      __TF8ActorAppg3MSGCS_14CocoaMessenger in CocoaMessenger.o
ld: symbol(s) not found for architecture i386```

**Comment by ex3ndr** [comment]
Workaround i using enums as described in #520 
```
AMAppCategoryEnum.values().objectAtIndex(AMAppCategory.IOS.rawValue) as! AMAppCategoryEnum
```

**Comment by tomball** [comment]
The issue here is that AMAppCategoryEnum_get_IOS() [is always inlined](https://github.com/google/j2objc/blob/master/jre_emul/Classes/J2ObjC_common.h#L326), so it isn't available as a public symbol. It looks like we need to define static accessors for the enum constants, such as:
```
+ (AMAppCategoryEnum *)GENERIC;
+ (AMAppCategoryEnum *)ANDROID;
+ (AMAppCategoryEnum *)IOS;
+ (AMAppCategoryEnum *)WEB;
```
which can be accessed from Swift using:
```
var appCategory:AMAppCategoryEnum = AMAppCategoryEnum.IOS();
```

**Comment by confile** [comment]
@tomball That would be great. Working with Enums from Swift is very ugly because you have to type so much. 

Another possibility would be to let a generated enum not extend from ``JavaLangEnum`` but extend something like ``GenericJavaLangEnum`` with: 
````
GenericJavaLangEnum : JavaLangEnum { ... }
```

``GenericJavaLangEnum`` then should have generic access methods. I am not sure if this is possible that way, but if so we could write an extension from Swift for ``GenericJavaLangEnum`` and make access much simpler.

**Comment by tomball** [comment]
I added a --static-accessor-methods flag to generate accessor methods for static variables and enum constants. With it, enum constants can be directly accessed by their names. For example, with "enum { RED, YELLOW, BLUE }":

    var t:ColorEnum = ColorEnum.RED();
    println("Color accessor: \(t)");   // prints "RED".

Since the accessor methods just call the accessor functions, code that's calling the functions won't be slowed down.

**Comment by tomball** [comment]
Pushed to public repository.
