### ISSUE TITLE
Proper naming of methods

### ISSUE THREAD

**Issue by ex3ndr** [google/j2objc#536]
I know that there are some issueses on this, but i have some simple idea about naming. Why not just replace all "withNSString" with real variable names like "withText"? In our project we have very big file that just rename all public methods of library to this convention.

May be add some flag that will enable this type of method naming with auto-checking for duplicates?

This is the only problem with j2objc.

**Comment by tomball** [comment]
Is your objection just the use of NSString as the type? Since strings are used for more than just text (database keys, for example), would withString be acceptable? That will only cause problems for projects that define a String class in the default package, neither of which is likely and is easily fixed.

**Comment by ex3ndr** [comment]
"text" is an example. It may be "phoneNumber" or "userName". Type is not useful, but name is good.
Something like registerUserWithName:withPhone:withAvatar. Now it is registerUserWithNSString:withInt:withNSString.

**Comment by tomball** [comment]
Then you're back to the original problem: in order to support parameter
names in external classes, we'd have to stop resolving classes using class
files, since they don't have parameter names. That means dropping support
for static library projects, and instead doing a single translation of all
the sources for the project's Java classes and all of their dependent
classes, like GWT does. The alternative is worse: drop support for
overloaded methods.

If that's not clear, just create a sample Java class with some methods with
parameter names, compile it with javac, and dump it with javap -v -- you'll
see that parameter names aren't in the class file, and therefore aren't
available to compilers to resolve methods.

**Comment by ex3ndr** [comment]
Our code actually is some not very big "frontend" classes may be we can mark methods to use with good names. For example mark any parameter with annotation with it's public name. I think this can work.

**Comment by tomball** [comment]
Or use @ObjectiveCName with the selector you want to use:

In Test.java:
  @ObjectiveCName("split:regex:limit:")
  public static String[] splitString(String s, String regex, int limit) {
    return s.split(regex, limit);
  }

In (translated) Test.h:
@interface Test : NSObject
...
+ (IOSObjectArray *)split:(NSString *)s
                    regex:(NSString *)regex
                    limit:(jint)limit;
...

**Comment by tomball** [comment]
If you want to change method names without modifying the Java sources, the translator supports [method mapping files](https://github.com/google/j2objc/wiki/Changing-Method-Names).

**Comment by ex3ndr** [comment]
How i need to include this annotation to my project? I tried to copy it to my sources, but it seems that i am doing something wrong because it is not working.

**Comment by tomball** [comment]
The Java source and Objective C output were copied from this test class. It
should just transpile:

import com.google.j2objc.annotations.ObjectiveCName;

class Test {

  @ObjectiveCName("split:regex:limit:")
  public static String[] splitString(String s, String regex, int limit) {
    return s.split(regex, limit);
  }

  @ObjectiveCName("another:test:")
  void foo(int bar, String mumble) {}
}

The only restriction on selectors is that there needs to be a colon (':')
for each Java parameter. Notice how the selector names don't need to match
Java method or parameter names; the translator uses whatever selector it's
given, so if the compiler complains about any bad name, then the developer
has to fix them. The translator splits the selector by its colons, then
appends the type and name for each Java parameter:

another: => "int bar", test: => "String mumble" translates to
"another:(int)bar test:(NSString *)mumble".
