### ISSUE TITLE
Best way of working with strings

### ISSUE THREAD

**Issue by ex3ndr** [google/j2objc#541]
In java we use code for building debug strings like this:
```
String str = "";
str += value + "\n";
str += value2;
```

And i expect that it will be automatically transformed to ```StringBuilder```, but it doesn't work for j2ObjC. What is best way of working with strings for avoiding unnecessary allocations?

**Comment by tomball** [comment]
StringBuilder conversion isn't defined by any Java specification, it's just how javac converts it under the covers. This therefore is neither a bug or an enhancement request. In the future, please ask similar questions on [StackOverflow.com, with the #j2objc tag](http://stackoverflow.com/questions/tagged/j2objc) -- that way, other interested developers can find the answer.

Since message dispatching is slower in Objective C than in Java, converting string concatenation to StringBuilder messages is slower, too. j2objc therefore translates to a [JreStrcat()](https://github.com/google/j2objc/blob/master/jre_emul/Classes/JreEmulation.m#L72) function, which is much faster since the only Objective C messages it sends are to objects that need a string description.
