### ISSUE TITLE
-version flag on j2objc

### ISSUE THREAD

**Issue by brunobowden** [google/j2objc#546]
@AdvayDev1 and I would like to have a --version flag on the j2objc binary so that we can check which version someone is compiling against. This would be helpful for checking to make sure that someone isn't using the intended version.

It's not entirely straight forward as you'd need to remember updating the version number when pushing new versions.

**Comment by tomball** [comment]
That's a blast from the past, as the first change I made to the Java VM was to add its -version flag. What we did then was to make up an overridable version string if one wasn't provided (I think it was username+date), so that when people wanted support for some rogue version we knew where to send them. We can add something similar to j2objc's build.

**Comment by tomball** [comment]
Added -version flag, with only one hyphen to match javac's flag.

**Comment by brunobowden** [comment]
Very smart. Advay just introduced a similar naming convention for the
plugin.
