### ISSUE TITLE
Provide default values for more properties, such as java.version

### ISSUE THREAD

**Issue by lukhnos** [google/j2objc#565]
I am using j2objc to translate a library that queries a number of Java system properties, mostly for diagnosis purposes. Many of those don't exist in jre_emul. I wonder if it makes sense to add at least those that are found in Android. I also wonder what the values should be.

The properties in question are like `java.specification.version`, `java.vendor`, `java.version`. The library I'm using assumes those values must exist (and therefore it never expects `null`). It's not hard to either add those properties during runtime by the Objective-C app that uses the library, or I can modify its source code. My proposal here is really more like to get out-of-the-box feature parity (with Android) from j2objc.

Here's a list of what Dalvik VM provides according to [the Android API doc](http://developer.android.com/reference/java/lang/System.html). I've also added the values provided by Oracle's JVM on OS X as well as those currently by j2objc.

| Property                      | Android                   | JVM on OS X                        | jre_emul          |
| ----------------------------- | ------------------------- | ---------------------------------- | ----------------- |
| file.separator                | /                         | /                                  | /                 |  
| java.class.path               | .                         | .                                  | null              |  
| java.class.version            | 50.0                      | 52.0                               | null              |  
| java.compiler                 | (empty string)            | null                               | null              |  
| java.ext.dirs                 | (empty string)            | (paths)                            | null              |  
| java.home                     | /system                   | /Library/Java/....                 | (pwd of the app)  |              
| java.io.tmpdir                | /data/data/(app-id)/cache | (tmp path)                         | (tmp path)        |          
| java.library.path             | /vendor/lib:/system/      | (paths)                            | null              |  
| java.specification.name       | Dalvik Core               | Java Platform API Specification    | null              |  
| java.specification.vendor     | The Android               | Oracle Corporation                 | null              |  
| java.specification.version    | 0.9                       | 1.8                                | null              |  
| java.vendor                   | The Android Project       | Oracle Corporation                 | null              |  
| java.vendor.url               | http://www.android.com/   | http://java.oracle.com/            | null              |  
| java.version                  | 0                         | 1.8.0_45                           | null              |  
| java.vm.name                  | Dalvik                    | Java HotSpot(TM) 64-Bit Server VM  | null              |  
| java.vm.specification.name    | Dalvik                    | Java Virtual Machine Specification | null              |  
| java.vm.specification.vendor  | The Android               | Oracle Corporation                 | null              |  
| java.vm.specification.version | 0.9                       | 1.8                                | null              |  
| java.vm.vendor                | The Android Project       | Oracle Corporation                 | null              |  
| java.vm.version               | 2.1.0                     | 25.45-b02                          | null              |  
| line.separator                | \n                        | \n                                 | \n                |  
| os.arch                       | i686                      | x86_64                             | null              |  
| os.name                       | Linux                     | Mac OS X                           | Mac OS X (*)      |          
| os.version                    | 3.4.67+                   | 10.10.4                            | null              |  
| path.separator                | :                         | :                                  | :                 |  
| user.dir                      | /                         | /Users/(id)/...                    | (pwd of the app)  |              
| user.home                     | (empty string)            | /Users/(id)/...                    | /Users/(id)/...   |              
| user.name                     | root                      | (user id)                          | (user id)         |          

(*) Or `iPhone` or `iPhone Simulator`

There's also `sun.arch.data.model` which some Java programs use to tell if it's running on a 64-bit system. The property is `null` on Android.

**Comment by tomball** [comment]
Some of these are different by necessity. iOS has a strict app sandbox, so java.home and user.dir use its root since that's the root of anything potentially accessible. It looks like our user.dir is incorrect for OS X, though, and should be the same as user.home.

Most of the java.* settings don't make sense without a JVM, though we can provide empty strings or zeros. I suppose the java.vm.specification.* and java.vm.vendor can be "J2ObjC"; we're not an officially supported Google project the way Android is, and so shouldn't have "Google" in any of those strings.

Here's what I therefore propose adding, other suggestions are welcome:

| Property                      | value |
| ----------------------------- | ------------------------- |
| java.class.path               | (empty string)  |
| java.class.version            | 0  | 
| java.compiler                 | (empty string)  |
| java.ext.dirs                 | (empty string) |  
| java.library.path             |  (empty string) |  
| java.specification.name       | J2ObjC  |  
| java.specification.vendor     | J2ObjC |  
| java.specification.version    | 0   |  
| java.vendor                   | J2ObjC  |  
| java.vendor.url               | http://j2objc.org/   |
| java.version                  | 0   |  
| java.vm.name                  | (empty string)  | 
| java.vm.specification.name    | J2ObjC    |  
| java.vm.specification.vendor  | J2ObjC    |  
| java.vm.specification.version | 0   |  
| java.vm.vendor                | J2ObjC  |  
| java.vm.version               | 0  |  
| os.arch                       | (utsname.sysname*)  |
| os.version                    | (utsname.version*) |  

\* Run "man 2 uname" to see utsname definition.

**Comment by lukhnos** [comment]
Thanks! For the property `os.version`, `utsname.version` reads:

    Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64

That's on OS X 10.10.3, and iOS 8.3 gives similar result. `utsname.release` reads `14.3.0` on OS X 10.10.3 and `14.0.0` on iOS 8.3.

I wonder if it makes more sense to call `[NSProcessInfo processInfo].operatingSystemVersion` (and falls back to `[UIDevice currentDevice].systemVersion` on iOS or `Gestalt()` on OS X when `operatingSystemVersion` is not available) in this case?

As for `os.arch`, `utsname.sysname` returns `Darwin`, but should that use the `hw.cputype` and `hw.cpusubtype` from `sysctl(3)` and form strings like `"x86_64"` instead?

**Comment by tomball** [comment]
Have an easier solution for os.arch: invoke clang with -DJ2OBJC_BUILD_ARCH=$(CURRENT_ARCH), then set os.arch using that definition. That tells developers what architecture the code was compiled for, and they can use native syscalls to get what's actually running.
