### ISSUE TITLE
The body of a do statement with constant false expression is erroneously skipped

### ISSUE THREAD

**Issue by lukhnos** [google/j2objc#569]
This currently does not get translated to what you expect:

```java
// It's very unlikely that the Objective-C code returns 1.
int f() {
    int x;
    do {
        x = 1;
    } while (false);
    return x;
}
```

The translated code turns out to be:

```objc
- (jint)f {
  jint x;
  return x;
}
```

And this crashes j2objc:

```java
int g() {
    int x;
    foo:
        do {
            x = 1;
        } while(false);
    return x;
}
```

[`StatementGenerator.java:628`](https://github.com/google/j2objc/blob/a5b32a1fcfe6759bb5908ade5a4e6e94fbafcb26/translator/src/main/java/com/google/devtools/j2objc/gen/StatementGenerator.java#L628) throws `NullPointerException` when j2objc tries to generate the output. The crashing line wants to do `node.getBody().accept(this)`, but 
`node.getBody()` (`node` is an instance of `LabeledStatement`) returns `null`.

It appears that `ConstantBranchPruner.endVisit(DoStatement)` removes the `do` statement's body entirely even though it should be kept in the `while (false)` case.

**Comment by tomball** [comment]
Only the "this crashes j2objc" is a bug, the rest is by design. Try compiling f() with javac, then run "javap -c" on it to see the bytecode:

        Code:
           0: iconst_1
           1: istore_1
           2: iload_1
           3: ireturn

javac didn't generate any code for the do expression, but instead optimized it away because of the constant false test (it does the same for if and while statement tests). j2objc supports the same optimizations as javac. I'll fix that today.

The reason g() crashes is because that optimizing should replace the label's statement with an empty statement.

**Comment by lukhnos** [comment]
Thanks for pointing out what javac does under the hood, but in the `f()` example, the equivalent of `iload_1` does not happen in the translated Objective-C code. The body is not emitted (replace `x = 1` with something like a method invocation and the problem becomes more visible).

**Comment by tomball** [comment]
Got it -- the issue is specific to do statement bodies, which get executed once even if the test always fails. I'll re-review your pull request.
