### ISSUE TITLE
Avoiding slow check_protocol_cast

### ISSUE THREAD

**Issue by advayDev1** [google/j2objc#575]
I have a Java method that looks like:
```
simulateSomething();
for (Thing t : things) { ((OtherThing)t).doStuff(); }
```
It gets converted into ObjC that looks like:
```
  [self simulateSomething];
  for (Thing * __strong t in nil_chk(things_)) {
      [((id<OtherThing>) check_protocol_cast(t, @protocol(OtherThing))) doStuff];
    }
  }
```
The check_protocol_cast (really its callee class_conformsToProtocol) is, per the profiler*, incredibly slow - in fact the time spent in check_protocol_cast is 3x the time spent in the entire prior simulation.  Since class_conformsToProtocol spends nearly all of its cycles in __bsdthread_ctl, I assume it is some sort of runtime-lock while doing introspection.  Anyway, I see that j2objc has a [macro J2OBJC_DISABLE_CAST_CHECKS](https://github.com/google/j2objc/blob/a9ef85fff8c338c91a39dae001e512d5f36a46f6/jre_emul/Classes/J2ObjC_common.h#L119).  What's the recommended way to disable this check just for this tight loop but not for the rest of my code?

(*Time Profiling release code on a physical iPhone 6).

**Comment by advayDev1** [comment]
discussion: https://groups.google.com/forum/#!topic/j2objc-discuss/6pdpoIccNYs

**Comment by tomball** [comment]
Objective C's class_conformsToProtocol() is slow because its definition of conformance is that the class has methods implemented for all the selectors in a protocol. Java's instanceof for interfaces is faster because it checks that the interface is included in the list of interfaces defined by that class. What makes matters worse for both runtimes is that superclasses are checked when the current class isn't conformant. So code performance will always suffer if protocol checks are made in performance-critical code, and that code is hit harder on iOS.

**Comment by kstanger** [comment]
By the way, I actually rewrote our Class.isInstance() on protocol types a while back so that it doesn't call into class_conformsToProtocol(). This improved performance for our instanceof checks, and I'm surprised that I neglected to update our cast checks as well. I'll see if I can fix that. It won't be lightning fast, but will be an improvement.

Since check_protocol_cast is an inline method, you should be able to apply J2OBJC_DISABLE_CAST_CHECKS on compilation of the translated files doing the checks.

**Comment by advayDev1** [comment]
@kstanger  - Sweet, can you re-open this bug to track the change to casts?

I'm currently doing a hacky:
```
#define check_protocol_cast(a,b) ((a))
[expensive thing]
#undef check_protocol_cast
```
because defining J2OBJC_DISABLE_CAST_CHECKS around the expensive thing did not in fact work.  Haven't looked into why yet.

**Comment by kstanger** [comment]
Reopening to see if check_protocol_cast can be reimplemented in terms of isInstance(), which should be cheaper.

**Comment by kstanger** [comment]
Fixed in current source
https://github.com/google/j2objc/commit/87d6eed7175840dfc1a8a507e25e505fb1653d2a

**Comment by advayDev1** [comment]
neato thanks
