### ISSUE TITLE
Any best practice?

### ISSUE THREAD

**Issue by ex3ndr** [google/j2objc#578]
I have project based on j2objc: https://github.com/actorapp/actor-platform It become big enouth to feel pain because of it's size because of j2objc. We alswo use GWT for Web.

Main problems:
1) How to include to XCode as directory, but not like separate files. How to make it incremental? I tried for hours, but still can't understand how to use "external build project".

2) How to mix different sources for different runtimes? Perfect solution is excluding some classes from ObjC, GWT, Android or other runtimes (plain java, scala, etc...). Now i need to create several projects with complex dependency. This can be easily reduced if all sources will be in one-two projects.

Thank you!

**Comment by tomball** [comment]
J2ObjC is a translator and runtime, not a build tool. Its j2objc script is
designed to be as much of a plug-in replacement for javac, while j2objcc is
a thin wrapper around clang/cc. Build tools which work with either are
therefore good candidates for use when building projects using j2objc, but
we can't guarantee their use, nor can we fix bugs or correct deficiencies
in those tools. Our project works with Xcode and Make not because we
endorse them, but because they are already available on iOS development
system.

All I can suggest is that if a build tool doesn't work for your project,
try another. Gradle <http://gradle.org/> is widely used by Android
projects, and there is a Gradle plugin for J2ObjC
<https://github.com/j2objc-contrib/j2objc-gradle>. @rastaman
<https://github.com/rastaman> created a Maven plugin for J2ObjC
<https://github.com/codehaus-plexus/plexus-compiler/tree/master/plexus-compilers/plexus-compiler-j2objc>,
which has been accepted by the Maven team but AFAIK isn't part of a
released build yet. And @hemantasapkota
<https://github.com/hemantasapkota> created
a J2ObjC plugin for Eclipse
<https://github.com/hemantasapkota/j2objc-eclipse-plugin>.

Since your project's goal is to support many different build environments,
perhaps a cross-platform build system makes sense. CMake
<http://www.cmake.org/> and GYP <https://code.google.com/p/gyp/> are a
couple of open-source examples (Google's Chrome project uses GYP). These
systems tend to be difficult to set up initially, but can save lots of time
and frustration over the life of a project.

Finally, new open-source build systems include Buck <https://buckbuild.com/>,
Pants <https://pantsbuild.github.io/> and Bazel <http://bazel.io/>. I'm not
sure any of these can support all your project requirements today, but as
they are in active development, are worth watching.
<https://github.com/j2objc-contrib/j2objc-gradle>
