### ISSUE TITLE
Rename Class Files with prefixes

### ISSUE THREAD

**Issue by ex3ndr** [google/j2objc#582]
XCode gone wild when project have two files with same name in different folders.

**Comment by tomball** [comment]
That's the whole reason j2objc's default is to translate into subfolders (like java.util.List is translated as java/util/List.m). You have a few options:

* Rename one of the classes. This actually makes working on them easier, as having classes with the same name means you have to think about them more.
* Build one or more subsets of the classes into static library targets, which get linked into your app. Since the issue is that files are overwriting each other, building them separately and putting them into uniquely named archives allows them to all be linked into your app.
* Don't use Xcode. There are other build systems for iOS, such as Gradle for which there is a [J2ObjC plugin](http://j2objc.org/docs/Using-J2ObjC-with-Gradle.html).
