### ISSUE TITLE
0.9.8 Lambda not work in objective-c++.

### ISSUE THREAD

**Issue by w-rui** [google/j2objc#585]
Hello, I have tried new version today. I'm very excited when I saw support for Lambda. But when I download it and translate my code, Lambda goes wrong...

> For capturing lambdas, we create the classes at runtime using the same methods, but we need an instance and block for each lambda, as each lambda captures a potentially unique outer state. We end up creating one block per class which is wrapped in as a class method to retrieve and apply blocks:
```
^JavaLangInteger *(id _self, JavaLangInteger * a) {
  id (^block)() = objc_getAssociatedObject(_self, 0);
  return block(_self, a);
}
```

The code above is from `http://j2objc.org/blog/#lambdas-in-java-8---dysfunctional-interfaces`, and it only works in Objc, not in Objc++. For Objective-C++, code below works:
```
^JavaLangInteger *(id _self, JavaLangInteger * a) {
  id (^block)(...) = objc_getAssociatedObject(_self, 0);
  return block(_self, a);
}
```

A `...` is added to `id (^block)(...)`.

So my question is: is there any good way to solve my problem without switching all files from Objective-C++ to Objective-C?

**Comment by tomball** [comment]
The best and fastest solution is to fork our project, grep though the translator source to find "(^block)", conditionally print a "(...)" if generating Objective-C++, and make a pull request to contribute it to the project. I'm not being sarcastic here, as you were smart enough to isolate the problem quickly and come up with a small test to accurately reproduce the problem, so you're definitely capable enough of hacking the translator successfully. :-)

Otherwise, you'll need to wait until sometime next week, as Seth's on his way back to school.

**Comment by tomball** [comment]
I'll have a fix in a few days, if you'd rather wait.

**Comment by w-rui** [comment]
OK， thank you!

**Comment by tomball** [comment]
Fixed in current source.
