### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by kelvinjm** [google/j2objc#589]
Please consider this as a note, this project is really great and It looks like miracle to me that it works, however It's good to know maybe:

In some cases the result code is extremely slow in comparison to the original (**100 times and more**). As example, I can use scrypt key derivation function. Salsa20 algorithm in the following file is working really very slowly after the transformation: http://ge.tt/517ZIFC2/v/4 

The following transformed scrypt test code with recommended parameters (for mobile devices) takes about 120s on iPhone 4S. I can use a C implementation of scrypt that makes it in 300ms, but whole project backend is Java based so far and using j2objc also for this task would be much more comfortable.

**Test Java Eclipse Project + corresponding Xcode Project (j2objc 0.9.8.1):**
http://ge.tt/517ZIFC2/v/5

**Comment by tomball** [comment]
I don't know where you get the 100X slowdown, but suspect you aren't making a realistic comparison. Since you can't run Java on an iPhone 6 simulator, you aren't comparing code on the same system. Also, your project's scheme uses the Debug default, which builds unoptimized code. So you're comparing a simulator running unoptimized code against running Java directly, not a fair comparison.

If I compile on my Mac Book Pro on OS X **for both executables**, then I see that a j2objc app is 2.26X times slower than the Java version:

```sh
$ javac -d . bench/start.java bench/SCryptBench.java
$ java bench.start
Computing...
Process time: 210ms
$ j2objc -d . bench/start.java bench/SCryptBench.java
$ j2objcc -o bench bench/start.m bench/SCryptBench.m -I. -Os  # release optimization level
$ ./bench bench.start
Computing...
Process time: 475ms
```

This micro-benchmark is also problematic because [SecureRandom is really slow](http://stackoverflow.com/questions/137212/how-to-solve-performance-problem-with-java-securerandom). It's like slow for both Java and j2objc, but if you're trying to compare raw performance, it's best not to include unrelated issues like random number generation.
