### ISSUE TITLE
Request example for LoopTranslation Annotation

### ISSUE THREAD

**Issue by confile** [google/j2objc#594]
Please add some explaination and example when to use the LoopTranslation Annotation in the docs: 

 http://j2objc.org/docs/LoopTranslation.html

Thanks!

**Comment by confile** [comment]
@kstanger When should I use this translation?

**Comment by kstanger** [comment]
Probably never. If you expect your loop to throw ConcurrentModificationException, then the default translation (using ObjC fast enumeration) might execute more iterations before throwing.

The annotation allows you to force the more true-to-Java translation instead of using ObjC fast enumeration. But that will come at a performance cost, since we've optimized most java.util collections for fast enumeration. It would be useful if you ever encountered an issue with the fast enumeration translation, but I haven't seen any actual bugs from fast enumeration yet.

**Comment by confile** [comment]
thank you!
