### ISSUE TITLE
The method forLanguageTag(String) is undefined for the type Locale

### ISSUE THREAD

**Issue by confile** [google/j2objc#619]
I tried to do: 

```
Locale.forLanguageTag(locale);
```

but when I translate the code I get the following error: 

```
The method forLanguageTag(String) is undefined for the type Locale
```

**Comment by lukhnos** [comment]
I ran into the same problem before. It's a JDK 1.7 API, and it's only available on Android since API Level 21.

If you know your input, you can really just use one of the constructors: `Locale(language)`, `Locale(language, country)`, or `Locale(language, country, variant)`, or parse it on your own (perhaps through the help of [`+[NSLocale componentsFromLocaleIdentifier :]`](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSLocale_Class/#//apple_ref/occ/clm/NSLocale/componentsFromLocaleIdentifier:) then use the appropriate constructor.

**Comment by tomball** [comment]
I plan on syncing to the latest java.util Android source later this week.

**Comment by confile** [comment]
Sounds great thanks. So far I use this class to create a locale from a String like ``de_DE``: 

http://www.java2s.com/Code/Java/Data-Type/ConvertsaStringtoaLocale.htm

Note that there is a problem when you want to parse ``de-DE`` the method ``toLocale(String str)`` fails. 

So, I added the following on at the beginning of this method: 

```
      if (str.contains("-")) {
        String[] args = str.split("-");
        if (args.length > 2) {
          return new Locale(args[0], args[1], args[3]);
        }
        else if (args.length > 1) {
          return new Locale(args[0], args[1]);
        }
        else if (args.length == 1) {
          return new Locale(args[0]);
        }
      }
```

This works fine for me.

**Comment by lukhnos** [comment]
`de-DE` follows RFC 5646, and `de_DE` is a representation used historically by libraries (AFAIK), but even `Locale.forLanguageTag` won't parse the latter.

I think having the latest Android source in jre_emul is the best solution. The problem with `Locale`'s constructors is you can't specify script. So there's no way to use tags like `zh-Hant` or `zh-TW-Hant` because `Hant` (Traditional Chinese) is really a script, not a variant. `Locale.forLanguageTag` takes care of those cases.

**Comment by confile** [comment]
I know but ``Locale.toString()`` gives ``de_DE`` and in Swift:

```
println("NSLocale.currentLocale().localeIdentifier: \(NSLocale.currentLocale().localeIdentifier)")
```

the former returns: ``de_DE``

**Comment by tomball** [comment]
Fixed in latest source.

**Comment by confile** [comment]
@tomball thanks Tom

**Comment by khalilsam** [comment]
@confile  your code is working fine but there are is mistake in the first return ,the index of third parameter must be 2 and not 3 unless it will generate ArrayIndexOutOfBoundsException error
