### ISSUE TITLE
What the difference between jre_emul.a and jre_emul_core.a?

### ISSUE THREAD

**Issue by ex3ndr** [google/j2objc#626]
I am working on frameworked version of j2objc and useful cocoapod.
Basic jre_emul is too big to be placed on github, and just not useful because it's size. But jre_emul_core 2x times smaller and what does stripped in it?

**Comment by tomball** [comment]
jre_emul_core holds the subset needed to resolve translated Java sources that don't depend upon much of the JRE. One way to think of it is that it's the minimum library needed to support a hello-world example. Over time we'll be breaking out other JRE "chunks", such as XML support or advanced networking and security. We also plan on pulling out the android.* utility classes currently included in jre_emul but not actually part of the JRE.

Please note that you should never link with both libraries, since all the symbols in jre_emul_core are also in jre_emul.

**Comment by ex3ndr** [comment]
Do you have headers for jre_emule_core? What was stripped away?

**Comment by kstanger** [comment]
The headers are shared between jre_emul and jre_emul_core (in the /includes
directory of the distribution). In the future we will have better
documentation about which sources are included in jre_emul_core. For now
you can review the lists in our makefile:
https://github.com/google/j2objc/blob/master/jre_emul/java_sources.mk. Keep
in mind that the contents of jre_emul_core is still very much subject to
change and we expect to trim it down further.

**Comment by tomball** [comment]
We've been trying lately to sync our public repository with our internal
one more often, so there isn't as long a delay in getting bug fixes to
developers. Consequently, new functionality will often start showing up
before it's useful, finished or documented, just like in most other
projects. If that's causing anyone problems, please wait for releases and
ignore source commit messages.
