### ISSUE TITLE
Error in Translate to Objective- C

### ISSUE THREAD

**Issue by HosseinKurd** [google/j2objc#627]
there is Android Source I Need to translate to Objective C
CL Coomand in Android project (java files) Directory (and J2OBJC Directory):

    java -Xbootclasspath:$J2OBJC_HOME/lib/jre_emul.jar -jar $J2OBJC_HOME/lib/j2objc.jar j2objcc

but it shows error :

    Invalid layout of java.lang.String at value

    A fatal error has been detected by the Java Runtime Environment:

     Internal Error (javaClasses.cpp:127), pid=575, tid=4867

     fatal error: Invalid layout of preloaded class

    JRE version:  (8.0_51-b16) (build )

    Java VM: Java HotSpot(TM) 64-Bit Server VM (25.51-b03 mixed mode bsd-amd64 compressed oops)

    Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

    An error report file with more information is saved as:

    /Users/emaar/AndroidStudioProjects/TestBuild/app/src/main/java/com/emaar/app/testbuild/hs_err_pid575.log
      If you would like to submit a bug report, please visit:

      http://bugreport.java.com/bugreport/crash.jsp
      Abort trap: 6

any things set (JDK 8, Maven, SDK, Android Studio, Gradle, J2OBJC, ...)

how to solve it ?

**Comment by tomball** [comment]
j2objcc is not a Java source file. Run your command without that last argument to see what the valid flags and parameters are.

FWIW, that doesn't look like the dump from a Mac JVM. Since j2objc is a pure-Java app, in theory it should run on any JVM. However, we have no experience with, and can't support other platforms. Compilation of j2objc-translated files needs to be done on a Mac, since they depend on the iOS SDK, which has a license that restricts its use to Macs.
