### ISSUE TITLE
Translation of javax.net.ssl.X509KeyManager

### ISSUE THREAD

**Issue by olexl** [google/j2objc#633]
Can you add this class to internally translated files?

**Comment by tomball** [comment]
Sure, but why? It's just an interface, so you'll very likely need an implementation, which will require security support that isn't implemented. Since networking and security in iOS is very different than on Android, it's not something we'll be able to provide soon. 

I recommend that you instead define whatever common SSL interface your app needs, then implement it natively for iOS.

**Comment by antonio-cortes-perez** [comment]
Fixed in latest releases.
