### ISSUE TITLE
Dummy loops elimination

### ISSUE THREAD

**Issue by olexl** [google/j2objc#635]
I have 3rd party Java code that contains dummy loops in the following format:
```java
do {
    //some code
    if (...) {
        if (...) {
            break;
        }
        //some code
    } else if (...) {
        if (...) {
            break;
        }
        //some code
    } else {
    }
} while (false);
```
After J2ObjC translates such code into Objective-C, loops disappear. But 'break' statements do not which causes an error during compilation. Can you suggest how to run J2ObjC so that dummy loops (at least with 'break') are preserved?

**Comment by gg8** [comment]
I would like to second this issue.  I have a lot of Java code written this way, causing the Objective-C build to fail.  Is there any workaround for this (other than re-writing the Java code), or an idea if/when this (preserving dummy loops with "break") might be supported with J2ObjC?

**Comment by tomball** [comment]
Keith is working on this now.

For future translation issues, the best "workaround" is to fix the issue
and submit a pull request. The j2objc translator is 100% Java and pretty
easy to understand, especially since it works with a model of the Java
language. Other community members who were initially intimidated by working
on a compiler but investigated issues quickly found that it's relatively
easy (and fun!) to make small changes to it. Often the hardest part is
writing a small test for the problem, which @olexl already did here.

**Comment by olexl** [comment]
@gg8 as a temporary solution you can use a simple rewrite of the Java code. At least it helped me.
```java
boolean dummyLoop = false;
do {
    //...
} while (dummyLoop);
```

**Comment by tomball** [comment]
We should have a fix pushed early next week.

**Comment by gg8** [comment]
@tomball: Great, thank you!  I will take your suggestion of digging into the compiler code for future issues as well.

@olexl: Great suggestion!  Looks like that will work well for me in the short term.  Thanks.

**Comment by kstanger** [comment]
[Fixed in latest source.](https://github.com/google/j2objc/commit/cbe46e88123e19decbad231c8f6cca20e10ed10a)

**Comment by gg8** [comment]
@kstanger - Great, thanks!
