### ISSUE TITLE
Jackson deserialization failed when using Generic Types in an embedded list

### ISSUE THREAD

**Issue by saruye** [google/j2objc#639]
When using translated jackson, it cannot deserialize objects with embedded lists.

The java test passes while the objective-c tests fails when deserializing. Serializing works.

    public static class Person {
        private ArrayList<Address> addressList;
    }

When deserializing such an object the result is a person with an arraylist filled with LinkedHashMaps.

A test is provided here: https://github.com/j2objc-contrib/j2objc-common-libs-e2e-test/pull/50

**Comment by kstanger** [comment]
It sounds like this may boil down to a bug in our reflection support. You
can help us by identifying the specific J2ObjC issue and posting a simple
test case. Tom and I are usually very fast at fixing issues when there is a
simple test case.

**Comment by saruye** [comment]
@kstanger there is a test case in the pull request mentioned above. This requires building jackson though. I can try to create a test case that fails without it tomorrow.

**Comment by tomball** [comment]
Please retry with current source -- I just fixed problems serializing exception and number wrapper classes.

**Comment by saruye** [comment]
I tried with my test in the j2objc-e2e project and it seems to work. thanks a lot! I think the ticket can be closed.

**Comment by tomball** [comment]
Woohoo! I didn't want to debug all of Jackson if I could avoid it. :-)

**Comment by superarne** [comment]
I did try to debug the java code and find complicated looking parts to write unit tests that prove this bug without jackson... but I didn't find anything. So really glad you fixed it without this!! Thanks again :)

**Comment by taptilegames** [comment]
Has there been any update on this please? I appear to be having exactly the same problem with

create_ComFasterxmlJacksonAnnotationJsonSubTypes_Type (referred to in 7 places, e.g.

return [IOSObjectArray newArrayWithObjects:(id[]){ create_ComFasterxmlJacksonAnnotationJsonTypeInfo(ComFasterxmlJacksonAnnotationJsonTypeInfo_None_class_(), JreLoadEnum(ComFasterxmlJacksonAnnotationJsonTypeInfo_As, PROPERTY), @"type", JreLoadEnum(ComFasterxmlJacksonAnnotationJsonTypeInfo_Id, NAME), false), create_ComFasterxmlJacksonAnnotationJsonSubTypes([IOSObjectArray newArrayWithObjects:(id[]){ create_ComFasterxmlJacksonAnnotationJsonSubTypes_Type(@"ITEM", ComRedbiteItemitEntityDocumentRelatedItemSource_class_()), create_ComFasterxmlJacksonAnnotationJsonSubTypes_Type(@"COLLECTION", ComRedbiteItemitEntityDocumentRelatedCollectionSource_class_()), create_ComFasterxmlJacksonAnnotationJsonSubTypes_Type(@"LOCATION", ComRedbiteItemitEntityDocumentRelatedLocationSource_class_()) } count:3 type:ComFasterxmlJacksonAnnotationJsonSubTypes_Type_class_()]) } count:2 type:JavaLangAnnotationAnnotation_class_()];

Amongst other things, I can see the following declared in JsonTypeInfo.m:

id create_ComFasterxmlJacksonAnnotationJsonTypeInfo(IOSClass *defaultImpl, ComFasterxmlJacksonAnnotationJsonTypeInfo_As *include, NSString *property, ComFasterxmlJacksonAnnotationJsonTypeInfo_Id *use, jboolean visible)…
J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationJsonTypeInfo)
J2OBJC_INITIALIZED_DEFN(ComFasterxmlJacksonAnnotationJsonTypeInfo_Id)

I can return nil to get through these to avoid the compile errors (although I’ve got some missing date classes from other dependencies from ThreeTen to work through, so I can’t categorically confirm whether more will come out the woodwork before I get a success). However, I suspect that’s not the solution I actually want.

I did notice there was a J2Objc continuous integration project for Jackson, but they seem to have given up at 2.1.1.9.2 . https://github.com/Dash-Labs/jackson-annotations-objc/tree/master/src/com/fasterxml/jackson/annotation . I’m not clear whether they just lost interest, or whether something fundamentally changed in Jackson that broke their toolchain.

I'm using 2.6.0 for all 3 libraries (annotations, core, databinding), but have also tried 2.2.2 and it was broken in the same way. The other developer requires at least 2.3.0 in order to have a suitably powerful JSONSchema validation tool, and this is core to our requirements.

I’m not 100% clear on what the macros achieve, but I’m guessing something to do with creating a class that wraps an enum? I realise that Java enums essentially become both a class and an enum in an inevitably horrific way as a result of enums being able to behave like classes in Java but just being integers in ObjC). I’d be keen to get a little help in terms of understanding how these macros as intended to work and how to replicate their behaviour. My hopelessly optimistic brain hopes this is something trivial like putting a J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE or J2OBJC_INITIALIZED_DEFN in a .h (or .pch) but I’m fully ready for you to shatter my illusion ;-)

Would appreciate any help with this, as right now, our options seem to be:

    Fudge in the missing macros and hope it works reliably
    Drop Jackson (lots of re-work from another developer)
    Using interfaces, so a fairly large piece of work using use SBJSON for iOS and Jackson for Android/web/server-side
    All of which look pretty grim to me.

Note: For Google Groups, I’m andy33@gmail.com - you replied to my post about java.nio.file the other day

Happy to upload some source, although this web page is preventing me from uploading source code/archives.

**Comment by tomball** [comment]
Good news: you only forgot to run j2objc on the jackson-annotations source (it's not distributed with the j2objc release bundle). Here are the steps:

1. Locate the jackson-annotations source jar. I used [Maven Central](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.fasterxml.jackson.core%22%20AND%20a%3A%22jackson-annotations%22), found version 2.6.0 and clicked its sources.jar link.
1. `j2objc jackson-annotations-2.6.0-sources.jar` to create the Objective C version.
1. `libtool -static -o libjackson-annotations.a *.o` to create a static library (libtool will complain that package-info.o is empty, so either delete it first or ignore the warning).
1. Add this directory to the include paths for the compiler step that is failing. In Xcode, that would be your target's "User Header Search Paths" build setting.
1. Add `-l jackson-annotations` to your link flags. In Xcode, that's the Other Linker Flags build setting.
