### ISSUE TITLE
Child classes extending Serializable classes aren't considered serializable

### ISSUE THREAD

**Issue by Toinouze** [google/j2objc#652]
j2objc version : 0.9.8.2.1

    public void myMethod(Serializable myParam) {
        ...
    }
    
    Long myLong = 10L;
    myMethod(myLong);

This code does not compile with j2objc.

    The method myMethod(Serializable) in the type (...) is not applicable for the arguments (Long)

Moreover, at runtime : 
    
    (myLong instanceof Serializable)

returns false with j2objc. 

Any ideas?

Thanks.

**Comment by tomball** [comment]
[This is fixed](https://github.com/google/j2objc/commit/e6de6b4bda3b2cd65b2f47ffc4a043674ef4a2d2) in the current source. The issue was that the stub class for java.lang.Number wasn't declared as implementing Serializable, even though its native mapping did. That meant that translation would fail, but checking at runtime whether a Long was Serializable worked.
