### ISSUE TITLE
Unexpected EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000001

### ISSUE THREAD

**Issue by sadevelopment** [google/j2objc#656]
Hi,

Using: j2ObjC v 0.9.8.2.1

We are getting the following stack trace and are unable to figure the cause:

Thread : Crashed: main
0  libsystem_platform.dylib       6795168900 _platform_strcmp + 20
1  DriverApp                      4303493800 -[JavaClassMetadata findMethodInfo:] + 772
2  DriverApp                      4303493800 -[JavaClassMetadata findMethodInfo:] + 772
3  DriverApp                      4303493868 -[JavaClassMetadata findMethodMetadata:] + 840
4  DriverApp                      4303462072 __46-[IOSConcreteClass collectMethods:publicOnly:]_block_invoke + 2180
5  DriverApp                      4303464020 CreateMethodWrappers + 1740
6  DriverApp                      4303461864 CollectMethodsOrConstructors + 1972
7  DriverApp                      4303461756 -[IOSConcreteClass collectMethods:publicOnly:] + 1864
8  DriverApp                      4303446468 -[IOSClass getDeclaredMethods] + 2928

Any pointers would be much appreciated.

Regards,

Marcus Smith

**Comment by tomball** [comment]
The 0x1 address is generally a returned NULL that was incremented, so a NULL test looks to be missing. In [findMethodInfo:](https://github.com/google/j2objc/blob/master/jre_emul/Classes/JavaMetadata.m#L77), the likeliest source of this bad address is `name`, since the `data_` field is constant (it's from the __metadata structure in each .m file generated by the translator).

Reading the doc for [NSString's defaultCStringEncoding](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSString_Class/#//apple_ref/occ/clm/NSString/defaultCStringEncoding), it appears it should rarely be used. Try replacing it with `NSUTF8StringEncoding`.

Another thing to try is adding a NULL check:

    - (const J2ObjcMethodInfo *)findMethodInfo:(NSString *)methodName {
      const char *name = [methodName cStringUsingEncoding:[NSString defaultCStringEncoding]];
      if (name) {
        for (int i = 0; i < data_->methodCount; i++) {
          if (strcmp(name, data_->methods[i].selector) == 0) {
            return &data_->methods[i];
          }
        }
      }
      return nil;
    }

Please let us know if either works. If neither helps, please cut&paste the __metadata structure from the  .m file of the translated class that's failing.

**Comment by sadevelopment** [comment]
Hi Tom,

Solved. We had some handcrafted classes that have been fine until we upgraded our j2objc, the structure of the meta info had changed and we had not updated. All sorted now thanks.

**Comment by tomball** [comment]
Thanks for the feedback, and I'm glad it's working for you now.
