### ISSUE TITLE
Deserialisation wrongly calling default constructor

### ISSUE THREAD

**Issue by nbransby** [google/j2objc#657]
http://stackoverflow.com/a/2904589/737857

This is not the case in translated code, the init method is called

**Comment by tomball** [comment]
Good catch -- happily Objective-C separates object instantiation (alloc) from initialization.

**Comment by tomball** [comment]
Fixed in [d2fedb9234af0e3d22347441f08abb84c2d3b454](https://github.com/google/j2objc/commit/d2fedb9234af0e3d22347441f08abb84c2d3b454).

This exposed that Throwable serialization was broken, fixed in [3a5082e7691f3026e73bea8e8ac0706a57a815fa](https://github.com/google/j2objc/commit/3a5082e7691f3026e73bea8e8ac0706a57a815fa).
