### ISSUE TITLE
Implement java.nio.file

### ISSUE THREAD

**Issue by eapache** [google/j2objc#659]
Trying to use Okio (https://github.com/square/okio) fails because it makes use of `java.nio.file` which is, as far as I can tell (?) not implemented by j2objc. Build fails with:

```
  error: okio/Okio.java:28: The import java.nio.file cannot be resolved
  error: okio/Okio.java:29: The import java.nio.file cannot be resolved
  error: okio/Okio.java:30: The import java.nio.file cannot be resolved
```

What kind of effort would it be to implement this? I'm open to doing it myself and submitting a PR if it would only be a few days work.

cc @boourns @carsonb

**Comment by tomball** [comment]
java.nio.file isn't supported by Android, which is what j2objc's JRE source is based on. We don't plan on implementing that package partly because of the lack of portability, as well as how limited the iOS file system is.

However, Android uses OkHttp and Okio. To support Okio, [they just commented out the okio.Okio source and sink methods that take a java.nio.file.Path parameter](https://android.googlesource.com/platform/external/okhttp/+/master/okio/okio/src/main/java/okio/Okio.java). If you avoid these methods in your project's code, it will be easier to port to Android.
