### ISSUE TITLE
"make frameworks" fails for macosx only J2OBJC_ARCHS

### ISSUE THREAD

**Issue by astrotuna201** [google/j2objc#663]
the generation of frameworks (not static libraries) fails using the new "make frameworks" option ...

When J2OBJC_ARCHS is set to the default 
"J2OBJC_ARCHS = macosx iphone iphone64 iphonev7s simulator simulator64" (in common.mk),

the frameworks are assembled, but only include non- maxosx architectures

if J2OBJC_ARCHS is set to 
J2OBJC_ARCHS = macosx

the frameworks are not assembled at all (because presumably the Makefile is looking for the iOS & Simulator static libs.

**Comment by kstanger** [comment]
This may be working as intended since there's no need for a OSX framework. (the OSX build is mainly used for running unit tests) I'll let Tomm comment on this.

**Comment by tomball** [comment]
Yes, the issue is that 64-bit iOS emulator and OS X archs can't be put in the same fat library, since they're both x86_64. Since j2objc is iOS focused, having separate OS X frameworks wasn't considered.

That said, we wouldn't ignore a pull request to add make support for a separate OS X framework, as long as it doesn't break the iOS build. ;-)
