### ISSUE TITLE
Enum values aren't available until initialize or values method isn't called or it wasn't referenced from Java source

### ISSUE THREAD

**Issue by efpies** [google/j2objc#669]
I'm using 0.9.8.2.1

So I have enum class `MarkerSideEnum` and it has values `MarkerSide_LEFT` and `MarkerSide_RIGHT` (which are defines to MarkerSideEnum_values_ array elements).

If I use these defines in my ObjC code, they aren't available until this array is initialized. It happens in `[MarkerSideEnum initialize]` or `[MarkerSideEnum values]`. It seems they aren't called until they're used in Java code or called explicitly. I set a breakpoint, and it seems that Java code translates into macro `JreLoadStatic(MarkerSideEnum, RIGHT)` which causes the array to initialize. Before this method is called, this macro substitutes `nil`.

I guess, it's a bug? Unless I should use `JreLoadStatic` to get enum objects I need.

**Comment by efpies** [comment]
If it really works as intended, what is the correct way to get the Enum object? Documentation states that there should be static accessors (http://j2objc.org/docs/Enum-Translation.html) like `+ (MarkerSideEnum *)LEFT`, but that's not the case. And if I will use `+ (MarkerSideEnum *)valueOfWithNSString:(NSString *)name`, it won't be safe in case if the Java source will change.

**Comment by tomball** [comment]
It's obscure because each Java enum class creates both a C enum and an Objective C enum class. To separately reference the two, the C enum has the name of the Java enum, while the Objective C class has the name plus "Enum". So "MarkerSide" native references refer to the C enum, while "MarkerSideEnum" native references are to the class.

The C enum is always set by the compiler, so MarkerSide_LEFT and MarkerSide_RIGHT are always defined. It sounds like you want the enum constants as objects, though, so you should use MarkerSideEnum_LEFT() and MarkerSideEnum_RIGHT(). It's not obvious, but these are created by the [J2OBJC_ENUM_CONSTANT_GETTER](https://github.com/google/j2objc/blob/master/jre_emul/Classes/J2ObjC_common.h#L348) macros in the .h file.

We're working on removing all macros that define public API from our headers, while hopefully will eliminate this confusion.

**Comment by tomball** [comment]
To get the accessor methods, use the translator's --static-accessor-methods
flag. Static accessors are now defined as C functions, which are faster
than Objective C methods. Generating static accessor methods also makes the
app larger, so they're off by default.

**Comment by efpies** [comment]
Thanks for detailed response. I totally missed constant getters in header file.

**Comment by tomball** [comment]
That's why we need to replace the J2OBJC_ENUM_CONSTANT_GETTER uses in generated headers with actual declarations. :-)

**Comment by kstanger** [comment]
We now have documentation on how to access fields, methods, etc. from
generated classes: http://j2objc.org/docs/Translation-Reference.html#enums
Like Tom said, we have some work to do to make the correct usage more
obvious when looking at the headers.
