### ISSUE TITLE
Add iOS security provider for SSL (to be returned by SSLContext.getInstance()).

### ISSUE THREAD

**Issue by gistya** [google/j2objc#679]
In SSLContext.H, the method  JavaxNetSslSSLContext_getInstanceWithNSString_: fails with the JavaSecurityNoSuchAlgorithmException for "TLS" and "TSLv1.2" strings, which should be supported, on iOS 9.2. Anybody know why? The stack trace has JavaSecurityNoSuchAlgorithmException with OrgApacheHarmonySecurityFortressEngine_notFoundWithNSString_withNSString_ at the top.

**Comment by tomball** [comment]
There needs to be an iOS security provider for SSL, which hasn't been implemented. The problem is that the unimplemented providers all depend on each other, so it's a huge wad of code that must work perfectly on the first draft. 

If anyone has security experience, we'd love help on this -- the actual security support is in the iOS Security Framework, so it's a matter of correctly mapping Java's requirements to the Security Framework's capabilities.

**Comment by gistya** [comment]
Maybe there's a way to do this, but it would have to be done at a low level, and I'm not sure how to approach that yet. One of the problems is that Java's API for SSL over HTTP allows for some security exceptions (like ignoring hostname mismatch) that cannot be done on iOS with NSURLSession due to Apple's tighter security restrictions. So I don't know that a direct mapping is even possible without relying on Core Foundation HTTP methods, which are now deprecated. There are a lot of problems caused by these new restrictions for people networking with devices over LANs (where they are just using Ethernet as, essentially, a glorified serial port, but they have to use HTTPS to be PCI-compliant, etc.). Apple's Application Transport Security restrictions on iOS 9 by default require forward secrecy and hostname matching etc., and there's no way to programmatically get around that. Even if you disable ATS, you still can't turn off hostname matching.

**Comment by tomball** [comment]
I suggest asking on StackOverflow, as this sounds like an iOS issue independent of what language the app is written in. A J2ObjC hack isn't an option here, as we can't offer a weaker security model that what Apple provides. My guess is you aren't the first developer affected by these new restrictions, though, so hopefully workarounds are starting to surface or Apple will soon realize the error of their ways.

**Comment by alexander-larsson** [comment]
I saw this issue an I thought that is is probably the best place to ask this question.

I'm working on an app that constantly trows this exception on every single call to the API. But it seems like that does not matter since if I run the app on the emulator and check the traffic in WireShark it is all sent using TLSv1.2. How is this possible?

I can just comment out all the code (in the generated Obj-C) related to this call and it still works. If you do the same on Android (in the Java source), it fails. Is there som kind of "quick fix" involved that makes this work?

**Comment by antonio-cortes-perez** [comment]
A basic SSL socket client was implemented in version J2ObjC 2.3. Please open a new issue if more functionality is required. Also, please consider contributing to this effort.
