### ISSUE TITLE
Add Provider  "SunRsaSign" 

### ISSUE THREAD

**Issue by MaleBug** [google/j2objc#695]
Hi, 
    First of all great job on  providing us with this helpful tool.  Is it possible to add/register other Java Cryptography Architecture e.g. "SunRsaSign" in j2objc? Currently i need to validate a public key created from it.  Thanks it advance.  :)

**Comment by tomball** [comment]
You can register other security providers like you can do with Java apps, such as with java.security.Security.addProvider(Provider). We hope to support SunRsaSign as we'll soon be upgrading our runtime to the Android version based on OpenJDK. However, replacing a runtime is a very big task, so we can't provide any schedule. 

In the meantime, I recommend using native code [as described here](http://stackoverflow.com/questions/21724337/signing-and-verifying-on-ios-using-rsa). Basically, if SHA256 w/RSA works for you then iOS directly supports it, otherwise you'll need to link in OpenSSL (google for instructions or a pre-built library).

**Comment by MaleBug** [comment]
Hi tom,
    Thank you for your reply and recommendation.  Will be looking forward for this feature to be included  in the future :)
