### ISSUE TITLE
If I'm using Hindi numbers on my Mac preferences, the translated source has Hindi numbers.

### ISSUE THREAD

**Issue by eddydas** [google/j2objc#698]
If I'm using Hindi numbers on my Mac preference pane, the translated source has Hindi numbers.

![screen shot - - at](https://cloud.githubusercontent.com/assets/2492409/12744405/70480208-c9d7-11e5-9061-d2fe92d7ba7d.png)

+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[JavaLangAnnotationRetention alloc] initWithValue:JavaLangAnnotationRetentionPolicyEnum_get_RUNTIME()] autorelease], [[[JavaLangAnnotationTarget alloc] initWithValue:[IOSObjectArray arrayWithObjects:(id[]) { JavaLangAnnotationElementTypeEnum_get_METHOD() } count:१ type:NSObject_class_()]] autorelease], [[[JavaLangAnnotationDocumented alloc] init] autorelease] } count:३ type:JavaLangAnnotationAnnotation_class_()];
}

**Comment by tomball** [comment]
What version of OS X are you using? I'm running 10.11.3 (El Capitan), and my Language & Region preferences panel doesn't have a Numbers option. This should be simple to fix, but I'm not sure how to test a solution.

**Comment by tomball** [comment]
Do you have a [j2objc build](http://j2objc.org/docs/Building-J2ObjC.html)? If so, please try changing [SourceBuilder.printf()](https://github.com/google/j2objc/blob/master/translator/src/main/java/com/google/devtools/j2objc/gen/SourceBuilder.java#L100) from:

    print(String.format(format, args));

to:

    print(String.format(Locale.ROOT, format, args));

This changes the formatter used when generating source files to use the default locale. Since the translator's use only affects number formatting, this should fix this problem without making any other changes.

**Comment by eddydas** [comment]
Sorry for replying late. If you choose some specific locales (e.g. "India - Hindi" in my case), it will let you choose an alternate numbering system. The "- Hindi" part is hidden inside the "Advanced" button.

And no sorry I don't have a j2objc build. Thanks a lot for fixing this in such a promptly manner!
