### ISSUE TITLE
[performance] Array Operations are extremely slow

### ISSUE THREAD

**Issue by ex3ndr** [google/j2objc#720]
We are using java-based crypto libraries and they works extremely slow in j2objc. 90% of time in encryption is reading and writing to arrays and such simple operation takes a lot of time unlike plain objc implementation. Especially IOSLongArray_Get is very slow.

**Comment by tomball** [comment]
Crypto code has to do *lots* of number calculating and array accesses, as otherwise the plaintext would be trivial to decode. My hunch is that range-checking is slowing your code down, since IOSLongArray_Get() is an inlined function that just checks the range and then returns the indexed element using a straight C array dereference. You can turn off index-checking by defining J2OBJC_DISABLE_ARRAY_BOUND_CHECKS, though doing so for the whole j2objc runtime is obviously risky.

I haven't tried this, but since both IOSLongArray_Get() and IOSArray_checkIndex() are inlined functions, it should be possible to disable range checking in just one Java source by adding this near the top of the file (such as after the imports and before the class declaration):

    /*-[
    #define J2OBJC_DISABLE_ARRAY_BOUND_CHECKS 1
    ]-*/

This JNI block will be added to the generated .m file for the Java source, so it won't affect classes that #include the .h for this Java file.

Another area to investigate (once range-checking is disabled) is whether performance is an issue on all platforms, or just 32-bit or 64-bit ones. Since j2objc generates arch-independent code, we can't help with platform-specific issues, but if that's an issue it's likely that there are related discussions on StackOverflow for ways to speed up C code on specific iOS platforms.

If you want us to investigate this further, please reopen this issue with a micro-benchmark that demonstrates the problem.

**Comment by ex3ndr** [comment]
Thank you @tomball J2OBJC_DISABLE_ARRAY_BOUND_CHECKS speeds up my encryption ~100x times!

**Comment by tomball** [comment]
That's great news, I'm glad you're unblocked.

**Comment by robotan0921** [comment]
hi, there.

I translate Java module to Obj-c using j2objc (ver 2.5) and run it on iOS device, but it was much slower than that on Android device. 
I thought that this loss of performance was happened because the module calculates many matrixes such as Quaternion or RotationMatrix.

I tried this workaround, but its performance didn't improve.
`#define J2OBJC_DISABLE_ARRAY_BOUND_CHECKS 1`

Can you tell me if you know other workarounds to improve array operation performance?
Thank you in advance.

**Comment by tomball** [comment]
Two-dimensional (or greater) arrays are slower, because the Java spec is that they be object arrays of arrays. To access a cell in a two-dimensional matrix, it therefore takes an Objective C call to fetch the inner array, then accessing the inner element. Objective C messages are slower than Java method calls since Objective C is more dynamic.

The biggest speed improvement, therefore, is to flatten the multiple dimensions into a single dimension array. For a 6 x 6 matrix, for example, a 36 element array is used, and element(x, y) is found using (6 * x) + y. Primitive arrays are slightly faster, too, as Objective C retain/release messages aren't sent to the elements as they are added or removed.

I don't know of any, but suspect there are several Java matrix libraries that provide this optimization.

**Comment by robotan0921** [comment]
@tomball , thank you so mush for your help!
