### ISSUE TITLE
android package name problem

### ISSUE THREAD

**Issue by kornale** [google/j2objc#721]
Hi,

I have a versimple java class:

`package android;`
`public class TestClass {`
`}`

My command line is as follow:

j2objc --no-package-directories TestClass.java

I would have expected no package directions, but the TestClass.m file looks like this:

`#include "J2ObjC_source.h"`
`#include "android/TestClass.h"`

`@implementation AndroidTestClass`
`...`

The code can not be compiled because it did not create the TestClass.h in the android directory but the include statement expects it to be in the android directory.

If I change the package to android2 everything is working properly. What is the special deal with android packages? What did I miss?

Many thanks
Alexander

**Comment by tomball** [comment]
The Android API contains classes from the Java runtime, plus a number of new packages that all start with "android.". Since j2objc supports a few Android utility classes and needs to find them in its include path, packages starting with "android." are ignored by the --no-package-directories flag, just like packages that start with "java." and "javax." are.

[The recommendation for Java package names](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html) is to instead reverse your company's domain name.

**Comment by kornale** [comment]
Thanks for the answer.
If I can't use the --no-package-directories flag, then I have problems with the Output Files in the build rule of Xcode. In the documentation it's written that I should put ${DERIVED_FILES_DIR}/${INPUT_FILE_BASE}.m and ${DERIVED_FILES_DIR}/${INPUT_FILE_BASE}.h in the Output Files sections. But this will not work if the files are stored in different directories, based on the package name. Do you have any advise for that?

**Comment by tomball** [comment]
If you have your own source files with packages that start with "android.*" then rename those packages since the Android team reserves all such names for itself. 

If you are trying to transpile source files from the Android repository, then you'll need to define an external build step for them. The `j2objc build` target in [JreEmulation.xcodeproj](https://github.com/google/j2objc/tree/master/jre_emul/JreEmulation.xcodeproj) is an example of an Xcode target running Make to build a library. The [j2objc/make](https://github.com/google/j2objc/tree/master/make) directory has support files to simplify library building using Make; [j2objc/jsr305/Makefile](https://github.com/google/j2objc/blob/master/jsr305/Makefile) is an example of their use.

However, most android.* classes have dependencies on the Android OS and UI, so it's unlikely you'll be able to successfully translate them (j2objc is designed to translate platform-independent code). In that case, define an interface for your app's use of the Android API, then implement it using the Android API for your Android app build, and separately implement that interface on iOS. This is a common way to share Java code across multiple platforms, regardless of whether any of that code get translated.
