### ISSUE TITLE
Missing Override.{m,h}

### ISSUE THREAD

**Issue by Buggaboo** [google/j2objc#732]
Hi,

I noticed that since release 0.9.8.2.1, that the `java.lang.Override` is missing as translated j2objc source files. I'm doing a project where one of my dependencies relies on these files based on `Override.java` that is housed in `jre_emul`.

I haven't seen any explicit attempts to remove the translation in the git logs, why is it missing?

**Comment by tomball** [comment]
It's there -- I just downloaded that release, unzipped it, and there was include/java/lang/Override.h. Be sure to only include the distribution_directory/include in your project's header include paths, not distribution_directory/include/java/lang/.

**Comment by Buggaboo** [comment]
Hi,

I meant to say since release 1.0.1, it's been missing. It's in 0.9.8.2.1. It's also missing from my git builds.
I compile with `make dist frameworks`, I thought that would do the trick, but it doesn't translate `Overide.java`.

**Comment by Buggaboo** [comment]
After some investigation, I think I found the culprit: commit 109f855b
Something about SOURCE_RETENTION_ANNOTATIONS.

**Comment by Buggaboo** [comment]
Instead of blacklisting these types (e.g. Override.java, Generated.java...), how about stubbing them, so that projects that rely on these would actually transpile?

**Comment by tomball** [comment]
Now I understand. @Override is a source annotation, meaning it's only used
by the compiler and never the runtime, like CLASS and RUNTIME annotations
are. We incorrectly translated source annotations previously, but for 1.0
stopped doing so since they just make apps bigger while adding no value.

My guess is that you are trying to reuse source files translated with 0.9.*
with the 1.0 runtime, which we never recommend. Instead, we recommend that
you treat j2objc as a compiler, and so recompile whenever you build your
app. The generated Objective C sources should only be treated as a
temporary build artifact. We hope sometime in the future to stop generating
Objective C source files, and instead generate .o object files directly.
