### ISSUE TITLE
Naming convention in new J2ObjC changed?

### ISSUE THREAD

**Issue by DxTr0412** [google/j2objc#747]
Hi

Earlier all the variables and constants were translated with _ in the added but now I tried with the latest compiler, variable names were without _ this time and I faced lots of problems as I used all the variables with _ appended. 

Is there a way I can define the variable name as per my requirement? 

Thanks in advance.

**Comment by kstanger** [comment]
The naming convention was updated prior to the 1.0 release. Read [this discussion](https://groups.google.com/d/topic/j2objc-discuss/ypNJtQI7du4/discussion) for more details. If the naming change is a large amount of work for you, then there is a migration path by syncing to a particular commit. We plan to keep the generated API much more stable going forward past 1.0.

Note - one of the naming changes mentioned in the linked discussion, changing the inner class delimiter, was reverted because the "$" character causes trouble with xcode. So if you choose to follow the migration path avoid making that change in your code.

**Comment by DxTr0412** [comment]
Thank you very much, will surely do the same.
