### ISSUE TITLE
Bad access crash IOSObjectArray arraycopy:destination:dstOffset:length:

### ISSUE THREAD

**Issue by kingxt** [google/j2objc#750]
![img_3270](https://cloud.githubusercontent.com/assets/2328454/15454923/1e27346a-2078-11e6-8c8a-3868989f4f55.JPG)
![img_3271](https://cloud.githubusercontent.com/assets/2328454/15454924/1f5937c0-2078-11e6-8194-7ca66e2ed616.JPG)

My app crash at JavaUtilArrayList.add() function occasionally running with iphone5, but it is ok when running with iphone5s iphone6, 6plus,and later. I do not known why. I guess it 32bit for the reason, but i cannot reproduce it.

**Comment by tomball** [comment]
That 0x8008000c looks like a bad address. That can happen if the ArrayList
was dealloc'd but your app still used it, because once the memory block
released and reused, anything can be written to that location. It can also
be difficult to reproduce, because it depends on the when and how the heap
reuses that memory. Perhaps it happens on an iPhone 5 because it has less
memory than those other devices, and so memory gets reused faster.

Deallocated objects that are still treated as "alive" are called zombies,
and the Xcode instruments has a profiling template called Zombies. Try
profiling your app with this template, on an iPhone 5 (or that simulator),
and hopefully it will report any zombies.

**Comment by kingxt** [comment]
ok, thanks very much, I will profiling the problem with zombies.

**Comment by tomball** [comment]
Unable to reproduce. If you have a test that demonstrates this (can't find GroupChatConvoListFetcher source), please attach and reopen.
