### ISSUE TITLE
KXml2 missing headers

### ISSUE THREAD

**Issue by kyrylo-kolodiazhnyi-td** [google/j2objc#754]
Hi, my code depends from KXmlParser and KXmlSerializer classes, but corresponding headers files were removed from release packages for versions 1.0.1 and 1.0.2. Why it was done? And is there only way to resolve this issue manually translate corresponding java files and put headers to j2objc/include directory?

**Comment by Buggaboo** [comment]
It's on the git repository: ./jre_emul/android/libcore/xml/src/main/java/org/kxml2/io/KXmlParser.java

You are probably referring to [this commit](f9ff221f9eb8aacaecf057e3e9a1ca7c4e8a5beb)

**Comment by kyrylo-kolodiazhnyi-td** [comment]
Thanks, I know where I can find java sources. I'm asking why in release zip package doesn't exist directory ./include/org/kxml2/io/ with files KXmlParser.h and KXmlSerializer.h. For release 0.9.8 such directory exists.

**Comment by tomball** [comment]
Why? Because these classes aren't part of the public JRE or Android API,
they're private implementation classes. Android and j2objc (since it's JRE
is based on Android's libcore package) use the org.kxml2.io classes to
implement the interfaces defined in org.xmlpull.v1, but portable apps
should only use the org.xmlpull.v1 API.

If you simply must use the non-portable org.kxml2.io API, you are welcome
to build the j2objc/jre_emul project yourself, where the headers will then
be in j2objc/jre_emul/build_result/Classes/. However, if Android's libcore
team switches to another implementation of org.xmlpull.v1 in the future,
then the j2objc JRE will as well.

**Comment by Kolkir** [comment]
Thanks, for the explanation.
