### ISSUE TITLE
Using a java enum to populate a UIPickerViewDataSource 

### ISSUE THREAD

**Issue by atwhepner** [google/j2objc#756]
I need to use a java enum as the datasource for my UIPickerView. I have a method that converts the IOSObjectArray to an NSArray. That works just fine:

```
- (NSArray *)arrayFromJavaArray:(IOSObjectArray *)javaArray{
    NSMutableArray *mutableArray = [[NSMutableArray alloc] init];
    
    for (id element in javaArray) {
        [mutableArray addObject:element];
    }
    return mutableArray;
}
```

I can call my method, set my datasource, and print my array without issue:
```
    self.visitTypeNSArray = [self arrayFromJavaArray:COVisitRequestType_values()];
    self.visitTypePicker.dataSource = (id <UIPickerViewDataSource>) self.visitTypeNSArray;
    NSLog(@"visitTypeNSArray: %@", self.visitTypeNSArray);
```

The exception happens after viewDidLoad runs:
```
2016-06-08 18:11:21.671 Visit[3854:3906237] -[COVisitRequestType length]: unrecognized selector sent to instance 0x7fbdd66686a0
2016-06-08 18:11:21.683 Visit[3854:3906237] Uncaught exception: java.lang.Throwable: -[COVisitRequestType length]: unrecognized selector sent to instance 0x7fbdd66686a0
```

I know NSArray has "count", rather than "length". But I never use length, that I know of.

**Comment by kstanger** [comment]
Looks like you're trying to call "length" on one of your enum values.

**Comment by tomball** [comment]
That's right, as UIPickerView's documentation states: "Each row on a component has content, which is either a string or a view object such as a label (UILabel) or an image (UIImageView)." My guess is that because the enum elements are not UILabels or UIImageViews, UIPickerView assumes they are strings and tries to reference the string's length property. 

To resolve this, I suggest creating an array of strings that's the same size as your enum's values array, then iterate over the values and add each enum constant's name. To determine which enum was picked, use Enum.valueOf(enum-class, string).
