### ISSUE TITLE
Does j2objc support swift framework?

### ISSUE THREAD

**Issue by leogeng** [google/j2objc#759]
I want to make a swift framework  with translate code by j2objc, and it alway error: 
`/Include of non-modular header inside framework module 'XXXX'`

Even i add JRE.Framework.

Does j2objc support swift framework?

**Comment by Buggaboo** [comment]
Yes, but beware, it's not completely ready yet.

**Comment by leogeng** [comment]
@Buggaboo , Do you mean it has supported swift framework?
Can you give me a solution to fix the problem?

**Comment by Buggaboo** [comment]
I have issues with certain type conversions, class cast exceptions, reflection and dynamic linking, issues with generics (use the `AnyObject` type for now)... do not attempt to use `IosHttp(s)URLConnection`, I have a bunch of custom patches to make it work (also for certificate pinning, no public pinning yet, I have to wrap harmony DER stuff with it first)

That non-modular thing problem you have there was the easiest to fix. 

Also the current generated `module.map` is useless. It should be renamed to `module.modulemap` and put inside the Headers path, i.e. `./dist/frameworks/JRE.framework/Versions/A/Headers/`, contain this:

```
module JRE {
    umbrella header "JRE.h"
    export *
    module * { export * }
}
```

I meant to do a pull request for this (among others) but I don't have time yet. I will soon though.

You need a whole bunch of things:
* You also need libz in your dependencies
* Build Settings > Modules
  * Allow non-modular includes... **No**
  * Enable modules **Yes**
  * Link frameworks auto... **Yes**
* Build Settings > Search paths
  * Always search user paths **No**
  * Use header maps **No**

**Comment by Buggaboo** [comment]
I'm thinking of using xtext and reusing some simple java6 grammar to generate swift code.

**Comment by leogeng** [comment]
@Buggaboo Thank  you, It works ok

**Comment by ygweric** [comment]
Hi @Buggaboo : Thanks for your answer, but I failed..... Can you help me to fix it? 

I write a demo so that you can find the error and modify it and save your time.  Thanks a lot.

[Demo](https://github.com/ygweric/J2ObjcPodDemo)

Following is my description about error, same with my Readme file in github.


----

I'm tring to use j2objc with cocoapods and swift, now I can compile j2objc framework, but when I compile my swift project with j2objc framework, there will be errors `Include of non-modular header inside framework module 'j2objc_j2objc_debug.ModelId'`

Can anybody help me ?

I've tried the following way to fix it, but totally failed

[https://github.com/google/j2objc/issues/759#issuecomment-226695367](https://github.com/google/j2objc/issues/759#issuecomment-226695367)

[http://stackoverflow.com/a/28552525/1142674](http://stackoverflow.com/a/28552525/1142674)

[http://stackoverflow.com/a/37072619/1142674](http://stackoverflow.com/a/37072619/1142674)



### How to use this demo

 1. Run `pod install`
 2. build `j2objc_j2objc_debug`, maybe you need to configure the `Header Search Paths` and `Library Search Paths` to your `$j2objc_home`
 3. build `J2ObjcPodDemo`, maybe you need to configure the `Header Search Paths` to your `$j2objc_home`

Then this will be error : `Include of non-modular header inside framework module 'j2objc_j2objc_debug.ModelId'`
 
### Directory structure
 * in `j2objcOutputs`, it is my objc code which is generated by `j2objc-grandle`
 * The `Podfile` is configured by `j2objc-grandle`
 
### Some other things
 * I can compile my project if I add all objc source files into my project directly, without error, But it is better to use pods
 * I've try to configure differnt path, etc., no work

**Comment by Buggaboo** [comment]
I haven't used pods. I just dragged all the frameworks, e.g. j2objc dependencies and the translated j2objc library,  into the project directly, then referenced it from swift code.
