### ISSUE TITLE
@ObjectiveCName Assertion Failure

### ISSUE THREAD

**Issue by cameronbell** [google/j2objc#775]
Hello, 

I'm trying to rename a method using @ObjectiveCName. I would like to use this on a Constructor but I couldn't figure out whether that was supported, so I'm currently trying it on a Factory method.
```
@ObjectiveCName(value="createRecordWithFirstName:(NSString *)firstName")
public static Record createRecord(String firstName) throws DisplayException {
    return new Record(firstName);
}
```

I'm getting an assertion failure [here.](https://github.com/google/j2objc/blob/1.0.2/translator/src/main/java/com/google/devtools/j2objc/gen/TypeGenerator.java#L283)

If the selector string is split with `:` that will result in 2 substrings, so `selParts.length` would be 2, and the number of params is 1, so the assertion fails. Am I misunderstanding something about how the selector string should be formatted? 

I've been working off the example in this [forum post](https://groups.google.com/forum/#!topic/j2objc-discuss/UeR94UlD-ew).

**Comment by tomball** [comment]
That post is old, as we found that method declarations allowed developers
to declare identical selectors that looked different (for example,
"foo:(NSString *)bar" and "foo:(int)mumble" have the same selector,
"foo:"). Instead, use the actual Objective C selector:
@ObjectiveCName(value="createRecordWithFirstName:"). The trade-off is that
Java developers need to learn Objective C better to understand selectors,
but we thought that was A Good Thing. :-)

Constructors are similarly handled, but should start with "init" for
consistency with Objective C naming. So "public Record(String firstName)"
could use: @ObjectiveCName("initWithFirstName:").

I'll leave this bug open, since that assertion failure needs to be replaced
with a compiler error.

**Comment by tomball** [comment]
That post is old, as we found that method declarations allowed developers
to declare identical selectors that looked different (for example,
"foo:(NSString *)bar" and "foo:(int)mumble" have the same selector,
"foo:"). Instead, use the actual Objective C selector:
`@ObjectiveCName(value="createRecordWithFirstName:")`. The trade-off is that
Java developers need to learn Objective C better to understand selectors,
but we thought that was A Good Thing. :-)

Constructors are similarly handled, but should start with "init" for
consistency with Objective C naming. So "public Record(String firstName)"
could use: `@ObjectiveCName("initWithFirstName:")`.

I'll leave this bug open, since that assertion failure needs to be replaced
with a compiler error.

**Comment by cameronbell** [comment]
That worked. Thanks for your help!
