### ISSUE TITLE
j2objc for watchOS

### ISSUE THREAD

**Issue by yurevich1** [google/j2objc#780]
While building project I can see lots of warning like this:

`ld: warning: URGENT: building for watchOS simulator, but linking in object file (/Users/admin/Documents/j2objc-1.1/lib/libjre_emul.a(DoubleBuffer.o)) built for iOS. Note: This will be an error in the future.`

What does it mean? Will this code work on real watchOS device?

**Comment by maxibystro** [comment]
Any updates? I have the same warnings when I'm building Watch Extension with JRE framework for simulator. I know that there are no problems with build for real device because JRE static library includes arm7k architecture. And the problem on simulator is clear. Universal JRE static library can't contain slices for both platforms iOS and WatchOS because they use the same architecture on simulator - i386. That's why static library contains only slice for iOS. I think it is not problem at all because JRE does not use iOS specific frameworks. So JRE should work on WatchOS simulator despite the fact that it was built for iOS platform. But does anyone know what to do with a bunch of warnings?

**Comment by tomball** [comment]
The jre_emul library is no longer built with an iOS armv7k slice, [that slice is now only for watchv7k](https://github.com/google/j2objc/commit/889ab385157c6a2014282f87373926be7bbb6f00#diff-099dafc678df7d266c25f95ccf6cde22). Is this specific to the Gradle plug-in (not a part of this project)? 

Neither our team nor any internal projects use j2objc for watch apps, as the JRE support is too big to be usable for large apps (and small apps are easily rewritten). The WatchOS commit came from a contributed pull request, so if it needs improving/fixing, please submit a pull request to update it.

**Comment by maxibystro** [comment]
I see that armv7k slice is still a part of iOS jre_emul library (which is in the JRE.framework). I created PR #954 where I moved armv7k slice to a separate jre_emul library for watchOS. Also this library includes i384 slice for watchsimulator sdk. Using of watchOS jre_emul will get rid of warnings from the issue description.

**Comment by antonio-cortes-perez** [comment]
Fixed in release 2.1.
