### ISSUE TITLE
Java classes cannot use other java classes

### ISSUE THREAD

**Issue by molbertz** [google/j2objc#788]
Every one of my java classes can be translated just fine. UNLESS they use another of my classes. Not even the most simple of use cases can be built successfully: Two classes. Both in the same package. Once I use one in the other... Boom. "MyClass cannot be resolved to a type".

What is that? Again, the basic setup and all seems to be correct as I indeed can translate, compile and build my app using java classes. As long as none of them reference each other. Also again, I stepped away from using classes from different packages. I reduced it to the most mimimal configuration: Two classes, same package.

Otherwise working script is:
j2objc - $(DERIVED_FILES_DIR) -sourcepath $(PROJECT_DIR)/** --no-package-directories -use-arc -g $(INPUT_FILE_PATH);

**Comment by tomball** [comment]
The main thing to remember when debugging j2objc failures is that it shares all its core arguments (-sourcepath, -classpath, -d, -g, etc.) with other Java compilers like javac. So if the j2objc-specific args are removed and "j2objc" is replaced with "javac", the command is:

    javac - $(DERIVED_FILES_DIR) -sourcepath $(PROJECT_DIR)/** -g $(INPUT_FILE_PATH);

To fix this, change the initial "-" arg to "-d". The "/**" source path looks suspect, too, but you didn't say what build tool you are using.

**Comment by molbertz** [comment]
Ok, this is gonna be kind long, but I'd like to explain myself for opening the issue:

I've done a lot  of research on this. And everywhere it says the same thing. Switch out with javac. Thing is, javac works just fine. From the commandline. But then again, so does j2objc. I forgot to mention that I use the Xcode Build Rule way. And that doesn't work as described everywhere. I was trying for 9 hours yesterday before opening this issue. Nothing worked.
Today, I found the answer. And it's something that nobody ever seems to have a problem with.

It was indeed the sourcepath. But, $(PROJECT_DIR) gets expanded to an absolute path. From within Xcode j2objc command call doesn't work with that. Because the working directory already is the $(PROJECT_DIR). For example: /Users/Me/iOS/MyProject
Now Xcode also creates another folder inside this location. Also named MyProject. So calling the Build Rule from within Xcode would be the same as to: cd /Users/Me/iOS/MyProject
And then calling: /path/to/j2objc ...
Now the java sources would be located in their package folder inside the "second" project folder:
/Users/Me/iOS/MyProject/MyProject/javapackage/JavaClass.java
Since our working directory is /Users/Me/iOS/MyProject, the call would have to be:
/path/to/j2objc -d builddir -sourcepath "MyProject/" /Users/Me/iOS/MyProject/MyProject/javapackage/JavaClass.java
With this, all related sources can be found.

Now, I can't believe that I am the only one having this problem with Xcode. I followed the tutorial for the Build Rule and the project structure is what Xcode generates. So what am I doing wrong? Everybody else seems fine with the -sourcepath $(PROJECT_DIR) and from my understanding it just can't work because the sourcepath must only be the project name; not the entire absolute path.

**Comment by tomball** [comment]
If $(PROJECT_DIR) points to "/Users/Me/iOS/MyProject" and the top of
"javapackage" is in "/Users/Me/iOS/MyProject/MyProject", then use
"-sourcepath $(PROJECT_DIR)/MyProject". There's nothing special (or
j2objc-specific) about the PROJECT_DIR -- it's just a build variable that
is expanded when inside $() (Xcode borrowed that concept from Make). If
that doesn't work, check your build log to verify what Xcode defines
PROJECT_DIR to be, then substitute that value into $(PROJECT_DIR) and list
the directory. Your top-level package directory should be listed, or else
the sub-directory ("/Myproject") needs to be changed until that package
directory is listed.

The reason $(PROJECT_DIR) is used is to avoid absolute paths in a project
(otherwise you can't share or move them), but relative paths within a
project are fine.
