### ISSUE TITLE
ObjectOutputStream possible issue using iOS 10.

### ISSUE THREAD

**Issue by jtdavid** [google/j2objc#798]
Hi,

I found a possible issue ONLY when running on iOS 10, and on the second attempt to create / initialize an ObjectOutputStream.

```
JavaIoOutputStream *myFileOutputStream = new_JavaIoFileOutputStream_initWithNSString_(nameGzip);

JavaUtilZipGZIPOutputStream *myGzipOutputStream = new_JavaUtilZipGZIPOutputStream_initWithJavaIoOutputStream_(myFileOutputStream);

JavaIoBufferedOutputStream *myBufferedOutputStream = new_JavaIoBufferedOutputStream_initWithJavaIoOutputStream_(myGzipOutputStream);

JavaIoObjectOutputStream *myObjectOutputStream = new_JavaIoObjectOutputStream_initWithJavaIoOutputStream_(myBufferedOutputStream);

[myObjectOutputStream writeObjectWithId:myInstance];
```

The application crashes with no memory management issue when trying to initialize the ObjectOutputStream and not when writing / serializing the object.

It always fires a crash similar to the following one:

`Exception in thread "Thread-2" java.lang.Throwable: -[__NSCFString member:]: unrecognized selector sent to instance 0x170840240`

So it seems like a memory retaining issue (some object being dealloc while still being used) but this is happening inside jre_emul.a somewhere...

Any further opinions or help will be highly appreciated.

Thanks.

**Comment by jtdavid** [comment]
Some other time the crash could be:

Exception in thread "Thread-2" java.lang.Throwable: -[JavaLangReflectField member:]: unrecognized selector sent to instance 0x17044d950

So basically it's an unrecognized selector "member:" that is triggering (on any randomly object at that address).

**Comment by ashitikov** [comment]
Confirm. We have the same problems while using [IOSClass getGenericDeclaration]. There is a serious bug inside jre_emul.a.

**Comment by ashitikov** [comment]
Hello! Finally I found a problem.

The reason of crash is String.intern().
There is a NSString+JavaString extension in J2OBJC which implements intern() method and does nothing by default:
```objc
// NSString+JavaString.h
// String.intern()
- (NSString *)intern;

// NSString+JavaString.m
- (NSString *)intern {
  // No actual interning is done, since NSString doesn't support it.
  // Instead, any "string == otherString" expression is changed to
  // "string.equals(otherString)
  return self;
}
```
The same method implements private default framework ProtocolBuffers, but it's hidden:
https://github.com/nst/iOS-Runtime-Headers/blob/f7f2c13158ff4ecd15b92eefb5c5d365b126db05/Frameworks/Foundation.framework/NSString.h#L1649
```objc
- (id)intern;
```
This method was implemented in iOS 10 first, so you can check that it doesn't exists in iOS 9.3:
https://github.com/nst/iOS-Runtime-Headers/blob/f92ec9a266a77e59a691ca35f4fba240d34eec91/Frameworks/Foundation.framework/NSString.h

Then in runtime when you call [NSString intern] there is no guarantees that [NSString intern] will be called from NSString+JavaString extension, so it cause unpredictable behaviour with crash. I guess it worth to rename this method because private api is probihited to use and can cause iTunesConnect reject.

In XCode debug you can check behaviour by adding new symbolic breakpoint:
-[NSString intern]
![breakpoints](https://cloud.githubusercontent.com/assets/8819544/19530098/81822a38-9643-11e6-845a-8e6a8c192a11.png)

**Comment by ashitikov** [comment]
I think I can create a PR like #787

**Comment by jtdavid** [comment]
@ashitikov Great catch! I will wait for that PR.

**Comment by tomball** [comment]
Thanks for the investigative work. We're in the (slow) process of adding
prefixes to the methods defined in our categories, which will fix this
issue.

The reason we aren't doing the prefixes all at once is because we have apps
that unfortunately call them directly. Many of these apps were very early
users of j2objc, and we learned the hard way that anything visible in
Xcode's code-completion list will be used by native code developers
(whether they should or not). That's why over the past couple of years
we've taken steps to separate the public API from the private, but the
legacy code is still around and only being fixed when we break it. :(

**Comment by kstanger** [comment]
"java_" prefixes were added to J2ObjC category methods in [this commit](https://github.com/google/j2objc/commit/c1e3ffb581b16e1f45bd097d84fdda60761c2be6).
