### ISSUE TITLE
Problem with classes having the same name but in different packages

### ISSUE THREAD

**Issue by simmese** [google/j2objc#817]
We have Java classes with same name in different packages. In this case j2objc converter translate the code generating the translation in objC only for the last java file. So in objC I have not the classes previous to the last!

There exist a way to avoid this behaviour?

This is my script:

if [ ! -f "${J2OBJC_HOME}/j2objc" ]; then echo "J2OBJC_HOME is not correctly defined, currently set to '${J2OBJC_HOME}'"; exit 1; fi;
"${J2OBJC_HOME}/j2objc" -d ${GENERATED_FILES_DIR} --no-package-directories -sourcepath "${JAVA_SOURCE_PATH}" -g ${INPUT_FILE_PATH};

Many thanks in advance!

Simone

**Comment by tomball** [comment]
Java uses packages to allow classes with the same name, while Objective C
has no support for packages, namespaces or anything similar. So you have a
few options:

1. Use unique Java source file names. Note: if the source file doesn't have
any public classes, you can name it anything.java without having to change
the actual code. Note 2: just because a class is declared public doesn't
mean it has to be -- in most cases, only classes that are referenced by
classes in other packages need to be public.

2. Build the translated Java code as a static library, using Make, Gradle,
Maven, a custom script, whatever. In Xcode, define an External Build
target, then have its Info panel call the appropriate build tool. For
example, JreEmulation.xcodeproj
<https://github.com/google/j2objc/tree/master/jre_emul/JreEmulation.xcodeproj>
does this with its "j2objc build" target.

3. If your app only uses a few Java sources, consider rewriting them in
Objective C, either by hand or translating them once and copying the
translated files into your project and editing them. j2objc is most useful
for apps that either have a LOT of shared code, or which share code that is
frequently modified. If you app has neither, then j2objc is likely to be
more trouble than it's worth for your team.

**Comment by lukhnos** [comment]
Another choice is not to use the `--no-package-directories` option and set up your Xcode project accordingly. I ran into this problem long time ago with a large Java library. The option looked attractive when I only had a small project, but setting my Xcode project to work with the directory structure resulting from a large library can go a long way.
