### ISSUE TITLE
ThrowAble.getStrackTrace() returns empty Array on Release Build

### ISSUE THREAD

**Issue by L6Echo** [google/j2objc#819]
On a release build, getStrackTrace returns always an empty Array

This code:
```swift
let throwAble: NSException = JavaLangIllegalArgumentException();
let stacktrace:IOSObjectArray = throwAble.getStackTrace();
let length = stacktrace.length();
NSLog("StackTraceLength: \(length)");
```
prints in debug build `StackTraceLength: 2` and in release build `StackTraceLength: 0`

Tested on iOS 10.1 SDK with Xcode 8.1 with J2Objc 1.2

**Comment by antonio-cortes-perez** [comment]
This is by design. On release builds, debug symbols are usually stripped, if the stack trace was printed it would only contain hex addresses (no class or method information). In our experience, returning this stripped stack trace caused a lot of confusion. Right now, we are evaluating the usefulness of the stripped stack trace. If we decide to implement it, you'll hear about it in a future release of J2ObjC.
