### ISSUE TITLE
Improve obj-c translation naming convention for better swift support

### ISSUE THREAD

**Issue by ryanmaxwell** [google/j2objc#821]
I've been using some code that has been translated using j2objc, as well as including the JRE Support files.

What I've noticed is that the naming of methods (especially constructors) in the project doesn't match Apple's style, which means that it translates rather poorly into swift headers (especially Swift 3).

Apple has some documentation [here](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html#//apple_ref/doc/uid/TP40014216-CH4-ID35) about how the translation works, and it's largely based around heuristics and works best when the objective-c methods are all named in a particular way.

As a simple example of how things are currently poor, and how they could be improved - 

Constructing a Date in Java - Date.h has a constructor with the signature

```objc
- (instancetype)initWithInt:(jint)year
                    withInt:(jint)month
                    withInt:(jint)day
                    withInt:(jint)hour
                    withInt:(jint)minute
                    withInt:(jint)second;
```

Which then translates to:

```swift
public init!(int year: jint, with month: jint, with day: jint, with hour: jint, with minute: jint, with second: jint)`
```

And then when you use (and read a line of code) you lose all the usefulness of the named arguments:

<img width="659" alt="screen shot 2016-12-03 at 08 57 24" src="https://cloud.githubusercontent.com/assets/718440/20848476/2ae07c40-b937-11e6-926a-7ba499915b82.png">

Compare and contrast with Swift's Date Class:

<img width="816" alt="screen shot 2016-12-03 at 08 58 00" src="https://cloud.githubusercontent.com/assets/718440/20848499/42abedd2-b937-11e6-96c2-a7854ae56485.png">

How this could be improved is fixing the automatic translation of methods, especially removing the repeated use of 'with' in the signatures.

So rather than saying `withInt:(jint)month` as the second named parameter, you say `month:(jint)month`.
You should never mention the type information in the signature (that's what the type in parens is for), and you shouldn't continue to say 'with' after the first argument.

 E.g if the constructor was named:

```objc
- (instancetype)initWithYear:(jint)year
                       month:(jint)month
                         day:(jint)day
                        hour:(jint)hour
                      minute:(jint)minute
                      second:(jint)second;
```

It would translate much better to Swift and be visible as:
<img width="679" alt="screen shot 2016-12-03 at 09 13 42" src="https://cloud.githubusercontent.com/assets/718440/20848892/f3ed03c8-b938-11e6-941c-a1c2a8ca364b.png">

Instance methods too:

```objc
- (jint)compareToWithId:(JavaUtilDate *)date;
```

should be named:

```swift
- (jint)compareToDate:(JavaUtilDate *)date;
```

And this will translate nicely to a `compareTo(date:` method rather than the awkward `compareTo(withId:` method - which actually makes even less sense as 'id' isn't a type in swift, so it gives the impression that it's comparing based on some kind of identifier rather than objects!

**Comment by kstanger** [comment]
There are good reasons that we use the type names instead of parameter names when generating signatures.
The primary reason is that it generates unique names for overloaded java methods, which would cause a naming collision if parameter names were used. For example if you have methods "foo(int i)" and "foo(long i)" the type names must be used to avoid generating the same selector for both methods.
Another reason is that with our existing JDT parser we actually don't know the parameter names at the invocation site. This will no longer be a restriction when we've switched to the Javac parser.

We welcome any suggestions that can account for the overloading described above, but any change to our method naming scheme will be disruptive to all of our users so it would be difficult to adopt.

Another solution that's available is our [\@ObjectiveCName](https://github.com/google/j2objc/blob/master/annotations/src/main/java/com/google/j2objc/annotations/ObjectiveCName.java) annotation that you can add to any method to change the generated selector. For example:
```
@ObjectiveCName("initWithYear:month:day")
public Date(int year, int month, int day) {}
```
