### ISSUE TITLE
Leak in Okio's Buffer

### ISSUE THREAD

**Issue by mdiiorio** [google/j2objc#822]
The following code will leak an Okio Segment and IOSByteArray:

```
- (void)test_leak;
{
    OkioBuffer *buffer = [[OkioBuffer alloc] init];
    [buffer writeByteWithInt:1];
}
```

This is due to Segment having a next and prev reference that in certain cases is assigned to the Segment itself, resulting in a retain cycle.

We haven't upgraded to 1.2 yet, so we're translating Okio ourselves. In our project we've fixed it by changing Okio's Buffer's dealloc method to be:

```
- (void)dealloc {
  if (head_) {
    JreStrongAssign(&((OkioSegment *) nil_chk(head_))->next_, nil);
    JreStrongAssign(&((OkioSegment *) nil_chk(head_))->prev_, nil);
  }
  RELEASE_(head_);
  [super dealloc];
}
```

We've tested with J2Objc 1.2 and see the same thing. What's the best way to get this fix into J2Objc?

**Comment by tomball** [comment]
This issue can't be fixed in j2objc, as that particular reference cycle can't be determined statically (that's why cycle_finder doesn't list it). The best way is to update the Okio source, which I suspect won't be an issue for that team as they've worked with us before. There are three ways I can think of (Keith is on vacation but may have better ideas when he gets back):

1. Add a Maven dependency on [j2objc-annotations](http://search.maven.org/#artifactdetails%7Ccom.google.j2objc%7Cj2objc-annotations%7C1.1%7Cjar), then mark the next and prev fields with the [Weak](http://j2objc.org/docs/Weak.html) annotation.

2. Add a finalize() method with your workaround:
```
public void finalize() {
  if (head != null) {
    next = null;
    prev = null;
  }
}
```

3. Add a `clear()` (or some other name) method, and call it from your source:
```
public void clear() {
  if (head != null) {
    next = null;
    prev = null;
  }
```
Option 1 requires the least code, but the Okio maintainers may not like the j2objc-annotations dependency (though it's harmless for normal Java use, since Weak has source retention and so doesn't affect classfiles). 

Option 2 requires no client code change, but finalize() methods are rightly held suspect since the Java runtime explicitly doesn't guarantee they'll be run (hence the need for java.io.Closeable). The maintainers may be persuaded, though, because this code explicitly does what the garbage collector would do anyway.

Option 3 is also harmless, since client code that doesn't call clear() works the same (except with j2objc, or course). In some cases, explicitly setting fields to null never hurts and can help GC, as [this OpenJDK comment describes](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/LinkedList.java#l449).

The last and perhaps best option is to ask the Okio maintainers for help, as they can make a small refactoring can avoid this cycle. Feel free to send them our way if they have any questions or concerns.

**Comment by mdiiorio** [comment]
Ok, thanks for the response. I'll follow-up with Okio and see what they say.
