### ISSUE TITLE
New feature: Field renaming with something similar to @ObjectiveCName

### ISSUE THREAD

**Issue by aollin** [google/j2objc#826]
I'm writing a Java preprocessor that adds automatic @ObjectiveCName annotations with to methods and classes to hide unnecessary information from reverse engineers using class-dump or similar utility. 

Also fields names are visible in the binary, so they need to be renamed too. I'm willing to write the required code, but I'm asking

 1) If j2objc has the required facility to rename field members. I know it does that in some form already, so my guess is yes?

2) Where to look for the renaming in the sources if the facility indeed exists?

**Comment by tomball** [comment]
We don't support field renaming, other than for reserved Objective C names (reserved words, header #defines, etc.) where a trailing underscore is added. That's because none of our customers thought it necessary, since most fields in Java are private (other than constants).

Personally, I believe that obfuscation for the purpose of blocking reverse engineering is useless, since any decent engineer that has your code and enough incentive to reverse engineer it can do so. The same requests and denials were made 20 years ago with Java applets: anyone who has access to your class files can figure out how to rewrite them. J2ObjC is primarily for cross-platform iOS apps, so even if you could totally hide the Objective C code, the Android version of that code is still relatively easy to decipher. 

Obfuscation to reduce app size is still useful, which is one reason so many Android developers use ProGuard. We're hoping this year to be able to translate JVM class files, and assuming that's possible, one in theory could translate ProGuard-stripped class files. However, that's all speculation at this point.

What was instead recommended to those Java applet writers, and is still recommended today, is to run all proprietary code on your server, where it can't be reverse engineered.

**Comment by aollin** [comment]
Time to obfuscate and crack proof equals time to crack. As simple as making it expensive for the attacker. I guess it does not matter for big corporations, but small indie developer here.
