### ISSUE TITLE
Warnings in *RetentionPolicy.h*: Pointer is missing a nullability type specifier

### ISSUE THREAD

**Issue by adil-hussain-84** [google/j2objc#827]
I've just updated the version of J2ObjC that I'm using (from 1.0.2 to 1.2) and I'm getting some warnings (14 to be precise) in my project because of the `RetentionPolicy.h` header missing nullability type specifiers..

```/Library/J2ObjC/j2objc-1.2/include/java/lang/annotation/RetentionPolicy.h:53:38: Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)```

... I'm guessing Xcode is complaining because some methods in this class have a nullability type specifier and some don't.

**Comment by tomball** [comment]
What version of LLVM (clang) is installed on your system? You can find out by running "clang --version" on the command line. Are you running j2objc with the --nullability flag?

**Comment by sbosley** [comment]
I am encountering a very similar issue with Thread.h in j2objc 1.2. Here's an example that reproduces the problem for me. Minimal test case class:

```java
package com.yahoo.j2objctest;

import junit.framework.TestCase;

public class TestThread extends TestCase {

    public void testThread() {
        Thread t = new Thread() {
                @Override
                public void run() {
                    System.out.println("I am thread " + getName());
                }
        };
        t.start();
        try {
            t.join();
        } catch (InterruptedException e) {
            //
        }
    }
}
```

Compiled with:
```
${J2OBJC_HOME}/j2objc -classpath "${J2OBJC_HOME}/lib/j2objc_junit.jar:${J2OBJC_HOME}/lib/jre_emul.jar" --no-package-directories -use-arc com/**/*.java
${J2OBJC_HOME}/j2objcc -fobjc-arc -I. -o "TestThread.o" -c TestThread.m
```

This compiles without warnings or errors using j2objc 1.1, but generates several "j2objc-1.2/include/java/lang/Thread.h:69:4: error: pointer is missing a nullability type specifier" errors with j2objc 1.2. Running on macOS 10.12.2, clang version 8.0.0. I'm assuming this the same fundamental issue as the OP's but forgive me if it's not!

I haven't dug into it deeply yet so sorry I can't provide more helpful info -- I might just be doing something wrong, but wanted to add some steps that exhibit the problem for me in case they were helpful.

**Comment by tomball** [comment]
Would one of you please edit the j2objc 1.2 header where the warning you found is being reported, delete the "#pragma mark Public" line above it, and respond whether the warning goes away? 

The pragma shouldn't matter, but both of these two cases are the first method after that pragma. The warning isn't reported when running clang on the command line, so maybe someone on the Xcode team thought all "Public" API must have full nullability annotating. If so, we can get rid of those pragmas, as they're just to organize methods a little better.

**Comment by sbosley** [comment]
@tomball no luck I'm afraid. I still get the same errors using j2objc 1.2 even with the pragma gone. [Here's a gist](https://gist.github.com/sbosley/716e401f96285400ce31e6e791f8ef90) of the full output I'm seeing.

I actually still get the same messages when invoking clang directly from the command line as well. I replaced my j2objcc invocation with `clang -fobjc-arc -I. -I${J2OBJC_HOME}/include -o "TestThread.o" -c TestThread.m` and still saw them with j2objc 1.2. However, clang seems to treat them as warnings by default, while j2objcc treats them as errors (I assume this difference is simply because j2objcc uses the -Werror flag).

**Comment by tomball** [comment]
Yes, the -Werror is why it's failing -- feel free to remove that flag from
the j2objcc script, as it doesn't affect what code is generated.

I think I'll add the -Wno-nullability-completeness flag to j2objcc for 1.3,
as completeness checking doesn't really make sense with translated Java
since javac doesn't enforce it. You can try adding that flag in the
meantime.

**Comment by tomball** [comment]
Added flag to j2objcc.sh. Please note that this won't affect Xcode builds, since they don't normally use the j2objcc script.
