### ISSUE TITLE
Conflict with NSString length property in Swift

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#831]
JavaLangCharSequence declares the method "- (jint)length;" and J2ObjC's category on NSString conforms to JavaLangCharSequence. While this doesn't seem to cause any issues with Objective-C compilation, it does cause Swift compile errors when trying to access the "length" property.

Example code accessing NSString property:
let i: Int = str.length;
Error:
Cannot convert value of type '() -> Int32' to specified type 'Int'

Example code accessing NSString as a method:
let i: Int = str.length();
Error:
Cannot convert value of type 'Int32' to specified type 'Int'

**Comment by duraz** [comment]
To provide context:
We're asking J2Objc's category to be implemented without causing name space collisions with the already existing Objective-c api, and the Objective-c Swift cross-functionality api. We believe that's very important both for Swift/Objectvie-c and for the success of J2Objc, given the fact that Swift is the new standard and Objective-C interoperability with it is paramount.

Recently we had issues while trying to use the newly released GCD api "wait()". Trying to do so would not allow our codebase to compile when the J2ObjC's library was included in the project. [https://groups.google.com/forum/#!topic/j2objc-discuss/P7REr-yKX9s] This was fixed in the 1.3 release.

In the past we also had a similar issue with the length call on NSString. To my understanding this issue was then fixed with a new release of J2ObjC so that the "length" namespace found in Objective-c was not also found in the J2ObjC category.

We recently found another issue with getters named "notify". The error we would get was: "Getter for 'notify' with Objective-C selector 'notify' conflicts with method 'notify()' from superclass 'NSObject' with the same Objective-C selector". This has also been fixed.

We're now discussing the "length" compile error we get when we try to build our project. Like stated above compiling in Swift is causing the error when accessing the "length" property. Swift is much more strict on types, and this seems to help surface the underlaying problem we see. In our opinion these are examples of a pattern that should be avoided while adding/maintaining new functionalities to the J2ObjC's category. The J2ObjC's category should not get in the middle of already existing API's, in this case, between Swift and Foundation. Adopting this semantic would allow J2ObjC to never cause these kinds of problems, even if it's just a type problem since  J2ObjC's code would never use already defined foundation API in the first place.

What possible fixes to J2ObjC do you guys think can be made to address this 'length' specific problem and avoid similar problems going forward?

**Comment by SpencerBaker** [comment]
@kstanger To answer your question if it's common to cast `String` to `NSString` in Swift, yes it is.

This is because `NSString.length` is more performant over `String.Characters.count`.

They also do different things. `NSString.length` performs a composed character count, while `Characters.count` does not.

**Comment by tomball** [comment]
We have a fix pending review and testing that maps both String.length() and
CharSequence.length() to java_length.

**Comment by duraz** [comment]
@tomball will look forward to next release. Thanks.

**Comment by kstanger** [comment]
Fixed in current source.
