### ISSUE TITLE
j2objc translation tool not being able to import `com.sun.*` dependencies

### ISSUE THREAD

**Issue by guilhermesgb** [google/j2objc#837]
Some files that I have which import files in the `com.sun.nio.sctp` package are unable to being translate as the import statements themselves are failing for some reason. Even after I included in the classpath a .jar defining them (netty-transport-sctp-4.0.26.Final.jar).

So I don't know how to workaround this issue.

Using the `javac` tool to get some insight on what is going on was of no help since it just works **without the need to include external dependencies** (`javac 1.8.0_121`).

Below is an example of such failure occurring when I try translating a file named `SCTPMessageChannel.java`. The imports of `com.sun.nio.sctp.SctpChannel.java` and `com.sun.nio.sctp.MessageInfo.java` fail right at the beginning, and several `X cannot be resolved to a type` messages are logged every time these dependencies are mentioned in the file.
```
error: ./src/android/gov/nist/javax/sip/stack/sctp/SCTPMessageChannel.java:14: The import com.sun cannot be resolved
error: ./src/android/gov/nist/javax/sip/stack/sctp/SCTPMessageChannel.java:15: The import com.sun cannot be resolved
error: ./src/android/gov/nist/javax/sip/stack/sctp/SCTPMessageChannel.java:51: SctpChannel cannot be resolved to a type
error: ./src/android/gov/nist/javax/sip/stack/sctp/SCTPMessageChannel.java:54: MessageInfo cannot be resolved to a type
error: ./src/android/gov/nist/javax/sip/stack/sctp/SCTPMessageChannel.java:69: MessageInfo cannot be resolved to a type
error: ./src/android/gov/nist/javax/sip/stack/sctp/SCTPMessageChannel.java:69: MessageInfo cannot be resolved
error: ./src/android/gov/nist/javax/sip/stack/sctp/SCTPMessageChannel.java:70: MessageInfo cannot be resolved to a type
```

**Comment by tomball** [comment]
The problem is that you are trying to translate classes that are on the -bootclasspath, classes that are included in the Java JRE (javac would report similar errors if invoked with "-bootclasspath j2objc/lib/jre_emul.jar"). j2objc only supports the JRE classes defined in its [JRE Emulation library](http://j2objc.org/reference/packages.html).

To use the netty-transport-sctp version, get the source files for that package and add the top-level directory for them to the -sourcepath. They'll need to be translated anyway for your app to run on iOS.

**Comment by guilhermesgb** [comment]
Got it. Many thanks for the help!
