### ISSUE TITLE
BreakIterator Does not support?

### ISSUE THREAD

**Issue by wdxxl** [google/j2objc#846]
Hi There,
Currently I'm working with Lucene-3.5.0, J2objc have error during convert related jars.

`j2objc -use-arc -d source_analyzers_350_arc lucene-analyzers-3.5.0-sources.jar -sourcepath lucene-highlighter-3.5.0-sources.jar lucene-memory-3.5.0-sources.jar lucene-queries-3.5.0-sources.jar lucene-spellchecker-3.5.0-sources.jar lucene-core-3.5.0-sources.jar jakarta-regexp-1.4-sources.jar`

error: org/apache/lucene/analysis/th/ThaiWordFilter.java:22: The import java.text.BreakIterator cannot be resolved.

**Comment by tomball** [comment]
The jre_emul library doesn't support java.text.BreakIterator because we haven't found an equivalent iOS class or functions that support it. iOS has an ICU library, but it only makes public part of the ICU C API which doesn't include ICU's ubrk.h. If jre_emul used ICU's break iterator functions without a public header in the iOS SDK, apps risk getting rejected due to its use of a private function. So until Apple releases an iOS SDK with ubrk.h in its public headers, we're stuck.

**Comment by lukhnos** [comment]
Another approach is to take a closer look at what you are translating. In your case, BreakIterator is needed by Lucene's Thai analyzer. If your app does not need that analyzer, you don't have to translate it and the classes that depend on it. Or you'll have to write your own analyzer, and Lucene is designed for making that possible.

**Comment by wdxxl** [comment]
@lukhnos thanks for the response, currently use this approach you mentioned, remove those analyzer from source jar to make it workable first.
