### ISSUE TITLE
Problem translating Nonnull and Nullable annotations

### ISSUE THREAD

**Issue by adil-hussain-84** [google/j2objc#849]
I've added the `'com.google.code.findbugs:jsr305:3.0.0'` dependency to my Java code and I've added a use of the `javax.annotation.Nonnull` annotation in my Java code.

I've also added the `-classpath "${J2OBJC_HOME}/lib/jsr305-3.0.0.jar"` option to my `j2objc` command as follows:

`${J2OBJC_HOME}/j2objc -d ${GENERATED_FILES_DIR} --prefixes ${PREFIXES_PROPERTIES_PATH} -Xuse-javac --no-package-directories -classpath ${J2OBJC_HOME}/lib/jsr305-3.0.0.jar -sourcepath ${SHARED_CODE_JAVA_SOURCE_PATH} $SHARED_CODE_JAVA_SOURCE_FILES`

When I run the `j2objc` command on my Java files they seem to translate okay.

However, when I build my iOS project which uses the translated files I'm getting some `"Apple Mach-O Linker Error"` messages as follows:
- ` "_JavaxAnnotationMetaWhen__initialized", referenced from:`
- `"_JavaxAnnotationMetaWhen_values_", referenced from:`
- `"_OBJC_CLASS_$_JavaxAnnotationMetaWhen", referenced from:`
- `"_create_JavaxAnnotationNonnull", referenced from:`
- `clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Any ideas what I need to add to my project setup in order for `Nonnull` and `Nullable` annotations from my Java code to translate and work okay in my iOS project?

**Edit:** I do have `"${J2OBJC_HOME}/include"` in my `Header Search Paths` and `"${J2OBJC_HOME}/lib"` in my `Library Search Paths` (in my Xcode project).

**Comment by tomball** [comment]
Short answer: link in the jsr305 library, using "-ljsr305" in Other Linker Flags.

Full answer: link errors due to unreferenced classes have the name of the missing class, camel-cased. For example, "_OBJC_CLASS_$_JavaxAnnotationMetaWhen" refers to the missing javax.annotation.meta.When class. Since javax.annotation.meta.When is defined in the jsr305 library, it needs to also be linked in.

The underlying issue is that you should be careful using -classpath -- libraries on the classpath only resolve references in files being translated, but are themselves not translated. That's fine for jsr305 since that library is included in the j2objc distribution. Putting other libraries on the classpath will resolve their references when translating, but cause linker failures because their code is not included in your app. There's no magic to j2objc: all Java code needs to be translated and linked into the app for it to work.

**Comment by adil-hussain-84** [comment]
Thanks @tomball. I can't believe I forgot the Other Linker Flags!

Thanks also for the warning about the `-classpath` option.
