### ISSUE TITLE
Wrong equality of AtomicInteger

### ISSUE THREAD

**Issue by ArtemShaban** [google/j2objc#850]
By default in java AtomicInteger is not override "equals" method and it compares by link.
But translated JavaUtilConcurrentAtomicAtomicInteger extends from NSNumber, which compares by value.

**in IOS:**
 JavaUtilConcurrentAtomicAtomicInteger *a1 = [JavaUtilConcurrentAtomicAtomicInteger new];
 [a1 setWithInt:1];
 JavaUtilConcurrentAtomicAtomicInteger *a2 = [JavaUtilConcurrentAtomicAtomicInteger new];
 [a2 setWithInt:1];
 BOOL equals = [a1 isEqual:a2];  //**YES**

**in JAVA:**
 AtomicInteger a1 = new AtomicInteger(1);
 AtomicInteger a2 = new AtomicInteger(1);
 boolean equals = a1.equals(a2); //**FALSE**

**Comment by tomball** [comment]
Good catch, I found [this discussion](http://stackoverflow.com/questions/7567502/why-are-two-atomicintegers-never-equal) that describes the subtleties. It actually shows a more basic problem: we map Number to NSNumber, so any class that doesn't explicitly define equals() or hashCode() will be incorrect. Perhaps we need for java.lang.Number to extend NSNumber instead of be mapped to it, as it can override NSNumber's isEqual: and hash methods.

**Comment by zubchenok** [comment]
This fix is needed to have RxJava project translations work properly

**Comment by tomball** [comment]
Having Number extend NSNumber ran into several subtle test failures. Keith has a better idea I'll work on, where the translator adds isEqualTo: and hash methods that behave like java.lang.Object's methods, when a class extends Number but doesn't override them. Since the wrapper classes in java.lang all do override those methods, this change will only affect the atomic subclasses as well as any outside of the JRE.

**Comment by tomball** [comment]
Fixed in current source.
