### ISSUE TITLE
j2objc 2.0: can't create an instance of SecureRandom

### ISSUE THREAD

**Issue by kberezindevex** [google/j2objc#856]
Hi,

After migration to j2objc 2.0 we discovered, that we are no longer able to create SecureRandom instance. It crashes with the following error:
```
PSSessionConnectionDaemon: <error>, Unexpected error, Unable to configure default providers, class java.lang.AssertionError, 
[0x00000001073f11cb java.lang.AssertionError.<init>() + 45, 
0x0000000107666934 sun.security.jca.Providers.<clinit>() + 430, 
0x0000000107666b83 sun.security.jca.Providers.getProviderList() + 52,
0x000000010758cf96 java.security.SecureRandom.getPrngAlgorithm() + 86, 
0x000000010758bf01 java.security.SecureRandom.getDefaultPRNG() + 29, 0x00000001073da44b PSEncryptionHelper.getKeyGen() + 11, 
0x000000010736d7a6 PSRsaClientEncryptionProcessor.createRsaOption() + 342, 
0x000000010736d5fc PSRsaClientEncryptionProcessor.supportedOptions() + 188, 0x00000001072c0445 PSConnector.createInitialPacket() + 309, 
0x00000001072c0296 PSConnector.connect() + 278, 
0x0000000107253b82 PSSessionConnectionDaemon.connectAndWait() + 562, 
0x00000001072537ed PSSessionConnectionDaemon.loopOnConnector() + 29, 
0x0000000107254aa3
```

Maybe it is somehow related to the migration to Apache Harmony? Any help would be appreciated.

Thanks,
Kirill

**Comment by tomball** [comment]
The problem is that sun.security.jca.Providers dynamically loads the security providers, so there's no dependency found for them when linking. 

There are a couple of temporary workarounds you can do until we fix this. The first is to link with the -ObjC flag, which links *all* Objective C classes found in static libraries. This can make your app bigger, so it's best to only use which developing your app. Our tests didn't catch this error because JUnit reflectively loads all test classes, so the test bundle has to be linked with -ObjC.

The other workaround is to add references to the security providers, from a class that's already linked into your app so the linker includes it. I'll be adding this to Providers.java:
```
    @SuppressWarnings("unused")
       private static final Class<?>[] providers = new Class[] {
        IosSecurityProvider.class,
        CertPathProvider.class,
    };
```
This won't increase the size of your app, since those classes should have been linked into your app (but weren't). If you add this block to your code, mark it as a temporary workaround since that list of providers may change in the future.
