### ISSUE TITLE
some class implemented by j2objc is not complete

### ISSUE THREAD

**Issue by lancemao** [google/j2objc#871]
for example when we try to translate this class from android source code, j2objc generates
// Implementation not generated because libcore.util.EmptyArray is on the bootclasspath.

however when we try to compile iOS project, we got:
Undefined symbols for architecture x86_64:
  "_LibcoreUtilEmptyArray_LONG", referenced from:
      _AndroidUtilLongArray_initWithInt_ in

looks like j2objc not implement the method above?

ps: we use j2objc 2.0.1 and we linked all .a file given by j2objc under lib folder

**Comment by tomball** [comment]
There are very few Android API classes (packages that start with android.*) supported by j2objc, because j2objc's focus is on sharing **_platform-independent code_** between apps. It has never been about porting Android apps, since the Android API has many core features that are very different from iOS.

[Here are the current Android utility classes supported by j2objc.](https://developers.google.com/j2objc/javadoc/android/reference/) Packages that start with libcore.* are internal to Android, and j2objc only includes those libcore classes that support its public JRE.

That said, since you found the source for android.util.LongArray (not part of j2objc), then it should be easy to also find the source for libcore.util.EmptyArray. No one is stopping developers from translating Android sources in their own projects, and [all Android source is here](https://android.googlesource.com/platform/).

**Comment by lancemao** [comment]
thanks for your quick response. I totally understand j2objc is not intended to support internal android APIs
Our issue is that j2objc also prevent us from translating EmptyArray class even though we already got the source code. As I stated in the post, j2objc generates an .m file with:
`// Implementation not generated because libcore.util.EmptyArray is on the bootclasspath.`

So since EmptyArray is not in j2objc support list, I'm wondering why it is in the bootclasspath? I didn't specify any additional classpath, I just:
`j2objc -use-arc -d out -sourcepath java `find java -name '*.java'``
