### ISSUE TITLE
Xcode9 (Swift4) NSInvalidArgumentException when trying to instantiate JavaLangInteger

### ISSUE THREAD

**Issue by marionFlx** [google/j2objc#893]
Hello,
I have some problems when I want to instantiate an JavaLangInteger.
I got an object with an JavaLangInteger field that I want to set with an INT

```
  let ageMaxJavaLang:JavaLangInteger = JavaLangInteger(value: ageMax!)
  interest.setAgeMaxWith(ageMaxJavaLang)
```
But I got : NSException	name: "NSInvalidArgumentException" - reason: "*** initialization method -initWithInteger: cannot be sent to an abstract object of class JavaLangInteger: Create a concrete instance!"	0x00000001c44429a0

**Comment by Corey-Pett** [comment]
Here is my odd workaround:

instead of 
`JavaLangInteger(value: value)`
convert your value to string and do:
`JavaLangInteger(nsString: value)`

**Comment by tomball** [comment]
Using a string argument works, but I think the real issue is that you need to use a CInt instead of an Int, since from the Swift importer's perspective, j2objc-translated code uses [C types for primitives](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithCAPIs.html). [Here's a StackOverflow discussion](https://stackoverflow.com/questions/32478352/pass-int-to-c-function) I found helpful. 

This isn't something that can be fixed or worked-around in j2objc, since the NSInvalidArgumentException is thrown by the Swift runtime when it can't find a constructor that takes a Swift Int. If anyone knows of a solution, though, please reopen this issue.
