### ISSUE TITLE
-classpath leads to no such file error

### ISSUE THREAD

**Issue by lancemao** [google/j2objc#894]
after updated to latest version i.e. 2.0.4.1, we found that -classpath parameter has to be prior than java files. If we put -classpath parameter after java file, it leads to 
'no such file:-classpath'
it seems that j2objc treat -classpath as a Java file instead of a command line parameter

in other words
`j2objc -classpath a.jar Test.java`
works file

while
`j2objc Test.java -classpath a.jar`
leads to error

2.0.3 works fine

**Comment by tomball** [comment]
I should be able to fix this later this week. In the meantime, the workaround is to reorder the arguments.

**Comment by tomball** [comment]
It looks like the problem was introduced in [63aa0d6](https://github.com/google/j2objc/commit/6eaa0d66b443688a4e6e6b960b0d7b2e8facc479#diff-f3733af711daff510832a5ab71adc5efR569), where everything after the first non-flag arg is considered a source file. Previously j2objc stopped processing args at that point, but forwarding the remaining args to javac (j2objc's front-end) caused it to pick up the -classpath.

**Comment by tomball** [comment]
Fixed in current source.
