### ISSUE TITLE
NSException VS JavaLangThrowable

### ISSUE THREAD

**Issue by lancemao** [google/j2objc#897]
in release 2.0.2, NSException is replaced by JavaLangThrowable. This looks great.
Unfortunately, we have translated A LOT of code (the whole Android framework with all dependencies) already using 2.0.1 and we modified the translated code
after updated to j2objc 2.0.4, there are many build breaks, so it is a huge work for us to check one file by one file since we cannot replace blindly

I understand adding a patch for compatibility is ugly, but still, I would like to ask if it is possible to have a parameter during translating so that we can choose either NSException or JavaLangThrowable?

**Comment by tomball** [comment]
We originally had JavaLangThrowable extend NSException, and changed it so NSExceptions could be caught in a Java "catch Throwable" try block at a developer's request. However, several problems with this were reported which couldn't be fixed, so we had to roll that feature back.

We don't support the modification of generated source files -- we consider them transient build artifacts, like .o files are. Projects do sometimes modify them, though, but they do so at their own risk.

If these modifications are to replace Android-specific code with code for iOS, refactor those files to an abstract base class with Android and iOS-specific subclasses (if there isn't any code to share, define an interface and two implementations). Separating platform-independent code makes it easier to share unit tests, and makes it easier to enhance the app in the future.

We recommend building Java files as one or more static libraries using external build rules which run something like Gradle, Maven or Make. This is much faster than translating each Java file separately using an Xcode build phase rule, and avoids keeping the generated files around (reducing the temptation to modify those files). The [JreEmulation project](https://github.com/google/j2objc/tree/master/jre_emul/JreEmulation.xcodeproj) demonstrates this approach.

**Comment by kstanger** [comment]
2.0.1 provides aliases that will help migrate your code before you upgrade to 2.0.2 or later. See here:
https://github.com/google/j2objc/commit/4104cef3665c38a988d589448165e960c7ed8486

While you're still on 2.0.1 you can update NSException references to JavaLangThrowable in your type declarations and method selectors. The method I used was: In a local client, run your build with 2.0.2 (or higher) and start fixing the related build errors, then switch back to 2.0.1 and make sure it still builds (it should since 2.0.1 provides the necessary aliases). Repeat this process until your code builds with the latest release.
