### ISSUE TITLE
Add JRE support for TLS SSLContent

### ISSUE THREAD

**Issue by rossyang** [google/j2objc#905]
Hi,
    when I try to convert java SSL socket connection, I found a problem when I try to use JavaxNetSslSSLContext_getInstanceWithNSString_(@"TLS") to get SSLContext, this function implementation is in your .a lib, I don't have a change to modify it, if I have written the same file, it will be duplicated, if I change to some other file,  original java code will be modified a lot, so could you please kindly to implement this function?

**Comment by tomball** [comment]
J2ObjC doesn't have security providers yet for SSL or secure sockets. We plan on adding additional security providers to [com.google.j2objc.security.IosSecurityProvider](https://github.com/google/j2objc/blob/master/jre_emul/Classes/com/google/j2objc/security/IosSecurityProvider.java), which will implement these providers using the iOS Security Framework. Some of this work has been delayed because the Security Framework has been recently improved, but would require a minimum iOS 10 version.

If you have iOS security experience, please consider contributing to this effort.

**Comment by tomball** [comment]
FYI, TLS 1.2 should be the default version with recent iOS versions, when using URLConnection with HTTPS URLs. If you need finer control, [here's a discussion on how to configure your app's network preferences](https://stackoverflow.com/questions/37320980/how-to-enable-tls-1-2-1-1-1-0-and-ssl-in-ios-app).

**Comment by antonio-cortes-perez** [comment]
A basic SSL socket client was implemented in version J2ObjC 2.3. Please open a new issue if more functionality is required. Also, please consider contributing to this effort.
