### ISSUE TITLE
Deserialization fails when using --prefix

### ISSUE THREAD

**Issue by mnrkeller** [google/j2objc#908]
I am having trouble deserializing objects when I set a prefix using the --prefix option.  I have tested and isolated the problem by modifying the SerializationTest.java test code as follows:

- move the Greeting class into it's own file and make the class public rather than static
- add 'package com.test;' to the new Greeting.java file
- add 'import com.test.Greeting;' to SerializationTest.java
- run j2objc on SerializationTest.java using the option: --prefix com.test=""

I then test the resulting Objective C code in my iOS app by calling the testSerialization() method.  The object serializes without complaint, however when it tries to deserialize (i.e. readObject()), a ClassNotFoundException is thrown and it indicates that com.test.Greeting cannot be found.  If I remove the --prefix option, the round trip works fine.

It would be great if you can verify that I am using the tool correctly and this is indeed an issue.  Assuming it is, are there any work arounds for this that you can suggest that would keep me moving?  I'm hoping to not have to remove the --prefix option both from a code readability point of view (my package names are quite long) and from the perspective of having to change 1000's of lines of code.

Thanks for any help you can provide.

**Comment by tomball** [comment]
Your app or test specify an iOS or macOS resource named "prefixes.properties". Since serialization is implemented using reflection, there needs to be this resource to tell the runtime what prefixes were specified during translation. [Here is the doc.](https://developers.google.com/j2objc/guides/package-prefixes#prefixed_classes_at_runtime).

I duplicated the error using your test changes, and fixed the error by adding a prefixes.properties file that contained the line "com.test=" (on macOS, resources are loaded from the same directory as the app binary). I will update SerializationTest to include this test, and will close this bug when it's added.

Thanks for your clear description of how to duplicate this problem, as it makes our job much easier.

**Comment by mnrkeller** [comment]
That worked.  Thanks for your quick response!

**Comment by tomball** [comment]
Added test case.
