### ISSUE TITLE
javax/xml/stream/XMLStreamConstants.h missing

### ISSUE THREAD

**Issue by beseder42** [google/j2objc#916]
One of my projects is missing `javax/xml/stream/XMLStreamConstants.h`. Is there any way to add it for me?

**Comment by tomball** [comment]
The jre_emul library is a fork of Android's JRE support, [which doesn't have any of the javax.xml.stream packages](https://developer.android.com/reference/packages.html). Since j2objc's purpose is to share cross-platform Java code, we can't justify making the jre_emul library bigger with this class (at least, until it's supported on Android).

However, javax.xml.stream is defined by Oracle's [Java API for XML Processing (JAXP)](https://docs.oracle.com/javase/8/docs/technotes/guides/xml/jaxp/index.html), which has open source jars [available here](https://search.maven.org/#search%7Cga%7C1%7Cjaxp-api). You should be able to use [jaxp-api-1.4.5.jar](https://search.maven.org/remotecontent?filepath=javax/xml/parsers/jaxp-api/1.4.5/jaxp-api-1.4.5.jar) on Android and translate files from [its sources jar](https://search.maven.org/remotecontent?filepath=javax/xml/parsers/jaxp-api/1.4.5/jaxp-api-1.4.5-sources.jar) using j2objc for your project.
