### ISSUE TITLE
Xcode debug cannot continue when All Exception is enabled

### ISSUE THREAD

**Issue by lancemao** [google/j2objc#925]
when All Exception is enabled in Xcode debugger. our app will stop at:
AndroidUtilLog_wWithNSString_withNSString_

and cannot continue

**Comment by tomball** [comment]
Set java.util.logging.Level's default localization bundle to null, so exception isn't thrown during its class initialization.

Please note: the JRE, like most Java library suites, uses exceptions liberally, while Objective C doesn't. There is no plan to ever provide an exception-free JRE, as it would be impossible for it to have the same documented behavior. We've made limited changes to the java.util.logging framework since it's used so much when debugging, but generally native debugging should only be done without breaking on all exceptions.
