### ISSUE TITLE
Native method not yet support header property

### ISSUE THREAD

**Issue by wdxxl** [google/j2objc#927]
Hi Team,
I was used some property, in one of java file, but this one not able convert into Header file. Is there have related tools? 

```
/*-[{
@property (nonatomic, copy) NSString *tableId;
}]-*/
```

**Comment by tomball** [comment]
Use the [@Property annotation](https://developers.google.com/j2objc/javadoc/annotations/reference/com/google/j2objc/annotations/Property):
```
import com.google.j2objc.annotations.Property;
...
    @Property("nonatomic, copy")
    private String tableId;
```
The translator generates an @property declaration in the .h file, and an @synthesize declaration in the .m file.

**Comment by wdxxl** [comment]
@tomball 
thanks for the response, one more question does annotation support IOS block function?

```
@property (nonatomic, assign) void (^callbackBlockFailed)(FISOperationCallbackModel *failedModel);
```

**Comment by tomball** [comment]
No, it doesn't. We aren't likely to support that feature, since in Java an annotation should never affect a method's logic (some annotation writers violate that rule, but they shouldn't).

If you want to define native code that way, you have two choices: JNI or two OCNI comments. We're doing more native work in separate JNI files these days, as IDEs don't support source files with multiple languages in them well. JNI is a bit more verbose, but JNI sources can be more easily shared between iOS and Android. The .m files in [jre_emul's native directory](https://github.com/google/j2objc/tree/master/jre_emul/android/platform/libcore/ojluni/src/main/native), for example, were [C files in Android's libcore library](https://android.googlesource.com/platform/libcore/+/master/ojluni/src/main/native/) which were renamed and then modified to access the Foundation and CoreFoundation APIs where necessary. All JNI requires is the C functions which are mapped to the class's native methods, while the function bodies can be C, Objective C, or C++.

If you want to continue using OCNI, then separate header and implementation comments are needed. Here's how your original question would be written:
```
/*-HEADER[
@property (nonatomic, copy) NSString *tableId;
]-*/

/*-[
@synthesize tableId = tableId_;   // Field names have a trailing underscore.
]-*/
```
I'm not familiar with using blocks in properties, but put anything you want to go in the .m file in a `/*-[` comment, and use `/*-HEADER[` for code that should go into a .h file (j2objc copies the comment body into the generated file unchanged).

**Comment by wdxxl** [comment]
@tomball thanks very much.
