### ISSUE TITLE
lucene-core & lucene-grouping 3.5.0 Reference Cycle Found issue

### ISSUE THREAD

**Issue by wdxxl** [google/j2objc#928]
Hi Team,

I'm working on lucene for cordova hybird project. (use j2objc convert luceue into cordova plugin)
but so many reference cycle found in the source code.
I'm trying to use ```@Weak and @WeakOuter``` to fix the cycle issue. but lots of works need to be done, and it will also crash cordova project, after fix just serval of the cycle issue. (any suggestion to fixing the issue like this? )

[Source code fixing](https://github.com/wdxxl/lucene) and [Tuning project](https://github.com/wdxxl/j2objc_wdxxl_demo/tree/master/cordova_lucene_tunning)

**Comment by wdxxl** [comment]
@lukhnos 
how could you fix the reference cycle in project "https://github.com/lukhnos/objclucene"? I'm able to convert Lucene 3.5 related jar files, but for indexing, it will cause memory leak issue.

**Comment by lukhnos** [comment]
This is not a J2ObjC issue. :)

I tracked down those leaks the usual way--by using Instruments and following the best practices of memory leak detection. I focused on a small number of hot areas--such as when a document gets repeatedly indexed or queried--and used both the Leaks and Allocation instruments to find abnormal memory usage. I also only focused on application classes since the leaks were unlikely to come from Foundation or J2ObjC classes.

I didn't use `cycle_finder` to find them as the report was too noisy for a large codebase. Rather I used `cycle_finder` to validate my theories. And I still had to test the app thoroughly to make sure that I didn't introduce any dangling pointers that shouldn't be there.

**Comment by tomball** [comment]
Lukhnos is right that `cycle_finder` is a poor choice for initial leak detection: the Leaks and Allocation Instruments should be used first. That's because cycle_finder uses static analysis, which can only find patterns that theoretically are issues, but during execution may or may not actually be. `cycle_finder` is most useful for catching potential cycles as the code is modified.

We therefore recommend using Instruments to fix the app's initial cycles, then [whitelist](https://developers.google.com/j2objc/guides/cycle-finder-tool#whitelisting) all remaining `cycle_finder` reported cycles as false positives. When the design changes and `cycle_finder` reports new cycles, the change is carefully reviewed to see if it's a real cycle or not: if it is then the design is fixed before being submitted, if it's a false positive then it's added to the whitelist.
