### ISSUE TITLE
Add missing JRE dependencies converting joda-time [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#93]
This is [Issue 93](https://code.google.com/p/j2objc/issues/detail?id=93) moved from a Google Code project.
Added on 2012-11-15T19:28:41.000Z by [r...@easycompany.com](http://code.google.comhttps://code.google.com/u/102244396788185517509/).
Please review that bug for more context and additional comments, but update this bug.
 Closed (Fixed).

Original labels: Type-Enhancement, Priority-Medium

**Comment by tomball** [comment]
Note: the joda-time library depends on joda-convert, which has a JDKStringConverter.java file that has a javax.xml.bind.DatatypeConverter dependency. Since javax.xml.bind isn't available on Android or j2objc, the two JDKStringConverter methods that depend on DatatypeConverter need to be commented out before transpiling, which isn't a problem because joda-time doesn't use them.

Please note that joda-time has a large set of timezone resource files (org/joda/time/tz/data/**) needed at runtime. Any iOS app using joda-time therefore needs to [copy these into the main app bundle](http://j2objc.org/docs/Java-Resources.html), with the same relative paths as in the joda-time jar file.
