### ISSUE TITLE
System.gc() not work as expected to gc WeakReference objcet?

### ISSUE THREAD

**Issue by wdxxl** [google/j2objc#931]
Hi Team,

```
import java.lang.ref.WeakReference;

public class WeakRefDemo {
    public static void main(String[] args) {
        WeakRefDemo weakRefDemo = new WeakRefDemo();
        Demo demo = weakRefDemo.new Demo("Hello WeakRef");
        WeakReference<Demo> wr = new WeakReference<Demo>(demo);
        System.out.println(wr.get().toString());
        demo = null;
        System.out.println(wr.get().toString());
        System.gc(); // code converted as JavaLangSystem_gc();
        System.out.println(wr.get()); // result not as expected?
    }

    class Demo {
        private String value;
        public Demo(String value) {
            this.value = value;
        }
        public String toString() {
            return this.value;
        }
    }
}
```

Output in Java:

```
Hello WeakRef
Hello WeakRef
null
```

Output in Objcetive-C:

```
Hello WeakRef
Hello WeakRef
Hello WeakRef
```

**Comment by tomball** [comment]
`System.gc()` is a no-op (does nothing). That's because J2ObjC uses Objective C reference counting, so there is no garbage collector to invoke.

You can cause early deallocating of weak or autoreleased objects with the [@AutoreleasePool annotation](https://developers.google.com/j2objc/javadoc/annotations/reference/com/google/j2objc/annotations/AutoreleasePool) ([Here's information from Apple on autorelease pools.](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmAutoreleasePools.html)) The jre_emul's [WeakReferenceTest](https://github.com/google/j2objc/blob/master/jre_emul/Tests/java/lang/ref/WeakReferenceTest.java#L44) demonstrates that WeakReferences work as expected. These tests all add the AutoreleasePool annotations to for loops, but searching jre_emul for AutoreleasePool will find other examples which use the annotation on a method.
