### ISSUE TITLE
Memory Leak from Gson use

### ISSUE THREAD

**Issue by danielCarlosCE** [google/j2objc#944]
Hey guys, I pretty confused how to solve this leak, so I would like any suggestion.
Here's the leak
`1 instance of JavaloStringReader leaked`

I have this code on Java
`TokenResponse response = gson.fromJson(data, TokenResponse.class);`

Therefore this in ObjectiveC
`SHRufusPayPalService_TokenResponse *response = [((ComGoogleGsonGson *) nil_chk(this$0_->gson_)) fromJsonWithNSString:data withIOSClass:SHRufusPayPalService_TokenResponse_class_()];`

**Comment by tomball** [comment]
First, do you really need all of Gson's functionality? It's a big library with lots of features, but many developers just use it to parse relatively simple server responses. If that's all you need, the same [org.json package](https://developer.android.com/reference/org/json/package-summary.html) is in Android and j2objc.

To track down leaks, you'll need to include the allocation stack, which the Instruments Leaks profile has. StringReader is a very commonly used class, so we need to know which class allocated it.

**Comment by danielCarlosCE** [comment]
It's a legacy code for a big project, we can't have doubts about Gson anymore.

**Comment by danieldickison** [comment]
We've found some leaks in gson also. It's sometimes difficult to identify the root cause of a leak, but one we've patched is gson's `LinkedTreeMap`. It creates retain cycles which can be broken by adding some `@Weak` and `@WeakOuter` annotations:
```diff
Index: gson-gson-parent-2.8.0/gson/src/main/java/com/google/gson/internal/LinkedTreeMap.java
===================================================================
--- gson-gson-parent-2.8.0/gson/src/main/java/com/google/gson/internal/LinkedTreeMap.java	(revision 138111)
+++ gson-gson-parent-2.8.0/gson/src/main/java/com/google/gson/internal/LinkedTreeMap.java	(revision 138112)
@@ -17,6 +17,9 @@
 
 package com.google.gson.internal;
 
+import com.google.j2objc.annotations.Weak;
+import com.google.j2objc.annotations.WeakOuter;
+
 import java.io.ObjectStreamException;
 import java.io.Serializable;
 import java.util.AbstractMap;
@@ -437,10 +440,13 @@
   }
 
   static final class Node<K, V> implements Entry<K, V> {
+    @Weak
     Node<K, V> parent;
     Node<K, V> left;
     Node<K, V> right;
+    @Weak
     Node<K, V> next;
+    @Weak
     Node<K, V> prev;
     final K key;
     V value;
@@ -557,6 +563,7 @@
     }
   }
 
+  @WeakOuter
   class EntrySet extends AbstractSet<Entry<K, V>> {
     @Override public int size() {
       return size;
@@ -592,6 +599,7 @@
     }
   }
 
+  @WeakOuter
   final class KeySet extends AbstractSet<K> {
     @Override public int size() {
       return size;
```

**Comment by tomball** [comment]
The j2objc team unfortunately can't support GSON since we're so small, but we're working on a feature where developers can support each other:  [external annotation files](https://checkerframework.org/annotation-file-utilities/annotation-file-format.html).

To improve Swift importing, @antonio-cortes-perez [added translator support](https://github.com/google/j2objc/commit/8025eb8857521ce3919d9dca29ade5f479d60bf6#diff-1ee8b0313e84f67f7b09cafc395240f3) for external annotation files, which Android has started using to better support Kotlin importing (both Swift and Kotlin use nullability annotations to avoid using optional types). The j2objc support is still experimental and currently limited to nullability annotations, but since no one has reported Swift importing issues with JRE classes, we're now working on:
- updating cycle_finder to support external `@Weak`, `@WeakOuter` and `@RetainsWith` annotations; and
- updating j2objc to support all annotation types.

With this upcoming support, a jaif file can be shared by GSON library users, which should be simpler and less version-sensitive than a patch file. **_This won't work today_**, but here's a preview of what Daniel's recommendation might look like as part of a GSON.jaif file:

```
package com.google.j2objc.annotations:
  annotation @RetainedWith:
    @java.lang.annotation.Target(value={FIELD})
  annotation @Weak:
    @java.lang.annotation.Target(value={FIELD, LOCAL_VARIABLE, PARAMETER})
  annotation @WeakOuter:
    @java.lang.annotation.Target(value={TYPE, LOCAL_VARIABLE})

package com.google.gson.internal:
  class LinkedTreeMap$Node:
    field parent:
      @com.google.j2objc.annotations.Weak
    field next:
      @com.google.j2objc.annotations.Weak
    field prev:
      @com.google.j2objc.annotations.Weak
  class LinkedTreeMap$EntrySet:
    @com.google.j2objc.annotations.WeakOuter
  class LinkedTreeMap$KeySet:
    @com.google.j2objc.annotations.WeakOuter
```
By including an external annotations file when translating GSON, it should be possible to address its memory leaks without modifying its source.

**Comment by congt** [comment]
Wow, that's exciting! It will eliminate most of our forks of third-party libraries to work with j2objc.

**Comment by blazek** [comment]
How is the situation? Are the `@Weak`, `@WeakOuter` and `@RetainsWith` external annotations supported? Is there a GSON.jaif available?

**Comment by antonio-cortes-perez** [comment]
See https://github.com/google/j2objc/releases/tag/2.5
We do not have a GSON.jaif.
