### ISSUE TITLE
PBEKeySpec.h file was missed in J2OBJC released project

### ISSUE THREAD

**Issue by shi1234ww** [google/j2objc#945]
I want to import javax.crypto.spec.PBEKeySpec  in Xcode; but  the PBEKeySpec.h file was not found in 
/j2objc-2.0.5/frameworks/JRE.framework/Versions/A/Headers/javax/crypto/spec folder .
![2018-02-28 10 03 44](https://user-images.githubusercontent.com/15307512/36766179-b9b65b82-1c6f-11e8-995c-7ea37c76b6ea.png)

**Comment by shi1234ww** [comment]
well Then I tried to translate PBEKeySpec.java myself, But Is an Error . ARC forbids explicit message send of 'dealloc'  . I've set complie Falgs with this file to -fno-objc-arc   . 
![2018-02-28 11 44 01](https://user-images.githubusercontent.com/15307512/36769142-69dafc7c-1c7d-11e8-926d-01ae0aa4adff.png)

**Comment by tomball** [comment]
You can translate PBEKeySpec.java yourself if you include j2objc's -use-arc flag, since your project uses ARC.

Until 2.0.6 is released, you can download [the project's source](https://github.com/google/j2objc), then following the [Building J2Objc](https://developers.google.com/j2objc/guides/building-j2objc) instructions. Since your app is using frameworks, build the full distribution (`make frameworks`).

**Comment by shi1234ww** [comment]
Very appreciate for your reply! Thanks a lot !

**Comment by antonio-cortes-perez** [comment]
Fixed in new releases.
