### ISSUE TITLE
Very slow compilation of generated Objective C files

### ISSUE THREAD

**Issue by System25** [google/j2objc#980]
Hi everybody,
 after using j2obc to transpile juniversalchardet I noticed that the compilation of the generated Objective C files is really slow. It takes around 30 minutes to compile my project after that. Before adding this library to my Java project the compilation was fine, but after adding it everything slow down.

When I run a "ps -ef | grep clang" on my Mac the output shows that distribution analisys clases the responsible for that slow build:
 org/mozilla/universalchardet/prober/distributionanalysis/Big5DistributionAnalysis.m
 org/mozilla/universalchardet/prober/distributionanalysis/EUCTWDistributionAnalysis.m
 ...

[juniversalchardet.zip](https://github.com/google/j2objc/files/2016031/juniversalchardet.zip)

Why is the compiling of this classes so slow? What can I do to accelerate the process?

Thanks

**Comment by tomball** [comment]
The problem is with the huge primitive arrays in many of these classes, which slows down LLVM (clang) parsing. The code being generated by j2objc is perfectly normal Objective C (it passes a static C array as an inlined parameter):
```
[IOSByteArray newArrayWithBytes:(jbyte[]){ 0, 0, 0,  ... } count:4096];
```
We can work around this LLVM bug by first declaring the array as a stack variable, and passing its name as the parameter:
```
static jbyte arrayBytes[] = { 0, 0, 0, ... };
[IOSByteArray newArrayWithBytes:arrayBytes count:4096];
```
You can workaround this until we update the translator, by building it in Xcode as an External Build step using a script, and add a Static Library target that depends on the External Build step (we do this in the [JreEmulation project](https://github.com/google/j2objc/tree/master/jre_emul/JreEmulation.xcodeproj)). This will take just as long to compile, but will only be rebuilt after you clean your project.

**Comment by System25** [comment]
Thanks @tomball.
Finally I used a different workaround: removing the library from the core of my project. So now I use the library as a JAR dependency in the Java project and a C++ based version in the Objective C project.

But I'm glad to hear that this problem will be fixed because you never know if the same problem may appear in a different library.

Best regards!
