### ISSUE TITLE
Strange error in LinkedHashMapEntry

### ISSUE THREAD

**Issue by System25** [google/j2objc#981]
Hi, working with security providers the following error happened:

```
ERROR  java.lang.ClassCastException: Cannot cast object of type java.util.LinkedHashMap$LinkedHashMapEntry to java.util.Map$Entry
	at 0x0000000104ebd7dd java.security.Provider.removeInvalidServices() + 381
	at 0x0000000104ebd619 java.security.Provider.ensureLegacyParsed() + 514
	at 0x0000000104ebe01d java.security.Provider.getService() + 235
```

But LinkedHashMapEntry extends HashMapEntry that implements Map.Entry.
What can be the source of this problem?

Thanks

**Comment by tomball** [comment]
My guess is that since LinkedHashMap supports null elements, [the cast check](https://github.com/google/j2objc/blob/master/jre_emul/Classes/J2ObjC_source.h#L52) is failing during iteration because of a null element.

Do you have a test example? If not, what provider did this fail with?

**Comment by tomball** [comment]
Sorry this took so long to wrap up. I can no longer duplicate this issue with the current release (2.6). Although I'm not sure exactly why (since I can't duplicate it 😉), it may have been fixed when we upgraded java.security and java.net to later Android source (jre_emul is a fork of Android's libcore library). 

Please reopen if you're still having problems.
