### ISSUE TITLE
Sharing code between iOS and Android using Bazel

### ISSUE THREAD

**Issue by vmsp** [google/j2objc#983]
I have a library with common code which uses `android.util.Log`:
```
java_library(
    name = "common",
    srcs = glob(["*.java"]),
)
```

And I have an j2objc rule for iOS which works just fine:
```
j2objc_library(
    name = "common_ios",
    deps = ["//common"],
    jre_deps = ["@bazel_j2objc//:android_util_lib"],
)
```

But when I use `common` in my Android project:
```
android_binary(
    name = "app",
    srcs = glob(["*.java"]),
    manifest = "//android:manifest",
    resource_files = ["//android:resources"],
    deps = ["//common"],
)
```

I get:
```
common/MyVeryOwnLogger.java:3: error: package android.util does not exist
import android.util.Log;
```

Which makes sense, as `android.*` libs should not be available in a `java_library` rule. Am I missing something? Is this not the recommended way to setup a project?

Thanks!

**Comment by tomball** [comment]
[android.util.Log](https://developer.android.com/reference/android/util/Log) has been a part of the Android API for years, so if your android_binary rule is failing, it's likely missing a dependency for the library that defines that class. Perhaps you haven't defined an android_sdk_repository like [this gist does](https://gist.github.com/izzyleung/a1a1fab771e15d423a7d605a74620bda)?

If that isn't the issue, you'll need to ask on [StackOverflow with the bazel tag](https://stackoverflow.com/questions/tagged/bazel), since it works with j2objc.

**Comment by vmsp** [comment]
Thanks for replying, @tomball.

If I use `android.util.Log` in code input to the `android_binary` rule it works fine. The issue is that `android.*` packages aren't exposed to the `java_library` rule, even if it is depended on by an `android_binary` rule (as is the case).

But you're right, the question is more of a "how to setup j2objc in a bazel cross-platform project" so I did ask on SO, [here](https://stackoverflow.com/questions/50741921/sharing-code-between-ios-and-android-using-bazel-and-j2objc).

**Comment by tomball** [comment]
Just a guess, but would changing the java_library to an android_library
help? I’d copy rather than change the current rule, since I doubt
j2objc_library accepts android_library dependencies.

**Comment by vmsp** [comment]
Yeah, that does seem to be the way to go. To make the type of the rule depend on which target is being built. It would be cool to have a bazel rule that handles this kind of use case (which I figure is the most common).
Thanks, Tom!
