### ISSUE TITLE
Multiple issues with HttpsUrlConnection

### ISSUE THREAD

**Issue by FD-** [google/j2objc#997]
I'm trying to load an https resource within a project utilising j2objc. In order to do that, I simply open a connection to an https url:

    final HttpURLConnection connection = (HttpURLConnection) url.openConnection();

Although this code works fine on Android, it doesn't on iOS. Please note I understand j2objc doesn't include any TLS/SSL security providers, but reading through the source code and documentation, it seems like accessing https like this should still work via the provided iOSHttpsUrlConnection implementation.

Unfortunately, I cannot seem to get it to work. When I'm calling openConnection, I get an exception saying

>  java.lang.ClassNotFoundException: java.util.logging.LoggingProxyImpl
> (null)

At the moment, I'm using the linker flags -l"jre_emul" -l"iconv" -l"z". When I add -ObjC, the ClassNotFoundException goes away. However, another exception is thrown by the openConnection call:

> java.security.NoSuchAlgorithmException: Default SSLContext not available

I'm a bit surprised to see this here: Having skimmed through the source, it seems like IOSHttpsUrlConnection uses iOS's NSURLRequest and doesn't reference SSLContext anywhere.
Do you have any idea how I could fix this issue? Also, what's the correct way of getting rid of the problem with LoggingProxyImpl?

I'm using j2objc 2.1.1 with Xcode 9.4.1. I've set up the j2objc-generated code in a static library that I use from a Swift project.

**Comment by tomball** [comment]
[This gist](https://gist.github.com/tomball/5f1175ec7f3b1663c8d067e93131b4f1) demonstrates HTTPS downloading on macOS, and it works with 2.1.1. I haven't tried it on iOS or with Swift, but the jre_emul networking code is the same for macOS and iOS.

The ClassNotFoundException you mention is from [sun.util.logging.LoggingSupport](https://github.com/google/j2objc/blob/2.1.1/jre_emul/android/platform/libcore/ojluni/src/main/java/sun/util/logging/LoggingSupport.java#L53), and it's inside a try/catch block. So if LoggingProxyImpl isn't available, the exception should have been caught (basic logging still works without it, just not all bells and whistles). Did you see this in Xcode with a "break on all exceptions" breakpoint?

The Default SSLContext exception should only happen when code is trying to create a secure socket, which isn't supported. Since you have the exception, what does its stack trace show?

**Comment by FD-** [comment]
The problem indeed was that I had set an exception breakpoint. For some reason the app crashed after resuming from the exception breakpoint. Seems like due to some locking issue - "objc[48144]: pthread_rwlock_rdlock failed (11) is printed".
I just had to disable the breakpoint and it's working great now!

Thank you very much for your immediate reply and helpful solution! I've really enjoyed using j2objc so far!
