### ISSUE TITLE
Wrong formatter in Arabic localization 

### ISSUE THREAD

**Issue by manuelko3** [google/j2objc#999]
Hello. I have some troubles with Arabic localization

As you can guess from the title, this code:
`DecimalFormat formatter = new DecimalFormat(“0”, DecimalFormatSymbols.getInstance(Locale.ENGLISH));
       formatter.setMaximumFractionDigits(MAXIMUM_FRACTION_DIGITS);`

prints
`٥٣.٩٣٠٤١٦`

instead of something like
`54.213`
We set English locale for formatting but we get Arabic format numbers insted of Demical format

**Comment by tomball** [comment]
What is your app's default locale? On iOS, the default would be what is set from Settings->General->Language & Region, which your app can override with Locale.setDefault(Locale). I ask because (as far as I know) Arabic isn't a common default setting in Belarus.

**Comment by manuelko3** [comment]
We’re developing international app and should support all possible languages, including Arabic language. The issue reproduces when phone is in Arabic.

We don’t override phone locale in our apps.
However we need to format a double with specified set of digits (English digits), but seems DecimalFormat doesn’t respect specified Locale.

**Comment by tomball** [comment]
The documentation for [DecimalFormat(String)](https://developers.google.com/j2objc/javadoc/jre/reference/java/text/DecimalFormat.html#DecimalFormat(java.lang.String)) states:

> Creates a DecimalFormat using the given pattern and the symbols for the default FORMAT locale. This is a convenient way to obtain a DecimalFormat when internationalization is not the main concern.
> 
> To obtain standard formats for a given locale, use the factory methods on NumberFormat such as getNumberInstance. These factories will return the most appropriate sub-class of NumberFormat for a given locale.

Since internationalization is a concern of your app (and since "0" is not a valid format string for decimal numbers), you'll probably want to instead use [NumberFormat.getNumberInstance(Locale)](https://developers.google.com/j2objc/javadoc/jre/reference/java/text/NumberFormat.html#getNumberInstance(java.util.Locale)), something like:

```
DecimalFormat formatter = (DecimalFormat) NumberFormat.getNumberInstance(Locale.ENGLISH);
formatter.setMaximumFractionDigits(MAXIMUM_FRACTION_DIGITS);
```
